/*
  # Seed Drug Formulary - Batch 8 (Q-R-S Medications)
  
  1. Data Seeding
    - Medications starting with Q, R, and S (~250 entries)
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Qnasl', 'beclomethasone nasal', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['40mcg', '80mcg'], false, true),
  ('Qsymia', 'phentermine/topiramate', 'Weight Loss Agent', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['3.75/23mg', '7.5/46mg', '11.25/69mg', '15/92mg'], true, true),
  ('Qualaquin', 'quinine', 'Antimalarial', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['324mg'], false, true),
  ('Quetiapine', 'quetiapine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg', '200mg', '300mg', '400mg'], false, true),
  ('Quetiapine XR', 'quetiapine extended-release', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '150mg', '200mg', '300mg', '400mg'], false, true),
  ('Quillivant XR', 'methylphenidate extended-release', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Suspension'], ARRAY['25mg/5ml'], false, true),
  ('Quinapril', 'quinapril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg', '40mg'], false, true),
  ('Quinidine', 'quinidine', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg', '300mg', '324mg'], false, true),
  ('Quinine', 'quinine sulfate', 'Antimalarial', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['324mg'], false, true),
  ('Qvar', 'beclomethasone', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['40mcg', '80mcg'], false, true),
  ('Rabeprazole', 'rabeprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg'], false, true),
  ('Raloxifene', 'raloxifene', 'SERM', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['60mg'], false, true),
  ('Raltegravir', 'raltegravir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Chewable Tablet', 'Packet'], ARRAY['400mg', '600mg', '25mg', '100mg'], false, true),
  ('Ramelteon', 'ramelteon', 'Sedative/Hypnotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['8mg'], false, true),
  ('Ramipril', 'ramipril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1.25mg', '2.5mg', '5mg', '10mg'], false, true),
  ('Ranexa', 'ranolazine', 'Antianginal', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '1000mg'], false, true),
  ('Ranitidine', 'ranitidine', 'H2 Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Syrup', 'Injection'], ARRAY['75mg', '150mg', '300mg', '15mg/ml', '25mg/ml'], false, true),
  ('Ranolazine', 'ranolazine', 'Antianginal', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '1000mg'], false, true),
  ('Rapaflo', 'silodosin', 'Alpha Blocker', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['4mg', '8mg'], false, true),
  ('Rapamune', 'sirolimus', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['0.5mg', '1mg', '2mg', '1mg/ml'], false, true),
  ('Rasagiline', 'rasagiline', 'Antiparkinson', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.5mg', '1mg'], false, true),
  ('Rasuvo', 'methotrexate', 'DMARD', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['7.5mg', '10mg', '12.5mg', '15mg', '17.5mg', '20mg', '22.5mg', '25mg', '27.5mg', '30mg'], false, true),
  ('Razadyne', 'galantamine', 'Cholinesterase Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Solution'], ARRAY['4mg', '8mg', '12mg', '8mg', '16mg', '24mg', '4mg/ml'], false, true),
  ('Rebif', 'interferon beta-1a', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['22mcg', '44mcg'], false, true),
  ('Reclast', 'zoledronic acid', 'Bisphosphonate', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg/100ml'], false, true),
  ('Reglan', 'metoclopramide', 'Antiemetic/Prokinetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection', 'ODT'], ARRAY['5mg', '10mg', '5mg/5ml', '5mg/ml'], false, true),
  ('Relafen', 'nabumetone', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '750mg'], false, true),
  ('Relenza', 'zanamivir', 'Antiviral', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Diskhaler'], ARRAY['5mg'], false, true),
  ('Relpax', 'eletriptan', 'Antimigraine', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '40mg'], false, true),
  ('Remeron', 'mirtazapine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['7.5mg', '15mg', '30mg', '45mg'], false, true),
  ('Remicade', 'infliximab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg'], false, true),
  ('Remodulin', 'treprostinil', 'Pulmonary Vasodilator', 'Tier 3', 'Preferred', ARRAY['Injection', 'Inhalation'], ARRAY['Injection', 'Nebulizer Solution'], ARRAY['1mg/ml', '2.5mg/ml', '5mg/ml', '10mg/ml'], false, true),
  ('Renagel', 'sevelamer', 'Phosphate Binder', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400mg', '800mg'], false, true),
  ('Renvela', 'sevelamer carbonate', 'Phosphate Binder', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['800mg', '0.8g', '2.4g'], false, true),
  ('Repaglinide', 'repaglinide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.5mg', '1mg', '2mg'], false, true),
  ('Repatha', 'evolocumab', 'Antilipemic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['140mg/ml', '420mg/3.5ml'], false, true),
  ('Requip', 'ropinirole', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg', '5mg'], false, true),
  ('Requip XL', 'ropinirole extended-release', 'Antiparkinson', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg', '4mg', '6mg', '8mg', '12mg'], false, true),
  ('Rescriptor', 'delavirdine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Restasis', 'cyclosporine ophthalmic', 'Immunomodulator', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Emulsion'], ARRAY['0.05%'], false, true),
  ('Restoril', 'temazepam', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['7.5mg', '15mg', '22.5mg', '30mg'], false, true),
  ('Retrovir', 'zidovudine', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Syrup', 'Injection'], ARRAY['100mg', '300mg', '10mg/ml'], false, true),
  ('Revatio', 'sildenafil', 'Pulmonary Vasodilator', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['20mg', '10mg/ml', '10mg/12.5ml'], false, true),
  ('Revlimid', 'lenalidomide', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['2.5mg', '5mg', '10mg', '15mg', '20mg', '25mg'], false, true),
  ('Rexulti', 'brexpiprazole', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg'], false, true),
  ('Reyataz', 'atazanavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Powder'], ARRAY['150mg', '200mg', '300mg', '50mg'], false, true),
  ('Rhinocort', 'budesonide nasal', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['32mcg'], false, true),
  ('Ribavirin', 'ribavirin', 'Antiviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Solution'], ARRAY['200mg', '400mg', '500mg', '600mg', '40mg/ml'], false, true),
  ('Rifabutin', 'rifabutin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['150mg'], false, true),
  ('Rifadin', 'rifampin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['150mg', '300mg', '600mg'], false, true),
  ('Rifampin', 'rifampin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['150mg', '300mg', '600mg'], false, true),
  ('Rifaximin', 'rifaximin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg', '550mg'], false, true),
  ('Riluzole', 'riluzole', 'ALS Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['50mg', '5mg/ml'], false, true),
  ('Rimantadine', 'rimantadine', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Syrup'], ARRAY['100mg', '50mg/5ml'], false, true),
  ('Riomet', 'metformin liquid', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Solution'], ARRAY['500mg/5ml'], false, true),
  ('Risedronate', 'risedronate', 'Bisphosphonate', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '30mg', '35mg', '75mg', '150mg'], false, true),
  ('Risperdal', 'risperidone', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'ODT', 'Injection'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg', '1mg/ml', '12.5mg', '25mg', '37.5mg', '50mg'], false, true),
  ('Risperidone', 'risperidone', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'ODT'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg', '1mg/ml'], false, true),
  ('Ritalin', 'methylphenidate', 'CNS Stimulant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg'], false, true),
  ('Ritalin LA', 'methylphenidate extended-release', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg', '30mg', '40mg'], false, true),
  ('Rituxan', 'rituximab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg/ml'], false, true),
  ('Rivaroxaban', 'rivaroxaban', 'Anticoagulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '10mg', '15mg', '20mg'], false, true),
  ('Rivastigmine', 'rivastigmine', 'Cholinesterase Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Transdermal'], ARRAY['Capsule', 'Solution', 'Patch'], ARRAY['1.5mg', '3mg', '4.5mg', '6mg', '2mg/ml', '4.6mg/24hr', '9.5mg/24hr', '13.3mg/24hr'], false, true),
  ('Rizatriptan', 'rizatriptan', 'Antimigraine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['5mg', '10mg'], false, true),
  ('Robaxin', 'methocarbamol', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['500mg', '750mg', '100mg/ml'], false, true),
  ('Rocaltrol', 'calcitriol', 'Vitamin D', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['0.25mcg', '0.5mcg', '1mcg/ml'], false, true),
  ('Rocephin', 'ceftriaxone', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mg', '500mg', '1g', '2g'], false, true),
  ('Roflumilast', 'roflumilast', 'PDE4 Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mcg'], false, true),
  ('Ropinirole', 'ropinirole', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg', '5mg'], false, true),
  ('Rosiglitazone', 'rosiglitazone', 'Antidiabetic', 'Tier 2', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg', '4mg', '8mg'], false, true),
  ('Rosuvastatin', 'rosuvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg', '40mg'], false, true),
  ('Rozerem', 'ramelteon', 'Sedative/Hypnotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['8mg'], false, true),
  ('Rytary', 'carbidopa/levodopa extended-release', 'Antiparkinson', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['23.75/95mg', '36.25/145mg', '48.75/195mg', '61.25/245mg'], true, true),
  ('Rythmol', 'propafenone', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg', '225mg', '300mg'], false, true),
  ('Sabril', 'vigabatrin', 'Anticonvulsant', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['500mg'], false, true),
  ('Saizen', 'somatropin', 'Growth Hormone', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg', '8.8mg'], false, true),
  ('Salmeterol', 'salmeterol', 'LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Diskus'], ARRAY['50mcg'], false, true),
  ('Samsca', 'tolvaptan', 'Vasopressin Antagonist', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg'], false, true),
  ('Sanctura', 'trospium', 'Urinary Antispasmodic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['20mg', '60mg'], false, true),
  ('Sandimmune', 'cyclosporine', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Solution', 'Injection'], ARRAY['25mg', '100mg', '100mg/ml', '50mg/ml'], false, true),
  ('Sandostatin', 'octreotide', 'Somatostatin Analog', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.05mg/ml', '0.1mg/ml', '0.2mg/ml', '0.5mg/ml', '1mg/ml', '10mg', '20mg', '30mg'], false, true),
  ('Saphris', 'asenapine', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Sublingual'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Sarafem', 'fluoxetine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg'], false, true),
  ('Savaysa', 'edoxaban', 'Anticoagulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg', '60mg'], false, true),
  ('Savella', 'milnacipran', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['12.5mg', '25mg', '50mg', '100mg'], false, true),
  ('Saxagliptin', 'saxagliptin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg'], false, true),
  ('Seasonique', 'levonorgestrel/ethinyl estradiol', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['Extended cycle'], true, true),
  ('Seconal', 'secobarbital', 'Sedative/Hypnotic', 'Tier 2', 'Non-Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg'], false, true),
  ('Selegiline', 'selegiline', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral', 'Transdermal'], ARRAY['Capsule', 'Tablet', 'ODT', 'Patch'], ARRAY['5mg', '1.25mg', '6mg/24hr', '9mg/24hr', '12mg/24hr'], false, true),
  ('Selsun', 'selenium sulfide', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Topical'], ARRAY['Shampoo', 'Lotion'], ARRAY['1%', '2.5%'], false, true),
  ('Sensipar', 'cinacalcet', 'Calcimimetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['30mg', '60mg', '90mg'], false, true),
  ('Serevent', 'salmeterol', 'LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Diskus'], ARRAY['50mcg'], false, true),
  ('Seroquel', 'quetiapine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg', '200mg', '300mg', '400mg'], false, true),
  ('Seroquel XR', 'quetiapine extended-release', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '150mg', '200mg', '300mg', '400mg'], false, true),
  ('Sertraline', 'sertraline', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['25mg', '50mg', '100mg', '20mg/ml'], false, true),
  ('Sevelamer', 'sevelamer', 'Phosphate Binder', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['400mg', '800mg', '0.8g', '2.4g'], false, true),
  ('Silenor', 'doxepin', 'Sedative/Hypnotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['3mg', '6mg'], false, true),
  ('Sildenafil', 'sildenafil', 'PDE5 Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['20mg', '25mg', '50mg', '100mg'], false, true),
  ('Silvadene', 'silver sulfadiazine', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Topical'], ARRAY['Cream'], ARRAY['1%'], false, true),
  ('Simvastatin', 'simvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg', '40mg', '80mg'], false, true),
  ('Sinemet', 'carbidopa/levodopa', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10/100mg', '25/100mg', '25/250mg'], true, true),
  ('Sinemet CR', 'carbidopa/levodopa controlled-release', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25/100mg', '50/200mg'], true, true),
  ('Singulair', 'montelukast', 'Leukotriene Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Chewable Tablet', 'Granules'], ARRAY['4mg', '5mg', '10mg'], false, true),
  ('Sirolimus', 'sirolimus', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['0.5mg', '1mg', '2mg', '1mg/ml'], false, true),
  ('Sitagliptin', 'sitagliptin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Skelaxin', 'metaxalone', 'Muscle Relaxant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400mg', '800mg'], false, true),
  ('Skyla', 'levonorgestrel IUD', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Intrauterine'], ARRAY['IUD'], ARRAY['13.5mg'], false, true),
  ('Sodium Bicarbonate', 'sodium bicarbonate', 'Antacid/Alkalinizer', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['325mg', '650mg', '4.2%', '7.5%', '8.4%'], false, true),
  ('Sodium Chloride', 'sodium chloride', 'Electrolyte', 'Tier 1', 'Preferred', ARRAY['Injection', 'Nasal', 'Ophthalmic'], ARRAY['Injection', 'Spray', 'Solution'], ARRAY['0.9%', '3%', '23.4%', '0.65%'], false, true),
  ('Sofosbuvir', 'sofosbuvir', 'Antiviral', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400mg'], false, true),
  ('Soliqua', 'insulin glargine/lixisenatide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100/33 units/mcg/ml'], true, true),
  ('Solu-Cortef', 'hydrocortisone sodium succinate', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg', '250mg', '500mg', '1000mg'], false, true),
  ('Solu-Medrol', 'methylprednisolone sodium succinate', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['40mg', '125mg', '500mg', '1g', '2g'], false, true),
  ('Soma', 'carisoprodol', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg', '350mg'], false, true),
  ('Somatropin', 'somatropin', 'Growth Hormone', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['Various strengths'], false, true),
  ('Sonata', 'zaleplon', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['5mg', '10mg'], false, true),
  ('Sorafenib', 'sorafenib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Soriatane', 'acitretin', 'Retinoid', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '17.5mg', '25mg'], false, true),
  ('Sotalol', 'sotalol', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['80mg', '120mg', '160mg', '240mg'], false, true),
  ('Sotylize', 'sotalol', 'Antiarrhythmic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Solution'], ARRAY['5mg/ml'], false, true),
  ('Sovaldi', 'sofosbuvir', 'Antiviral', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400mg'], false, true),
  ('Spectracef', 'cefditoren', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg', '400mg'], false, true),
  ('Spinosad', 'spinosad', 'Pediculicide', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Suspension'], ARRAY['0.9%'], false, true),
  ('Spiriva', 'tiotropium', 'Anticholinergic', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Capsule', 'Inhaler'], ARRAY['18mcg', '1.25mcg', '2.5mcg'], false, true),
  ('Spironolactone', 'spironolactone', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Sporanox', 'itraconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['100mg', '10mg/ml'], false, true),
  ('Sprycel', 'dasatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '50mg', '70mg', '80mg', '100mg', '140mg'], false, true),
  ('Stelara', 'ustekinumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['45mg/0.5ml', '90mg/ml'], false, true),
  ('Stendra', 'avanafil', 'PDE5 Inhibitor', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg', '200mg'], false, true),
  ('Stiolto', 'tiotropium/olodaterol', 'Anticholinergic/LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['2.5/2.5mcg'], true, true),
  ('Stivarga', 'regorafenib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['40mg'], false, true),
  ('Strattera', 'atomoxetine', 'ADHD Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '18mg', '25mg', '40mg', '60mg', '80mg', '100mg'], false, true),
  ('Streptomycin', 'streptomycin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g'], false, true),
  ('Striant', 'testosterone buccal', 'Hormone', 'Tier 3', 'Non-Preferred', ARRAY['Buccal'], ARRAY['Tablet'], ARRAY['30mg'], false, true),
  ('Stribild', 'elvitegravir/cobicistat/emtricitabine/tenofovir DF', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150/150/200/300mg'], true, true),
  ('Stromectol', 'ivermectin', 'Antiparasitic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['3mg'], false, true),
  ('Suboxone', 'buprenorphine/naloxone', 'Opioid Dependence', 'Tier 2', 'Preferred', ARRAY['Sublingual'], ARRAY['Film', 'Tablet'], ARRAY['2/0.5mg', '4/1mg', '8/2mg', '12/3mg'], true, true),
  ('Subsys', 'fentanyl sublingual spray', 'Opioid Analgesic', 'Tier 3', 'Non-Preferred', ARRAY['Sublingual'], ARRAY['Spray'], ARRAY['100mcg', '200mcg', '400mcg', '600mcg', '800mcg'], false, true),
  ('Subutex', 'buprenorphine', 'Opioid Dependence', 'Tier 2', 'Preferred', ARRAY['Sublingual'], ARRAY['Tablet'], ARRAY['2mg', '8mg'], false, true),
  ('Sucralfate', 'sucralfate', 'GI Protectant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['1g', '1g/10ml'], false, true),
  ('Sudafed', 'pseudoephedrine', 'Decongestant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Liquid'], ARRAY['30mg', '60mg', '120mg', '240mg', '15mg/5ml', '30mg/5ml'], false, true),
  ('Sular', 'nisoldipine', 'Calcium Channel Blocker', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['8.5mg', '17mg', '20mg', '25.5mg', '30mg', '34mg', '40mg'], false, true),
  ('Sulfacetamide', 'sulfacetamide', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Ophthalmic', 'Topical'], ARRAY['Solution', 'Ointment', 'Lotion'], ARRAY['10%'], false, true),
  ('Sulfamethoxazole/Trimethoprim', 'sulfamethoxazole/trimethoprim', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['400/80mg', '800/160mg', '200/40mg per 5ml'], true, true),
  ('Sulfasalazine', 'sulfasalazine', 'Aminosalicylate', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg'], false, true),
  ('Sulindac', 'sulindac', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg', '200mg'], false, true),
  ('Sumatriptan', 'sumatriptan', 'Antimigraine', 'Tier 1', 'Preferred', ARRAY['Oral', 'Nasal', 'Injection'], ARRAY['Tablet', 'Spray', 'Injection'], ARRAY['25mg', '50mg', '100mg', '5mg', '20mg', '4mg/0.5ml', '6mg/0.5ml'], false, true),
  ('Sumycin', 'tetracycline', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['250mg', '500mg'], false, true),
  ('Sunitinib', 'sunitinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['12.5mg', '25mg', '37.5mg', '50mg'], false, true),
  ('Supprelin LA', 'histrelin', 'GnRH Agonist', 'Tier 3', 'Preferred', ARRAY['Implant'], ARRAY['Implant'], ARRAY['50mg'], false, true),
  ('Suprax', 'cefixime', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Suspension'], ARRAY['400mg', '100mg/5ml', '200mg/5ml'], false, true),
  ('Sustiva', 'efavirenz', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['50mg', '200mg', '600mg'], false, true),
  ('Sutent', 'sunitinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['12.5mg', '25mg', '37.5mg', '50mg'], false, true),
  ('Sylatron', 'peginterferon alfa-2b', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['200mcg', '300mcg', '600mcg'], false, true),
  ('Symbyax', 'olanzapine/fluoxetine', 'Antidepressant/Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['3/25mg', '6/25mg', '6/50mg', '12/25mg', '12/50mg'], true, true),
  ('Symbicort', 'budesonide/formoterol', 'Corticosteroid/LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['80/4.5mcg', '160/4.5mcg'], true, true),
  ('Symlin', 'pramlintide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.6mg/ml', '1mg/ml'], false, true),
  ('Synera', 'lidocaine/tetracaine', 'Local Anesthetic', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Patch'], ARRAY['70/70mg'], true, true),
  ('Synthroid', 'levothyroxine', 'Thyroid Hormone', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mcg', '50mcg', '75mcg', '88mcg', '100mcg', '112mcg', '125mcg', '137mcg', '150mcg', '175mcg', '200mcg', '300mcg'], false, true)
ON CONFLICT (medication_name) DO NOTHING;
