/*
  # Seed Drug Formulary - Batch 3 (E-F Medications)
  
  1. Data Seeding
    - Medications starting with E and F (~150 entries)
    - Includes combination medications with proper flagging
    - Sets therapeutic class, route, and dosage forms
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Ecotrin', 'aspirin', 'Analgesic/NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['325mg', '500mg'], false, true),
  ('Edarbyclor', 'azilsartan medoxomil/chlorthalidone', 'Antihypertensive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['40/12.5mg', '40/25mg'], true, true),
  ('Edurant', 'rilpivirine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg'], false, true),
  ('Effexor', 'venlafaxine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['25mg', '37.5mg', '50mg', '75mg', '100mg'], false, true),
  ('Effexor XR', 'venlafaxine extended-release', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['37.5mg', '75mg', '150mg', '225mg'], false, true),
  ('Effient', 'prasugrel', 'Antiplatelet', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Elavil', 'amitriptyline', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '25mg', '50mg', '75mg', '100mg', '150mg'], false, true),
  ('Eldepryl', 'selegiline', 'Antiparkinson', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['5mg'], false, true),
  ('Elidel', 'pimecrolimus', 'Immunomodulator', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream'], ARRAY['1%'], false, true),
  ('Eligard', 'leuprolide acetate', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['7.5mg', '22.5mg', '30mg', '45mg'], false, true),
  ('Eliquis', 'apixaban', 'Anticoagulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg'], false, true),
  ('Ella', 'ulipristal acetate', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['30mg'], false, true),
  ('Elocon', 'mometasone furoate', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Ointment', 'Lotion'], ARRAY['0.1%'], false, true),
  ('Embeda', 'morphine sulfate/naltrexone', 'Opioid Analgesic', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['20/0.8mg', '30/1.2mg', '50/2mg', '60/2.4mg', '80/3.2mg', '100/4mg'], true, true),
  ('Emend', 'aprepitant', 'Antiemetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['40mg', '80mg', '125mg'], false, true),
  ('Emgality', 'galcanezumab', 'CGRP Inhibitor', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['120mg/ml'], false, true),
  ('Emsam', 'selegiline transdermal', 'Antidepressant', 'Tier 3', 'Non-Preferred', ARRAY['Transdermal'], ARRAY['Patch'], ARRAY['6mg/24hr', '9mg/24hr', '12mg/24hr'], false, true),
  ('Emtriva', 'emtricitabine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['200mg', '10mg/ml'], false, true),
  ('Enablex', 'darifenacin', 'Urinary Antispasmodic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['7.5mg', '15mg'], false, true),
  ('Enbrel', 'etanercept', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['25mg', '50mg'], false, true),
  ('Endocet', 'oxycodone/acetaminophen', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5/325mg', '7.5/325mg', '10/325mg'], true, true),
  ('Engerix-B', 'hepatitis B vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['20mcg/ml'], false, true),
  ('Enjuvia', 'conjugated estrogens', 'Hormone', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.3mg', '0.45mg', '0.625mg', '0.9mg', '1.25mg'], false, true),
  ('Enoxaparin', 'enoxaparin sodium', 'Anticoagulant', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['30mg', '40mg', '60mg', '80mg', '100mg', '120mg', '150mg'], false, true),
  ('Enstilar', 'calcipotriene/betamethasone', 'Antipsoriatic', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Foam'], ARRAY['0.005%/0.064%'], true, true),
  ('Entacapone', 'entacapone', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Entocort EC', 'budesonide', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['3mg'], false, true),
  ('Entresto', 'sacubitril/valsartan', 'Heart Failure Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['24/26mg', '49/51mg', '97/103mg'], true, true),
  ('Entyvio', 'vedolizumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['300mg'], false, true),
  ('Envarsus XR', 'tacrolimus extended-release', 'Immunosuppressant', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.75mg', '1mg', '4mg'], false, true),
  ('Epclusa', 'sofosbuvir/velpatasvir', 'Antiviral', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400/100mg'], true, true),
  ('Epiduo', 'adapalene/benzoyl peroxide', 'Acne Agent', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Gel'], ARRAY['0.1%/2.5%', '0.3%/2.5%'], true, true),
  ('Epinephrine', 'epinephrine', 'Sympathomimetic', 'Tier 1', 'Preferred', ARRAY['Injection', 'Inhalation'], ARRAY['Injection', 'Inhaler'], ARRAY['0.1mg/ml', '0.3mg', '0.15mg'], false, true),
  ('EpiPen', 'epinephrine auto-injector', 'Sympathomimetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Auto-Injector'], ARRAY['0.15mg', '0.3mg'], false, true),
  ('Epivir', 'lamivudine', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['150mg', '300mg', '10mg/ml'], false, true),
  ('Eplerenone', 'eplerenone', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg'], false, true),
  ('Epogen', 'epoetin alfa', 'Hematopoietic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2000 units', '3000 units', '4000 units', '10000 units', '40000 units'], false, true),
  ('Epzicom', 'abacavir/lamivudine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['600/300mg'], true, true),
  ('Equetro', 'carbamazepine extended-release', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg', '200mg', '300mg'], false, true),
  ('Erbitux', 'cetuximab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg', '200mg'], false, true),
  ('Ergocalciferol', 'ergocalciferol', 'Vitamin D', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['50000 units'], false, true),
  ('Erleada', 'apalutamide', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['60mg'], false, true),
  ('Ertapenem', 'ertapenem', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g'], false, true),
  ('Erythromycin', 'erythromycin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical', 'Ophthalmic'], ARRAY['Tablet', 'Capsule', 'Ointment', 'Solution'], ARRAY['250mg', '500mg', '2%', '0.5%'], false, true),
  ('Esbriet', 'pirfenidone', 'Antifibrotic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['267mg', '801mg'], false, true),
  ('Escitalopram', 'escitalopram', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '10mg', '20mg', '1mg/ml'], false, true),
  ('Esomeprazole', 'esomeprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Packet', 'Injection'], ARRAY['20mg', '40mg'], false, true),
  ('Estrace', 'estradiol', 'Hormone', 'Tier 1', 'Preferred', ARRAY['Oral', 'Vaginal'], ARRAY['Tablet', 'Cream'], ARRAY['0.5mg', '1mg', '2mg', '0.01%'], false, true),
  ('Estradiol', 'estradiol', 'Hormone', 'Tier 1', 'Preferred', ARRAY['Oral', 'Transdermal', 'Vaginal', 'Injection'], ARRAY['Tablet', 'Patch', 'Cream', 'Ring', 'Injection'], ARRAY['0.5mg', '1mg', '2mg'], false, true),
  ('Estratest', 'esterified estrogens/methyltestosterone', 'Hormone', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.625/1.25mg', '1.25/2.5mg'], true, true),
  ('Estring', 'estradiol vaginal ring', 'Hormone', 'Tier 2', 'Preferred', ARRAY['Vaginal'], ARRAY['Ring'], ARRAY['2mg'], false, true),
  ('Eszopiclone', 'eszopiclone', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '3mg'], false, true),
  ('Etanercept', 'etanercept', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['25mg', '50mg'], false, true),
  ('Ethambutol', 'ethambutol', 'Antitubercular', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '400mg'], false, true),
  ('Ethosuximide', 'ethosuximide', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Syrup'], ARRAY['250mg', '250mg/5ml'], false, true),
  ('Etodolac', 'etodolac', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['200mg', '300mg', '400mg', '500mg', '600mg'], false, true),
  ('Etoposide', 'etoposide', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['50mg', '100mg'], false, true),
  ('Etravirine', 'etravirine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Eucrisa', 'crisaborole', 'PDE4 Inhibitor', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Ointment'], ARRAY['2%'], false, true),
  ('Evenity', 'romosozumab', 'Bone Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['105mg/1.17ml'], false, true),
  ('Evista', 'raloxifene', 'SERM', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['60mg'], false, true),
  ('Evotaz', 'atazanavir/cobicistat', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['300/150mg'], true, true),
  ('Exalgo', 'hydromorphone extended-release', 'Opioid Analgesic', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['8mg', '12mg', '16mg', '32mg'], false, true),
  ('Excedrin', 'acetaminophen/aspirin/caffeine', 'Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Caplet'], ARRAY['250/250/65mg'], true, true),
  ('Exelon', 'rivastigmine', 'Cholinesterase Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Transdermal'], ARRAY['Capsule', 'Solution', 'Patch'], ARRAY['1.5mg', '3mg', '4.5mg', '6mg', '4.6mg/24hr', '9.5mg/24hr', '13.3mg/24hr'], false, true),
  ('Exforge', 'amlodipine/valsartan', 'Antihypertensive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5/160mg', '10/160mg', '5/320mg', '10/320mg'], true, true),
  ('Exforge HCT', 'amlodipine/valsartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5/160/12.5mg', '10/160/12.5mg', '5/160/25mg', '10/160/25mg', '10/320/25mg'], true, true),
  ('Exjade', 'deferasirox', 'Chelating Agent', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['125mg', '250mg', '500mg'], false, true),
  ('Extavia', 'interferon beta-1b', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.3mg'], false, true),
  ('Eylea', 'aflibercept', 'VEGF Inhibitor', 'Tier 3', 'Preferred', ARRAY['Intravitreal'], ARRAY['Injection'], ARRAY['2mg/0.05ml'], false, true),
  ('Ezetimibe', 'ezetimibe', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg'], false, true),
  ('Ezetimibe/Simvastatin', 'ezetimibe/simvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10/10mg', '10/20mg', '10/40mg', '10/80mg'], true, true),
  ('Fabrazyme', 'agalsidase beta', 'Enzyme Replacement', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg', '35mg'], false, true),
  ('Famciclovir', 'famciclovir', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['125mg', '250mg', '500mg'], false, true),
  ('Famotidine', 'famotidine', 'H2 Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Fanapt', 'iloperidone', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '4mg', '6mg', '8mg', '10mg', '12mg'], false, true),
  ('Farxiga', 'dapagliflozin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Fasenra', 'benralizumab', 'Monoclonal Antibody', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['30mg/ml'], false, true),
  ('Faslodex', 'fulvestrant', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mg/5ml'], false, true),
  ('Felbamate', 'felbamate', 'Anticonvulsant', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['400mg', '600mg', '600mg/5ml'], false, true),
  ('Feldene', 'piroxicam', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg'], false, true),
  ('Felodipine', 'felodipine', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Femara', 'letrozole', 'Antineoplastic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg'], false, true),
  ('Femhrt', 'norethindrone/ethinyl estradiol', 'Hormone', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.5/2.5mcg', '1/5mcg'], true, true),
  ('Fenofibrate', 'fenofibrate', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['48mg', '54mg', '145mg', '160mg'], false, true),
  ('Fenoprofen', 'fenoprofen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['200mg', '400mg', '600mg'], false, true),
  ('Fentanyl', 'fentanyl', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Transdermal', 'Buccal', 'Sublingual', 'Nasal', 'Injection'], ARRAY['Patch', 'Lozenge', 'Tablet', 'Spray', 'Injection'], ARRAY['12mcg/hr', '25mcg/hr', '50mcg/hr', '75mcg/hr', '100mcg/hr'], false, true),
  ('Fentora', 'fentanyl buccal tablet', 'Opioid Analgesic', 'Tier 3', 'Non-Preferred', ARRAY['Buccal'], ARRAY['Tablet'], ARRAY['100mcg', '200mcg', '400mcg', '600mcg', '800mcg'], false, true),
  ('Feraheme', 'ferumoxytol', 'Iron Supplement', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['510mg/17ml'], false, true),
  ('Ferriprox', 'deferiprone', 'Chelating Agent', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['500mg', '1000mg', '100mg/ml'], false, true),
  ('Ferrous Fumarate', 'ferrous fumarate', 'Iron Supplement', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['324mg'], false, true),
  ('Ferrous Gluconate', 'ferrous gluconate', 'Iron Supplement', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['240mg', '324mg'], false, true),
  ('Ferrous Sulfate', 'ferrous sulfate', 'Iron Supplement', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Elixir'], ARRAY['325mg', '220mg/5ml'], false, true),
  ('Fetzima', 'levomilnacipran', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['20mg', '40mg', '80mg', '120mg'], false, true),
  ('Fexofenadine', 'fexofenadine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['60mg', '180mg', '30mg/5ml'], false, true),
  ('Fiasp', 'insulin aspart', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Finacea', 'azelaic acid', 'Acne Agent', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Gel', 'Foam'], ARRAY['15%'], false, true),
  ('Finasteride', 'finasteride', 'Antiandrogen', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '5mg'], false, true),
  ('Fioricet', 'butalbital/acetaminophen/caffeine', 'Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['50/325/40mg'], true, true),
  ('Fiorinal', 'butalbital/aspirin/caffeine', 'Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['50/325/40mg'], true, true),
  ('Firmagon', 'degarelix', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['80mg', '120mg'], false, true),
  ('Flagyl', 'metronidazole', 'Antibiotic/Antiprotozoal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Topical', 'Vaginal'], ARRAY['Tablet', 'Capsule', 'Injection', 'Gel', 'Cream'], ARRAY['250mg', '500mg', '0.75%', '1%'], false, true),
  ('Flecainide', 'flecainide', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg', '150mg'], false, true),
  ('Flexeril', 'cyclobenzaprine', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '7.5mg', '10mg'], false, true),
  ('Flomax', 'tamsulosin', 'Alpha Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['0.4mg'], false, true),
  ('Flonase', 'fluticasone propionate nasal', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['50mcg/spray'], false, true),
  ('Florinef', 'fludrocortisone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.1mg'], false, true),
  ('Flovent', 'fluticasone propionate inhalation', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['44mcg', '110mcg', '220mcg'], false, true),
  ('Fluconazole', 'fluconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['50mg', '100mg', '150mg', '200mg'], false, true),
  ('Flucytosine', 'flucytosine', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['250mg', '500mg'], false, true),
  ('Fludrocortisone', 'fludrocortisone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.1mg'], false, true),
  ('Flumazenil', 'flumazenil', 'Benzodiazepine Antagonist', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.1mg/ml'], false, true),
  ('Flunisolide', 'flunisolide', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Nasal', 'Inhalation'], ARRAY['Spray', 'Inhaler'], ARRAY['25mcg', '29mcg', '250mcg'], false, true),
  ('Fluocinolone', 'fluocinolone acetonide', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Topical', 'Otic'], ARRAY['Cream', 'Ointment', 'Solution', 'Oil'], ARRAY['0.01%', '0.025%'], false, true),
  ('Fluocinonide', 'fluocinonide', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Gel', 'Ointment', 'Solution'], ARRAY['0.05%', '0.1%'], false, true),
  ('Fluorometholone', 'fluorometholone', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Suspension', 'Ointment'], ARRAY['0.1%', '0.25%'], false, true),
  ('Fluorouracil', 'fluorouracil', 'Antineoplastic', 'Tier 1', 'Preferred', ARRAY['Topical', 'Injection'], ARRAY['Cream', 'Solution', 'Injection'], ARRAY['0.5%', '1%', '2%', '5%', '50mg/ml'], false, true),
  ('Fluoxetine', 'fluoxetine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Solution'], ARRAY['10mg', '20mg', '40mg', '60mg', '90mg', '20mg/5ml'], false, true),
  ('Fluphenazine', 'fluphenazine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Elixir', 'Injection'], ARRAY['1mg', '2.5mg', '5mg', '10mg'], false, true),
  ('Flurazepam', 'flurazepam', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['15mg', '30mg'], false, true),
  ('Flurbiprofen', 'flurbiprofen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral', 'Ophthalmic'], ARRAY['Tablet', 'Solution'], ARRAY['50mg', '100mg', '0.03%'], false, true),
  ('Flutamide', 'flutamide', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['125mg'], false, true),
  ('Fluticasone', 'fluticasone propionate', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Inhalation', 'Nasal', 'Topical'], ARRAY['Inhaler', 'Spray', 'Cream', 'Ointment', 'Lotion'], ARRAY['44mcg', '110mcg', '220mcg', '50mcg', '0.05%'], false, true),
  ('Fluticasone/Salmeterol', 'fluticasone/salmeterol', 'Corticosteroid/LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Diskus', 'Inhaler'], ARRAY['100/50mcg', '250/50mcg', '500/50mcg', '45/21mcg', '115/21mcg', '230/21mcg'], true, true),
  ('Fluvastatin', 'fluvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['20mg', '40mg', '80mg'], false, true),
  ('Fluvoxamine', 'fluvoxamine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['25mg', '50mg', '100mg', '150mg'], false, true),
  ('Focalin', 'dexmethylphenidate', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Focalin XR', 'dexmethylphenidate extended-release', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['5mg', '10mg', '15mg', '20mg', '25mg', '30mg', '35mg', '40mg'], false, true),
  ('Folic Acid', 'folic acid', 'Vitamin', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['0.4mg', '0.8mg', '1mg'], false, true),
  ('Follistim', 'follitropin beta', 'Fertility Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['75 units', '150 units', '300 units', '600 units', '900 units'], false, true),
  ('Foradil', 'formoterol', 'LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Capsule for Inhalation'], ARRAY['12mcg'], false, true),
  ('Forfivo XL', 'bupropion extended-release', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['450mg'], false, true),
  ('Formoterol', 'formoterol', 'LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Nebulizer Solution'], ARRAY['20mcg/2ml'], false, true),
  ('Fortamet', 'metformin extended-release', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '1000mg'], false, true),
  ('Fortaz', 'ceftazidime', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['500mg', '1g', '2g', '6g'], false, true),
  ('Forteo', 'teriparatide', 'Bone Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mcg/ml'], false, true),
  ('Fosamax', 'alendronate', 'Bisphosphonate', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '10mg', '35mg', '40mg', '70mg'], false, true),
  ('Fosamax Plus D', 'alendronate/cholecalciferol', 'Bisphosphonate/Vitamin D', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['70mg/2800 units', '70mg/5600 units'], true, true),
  ('Foscarnet', 'foscarnet', 'Antiviral', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['24mg/ml'], false, true),
  ('Fosinopril', 'fosinopril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Fosphenytoin', 'fosphenytoin', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['50mg PE/ml'], false, true),
  ('Fosrenol', 'lanthanum', 'Phosphate Binder', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Chewable Tablet'], ARRAY['250mg', '500mg', '750mg', '1000mg'], false, true),
  ('Fragmin', 'dalteparin', 'Anticoagulant', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2500 units', '5000 units', '7500 units', '10000 units', '12500 units', '15000 units', '18000 units'], false, true),
  ('Frova', 'frovatriptan', 'Antimigraine', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg'], false, true),
  ('Fulvestrant', 'fulvestrant', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mg/5ml'], false, true),
  ('Furosemide', 'furosemide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['20mg', '40mg', '80mg', '10mg/ml', '40mg/5ml'], false, true),
  ('Fycompa', 'perampanel', 'Anticonvulsant', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['2mg', '4mg', '6mg', '8mg', '10mg', '12mg', '0.5mg/ml'], false, true)
ON CONFLICT (medication_name) DO NOTHING;
