/*
  # Seed Drug Formulary with Medications - Batch 2 (C-D)

  ## Overview
  This migration seeds the drug_formulary table with medications starting with C and D.
*/

INSERT INTO drug_formulary (medication_name, generic_name, tier, formulary_status, is_combination, component_medications, is_active)
VALUES
('CABERGOLINE', 'Cabergoline', 'Tier 2', 'Preferred', false, '{}', true),
('CADUET', 'Amlodipine/Atorvastatin', 'Tier 2', 'Preferred', true, ARRAY['AMLODIPINE', 'ATORVASTATIN'], true),
('CALAN', 'Verapamil', 'Tier 1', 'Preferred', false, '{}', true),
('CALAN SR', 'Verapamil SR', 'Tier 1', 'Preferred', false, '{}', true),
('CALCIPOTRIENE', 'Calcipotriene', 'Tier 2', 'Preferred', false, '{}', true),
('CALCITONIN-SALMON', 'Calcitonin', 'Tier 2', 'Preferred', false, '{}', true),
('CALCITRIOL', 'Calcitriol', 'Tier 1', 'Preferred', false, '{}', true),
('CALCIUM ACETATE', 'Calcium Acetate', 'Tier 1', 'Preferred', false, '{}', true),
('CAMBIA', 'Diclofenac Potassium', 'Tier 2', 'Preferred', false, '{}', true),
('CAMPTOSAR', 'Irinotecan', 'Tier 4', 'Non-Preferred', false, '{}', true),
('CANAGLIFLOZIN', 'Canagliflozin', 'Tier 2', 'Preferred', false, '{}', true),
('CANAGLIFLOZIN AND METFORMIN HYDROCHLORIDE', 'Canagliflozin/Metformin', 'Tier 2', 'Preferred', true, ARRAY['CANAGLIFLOZIN', 'METFORMIN HYDROCHLORIDE'], true),
('CANASA', 'Mesalamine', 'Tier 2', 'Preferred', false, '{}', true),
('CANCIDAS', 'Caspofungin', 'Tier 3', 'Preferred', false, '{}', true),
('CANDESARTAN CILEXETIL', 'Candesartan', 'Tier 1', 'Preferred', false, '{}', true),
('CANDESARTAN CILEXETIL AND HYDROCHLOROTHIAZIDE', 'Candesartan/HCTZ', 'Tier 2', 'Preferred', true, ARRAY['CANDESARTAN CILEXETIL', 'HYDROCHLOROTHIAZIDE'], true),
('CAPECITABINE', 'Capecitabine', 'Tier 2', 'Preferred', false, '{}', true),
('CAPOTEN', 'Captopril', 'Tier 1', 'Preferred', false, '{}', true),
('CAPTOPRIL', 'Captopril', 'Tier 1', 'Preferred', false, '{}', true),
('CAPTOPRIL AND HYDROCHLOROTHIAZIDE', 'Captopril/HCTZ', 'Tier 1', 'Preferred', true, ARRAY['CAPTOPRIL', 'HYDROCHLOROTHIAZIDE'], true),
('CARAFATE', 'Sucralfate', 'Tier 1', 'Preferred', false, '{}', true),
('CARBAMAZEPINE', 'Carbamazepine', 'Tier 1', 'Preferred', false, '{}', true),
('CARBATROL', 'Carbamazepine ER', 'Tier 2', 'Preferred', false, '{}', true),
('CARBIDOPA AND LEVODOPA', 'Carbidopa/Levodopa', 'Tier 1', 'Preferred', true, ARRAY['CARBIDOPA', 'LEVODOPA'], true),
('CARBOPLATIN', 'Carboplatin', 'Tier 2', 'Preferred', false, '{}', true),
('CARDENE', 'Nicardipine', 'Tier 2', 'Preferred', false, '{}', true),
('CARDIZEM', 'Diltiazem', 'Tier 1', 'Preferred', false, '{}', true),
('CARDIZEM CD', 'Diltiazem CD', 'Tier 2', 'Preferred', false, '{}', true),
('CARDIZEM LA', 'Diltiazem LA', 'Tier 2', 'Preferred', false, '{}', true),
('CARDURA', 'Doxazosin', 'Tier 1', 'Preferred', false, '{}', true),
('CARISOPRODOL', 'Carisoprodol', 'Tier 1', 'Preferred', false, '{}', true),
('CARTEOLOL HYDROCHLORIDE', 'Carteolol', 'Tier 1', 'Preferred', false, '{}', true),
('CARTIA XT', 'Diltiazem', 'Tier 2', 'Preferred', false, '{}', true),
('CARVEDILOL', 'Carvedilol', 'Tier 1', 'Preferred', false, '{}', true),
('CASODEX', 'Bicalutamide', 'Tier 1', 'Preferred', false, '{}', true),
('CASPOFUNGIN ACETATE', 'Caspofungin', 'Tier 3', 'Preferred', false, '{}', true),
('CATAFLAM', 'Diclofenac Potassium', 'Tier 1', 'Preferred', false, '{}', true),
('CATAPRES', 'Clonidine', 'Tier 1', 'Preferred', false, '{}', true),
('CECLOR', 'Cefaclor', 'Tier 1', 'Preferred', false, '{}', true),
('CEDAX', 'Ceftibuten', 'Tier 2', 'Preferred', false, '{}', true),
('CEFACLOR', 'Cefaclor', 'Tier 1', 'Preferred', false, '{}', true),
('CEFADROXIL', 'Cefadroxil', 'Tier 1', 'Preferred', false, '{}', true),
('CEFAZOLIN SODIUM', 'Cefazolin', 'Tier 1', 'Preferred', false, '{}', true),
('CEFDINIR', 'Cefdinir', 'Tier 1', 'Preferred', false, '{}', true),
('CEFEPIME HYDROCHLORIDE', 'Cefepime', 'Tier 2', 'Preferred', false, '{}', true),
('CEFIXIME', 'Cefixime', 'Tier 2', 'Preferred', false, '{}', true),
('CEFOTAXIME SODIUM', 'Cefotaxime', 'Tier 2', 'Preferred', false, '{}', true),
('CEFOTETAN', 'Cefotetan', 'Tier 2', 'Preferred', false, '{}', true),
('CEFOXITIN', 'Cefoxitin', 'Tier 2', 'Preferred', false, '{}', true),
('CEFPODOXIME PROXETIL', 'Cefpodoxime', 'Tier 1', 'Preferred', false, '{}', true),
('CEFPROZIL', 'Cefprozil', 'Tier 1', 'Preferred', false, '{}', true),
('CEFTAROLINE FOSAMIL', 'Ceftaroline', 'Tier 3', 'Preferred', false, '{}', true),
('CEFTAZIDIME', 'Ceftazidime', 'Tier 2', 'Preferred', false, '{}', true),
('CEFTIN', 'Cefuroxime Axetil', 'Tier 1', 'Preferred', false, '{}', true),
('CEFTRIAXONE SODIUM', 'Ceftriaxone', 'Tier 1', 'Preferred', false, '{}', true),
('CEFUROXIME AXETIL', 'Cefuroxime', 'Tier 1', 'Preferred', false, '{}', true),
('CELEBREX', 'Celecoxib', 'Tier 1', 'Preferred', false, '{}', true),
('CELECOXIB', 'Celecoxib', 'Tier 1', 'Preferred', false, '{}', true),
('CELEXA', 'Citalopram', 'Tier 1', 'Preferred', false, '{}', true),
('CELLCEPT', 'Mycophenolate Mofetil', 'Tier 2', 'Preferred', false, '{}', true),
('CENESTIN', 'Synthetic Conjugated Estrogens', 'Tier 2', 'Preferred', false, '{}', true),
('CEPHALEXIN', 'Cephalexin', 'Tier 1', 'Preferred', false, '{}', true),
('CETIRIZINE HYDROCHLORIDE', 'Cetirizine', 'Tier 1', 'Preferred', false, '{}', true),
('CETIRIZINE HYDROCHLORIDE AND PSEUDOEPHEDRINE HYDROCHLORIDE', 'Cetirizine/Pseudoephedrine', 'Tier 1', 'Preferred', true, ARRAY['CETIRIZINE HYDROCHLORIDE', 'PSEUDOEPHEDRINE HYDROCHLORIDE'], true),
('CHANTIX', 'Varenicline', 'Tier 2', 'Preferred', false, '{}', true),
('CHLORAMPHENICOL', 'Chloramphenicol', 'Tier 2', 'Preferred', false, '{}', true),
('CHLORDIAZEPOXIDE HYDROCHLORIDE', 'Chlordiazepoxide', 'Tier 1', 'Preferred', false, '{}', true),
('CHLORHEXIDINE GLUCONATE', 'Chlorhexidine', 'Tier 1', 'Preferred', false, '{}', true),
('CHLOROQUINE PHOSPHATE', 'Chloroquine', 'Tier 2', 'Preferred', false, '{}', true),
('CHLOROTHIAZIDE', 'Chlorothiazide', 'Tier 1', 'Preferred', false, '{}', true),
('CHLORPHENIRAMINE MALEATE', 'Chlorpheniramine', 'Tier 1', 'Preferred', false, '{}', true),
('CHLORPROMAZINE HYDROCHLORIDE', 'Chlorpromazine', 'Tier 1', 'Preferred', false, '{}', true),
('CHLORPROPAMIDE', 'Chlorpropamide', 'Tier 1', 'Preferred', false, '{}', true),
('CHLORTHALIDONE', 'Chlorthalidone', 'Tier 1', 'Preferred', false, '{}', true),
('CHLORZOXAZONE', 'Chlorzoxazone', 'Tier 1', 'Preferred', false, '{}', true),
('CHOLESTYRAMINE', 'Cholestyramine', 'Tier 1', 'Preferred', false, '{}', true),
('CIALIS', 'Tadalafil', 'Tier 2', 'Preferred', false, '{}', true),
('CICLOPIROX', 'Ciclopirox', 'Tier 2', 'Preferred', false, '{}', true),
('CILOSTAZOL', 'Cilostazol', 'Tier 1', 'Preferred', false, '{}', true),
('CIMETIDINE', 'Cimetidine', 'Tier 1', 'Preferred', false, '{}', true),
('CIMZIA', 'Certolizumab Pegol', 'Tier 4', 'Non-Preferred', false, '{}', true),
('CINACALCET HYDROCHLORIDE', 'Cinacalcet', 'Tier 2', 'Preferred', false, '{}', true),
('CIPRO', 'Ciprofloxacin', 'Tier 1', 'Preferred', false, '{}', true),
('CIPRODEX', 'Ciprofloxacin/Dexamethasone Otic', 'Tier 2', 'Preferred', true, ARRAY['CIPROFLOXACIN', 'DEXAMETHASONE'], true),
('CIPROFLOXACIN', 'Ciprofloxacin', 'Tier 1', 'Preferred', false, '{}', true),
('CIPROFLOXACIN HYDROCHLORIDE', 'Ciprofloxacin', 'Tier 1', 'Preferred', false, '{}', true),
('CISPLATIN', 'Cisplatin', 'Tier 2', 'Preferred', false, '{}', true),
('CITALOPRAM HYDROBROMIDE', 'Citalopram', 'Tier 1', 'Preferred', false, '{}', true),
('CLARINEX', 'Desloratadine', 'Tier 2', 'Preferred', false, '{}', true),
('CLARITHROMYCIN', 'Clarithromycin', 'Tier 1', 'Preferred', false, '{}', true),
('CLARITIN', 'Loratadine', 'Tier 1', 'Preferred', false, '{}', true),
('CLEMASTINE FUMARATE', 'Clemastine', 'Tier 1', 'Preferred', false, '{}', true),
('CLEOCIN', 'Clindamycin', 'Tier 1', 'Preferred', false, '{}', true),
('CLIMARA', 'Estradiol Transdermal', 'Tier 2', 'Preferred', false, '{}', true),
('CLINDAMYCIN HYDROCHLORIDE', 'Clindamycin', 'Tier 1', 'Preferred', false, '{}', true),
('CLINDAMYCIN PHOSPHATE', 'Clindamycin Topical', 'Tier 1', 'Preferred', false, '{}', true),
('CLINDAMYCIN PHOSPHATE AND BENZOYL PEROXIDE', 'Clindamycin/Benzoyl Peroxide', 'Tier 2', 'Preferred', true, ARRAY['CLINDAMYCIN PHOSPHATE', 'BENZOYL PEROXIDE'], true),
('CLOBAZAM', 'Clobazam', 'Tier 2', 'Preferred', false, '{}', true),
('CLOBETASOL PROPIONATE', 'Clobetasol', 'Tier 1', 'Preferred', false, '{}', true),
('CLOMID', 'Clomiphene', 'Tier 1', 'Preferred', false, '{}', true),
('CLOMIPHENE CITRATE', 'Clomiphene', 'Tier 1', 'Preferred', false, '{}', true),
('CLOMIPRAMINE HYDROCHLORIDE', 'Clomipramine', 'Tier 1', 'Preferred', false, '{}', true),
('CLONAZEPAM', 'Clonazepam', 'Tier 1', 'Preferred', false, '{}', true),
('CLONIDINE', 'Clonidine', 'Tier 1', 'Preferred', false, '{}', true),
('CLONIDINE HYDROCHLORIDE', 'Clonidine', 'Tier 1', 'Preferred', false, '{}', true),
('CLOPIDOGREL BISULFATE', 'Clopidogrel', 'Tier 1', 'Preferred', false, '{}', true),
('CLORAZEPATE DIPOTASSIUM', 'Clorazepate', 'Tier 1', 'Preferred', false, '{}', true),
('CLOTRIMAZOLE', 'Clotrimazole', 'Tier 1', 'Preferred', false, '{}', true),
('CLOTRIMAZOLE AND BETAMETHASONE DIPROPIONATE', 'Clotrimazole/Betamethasone', 'Tier 1', 'Preferred', true, ARRAY['CLOTRIMAZOLE', 'BETAMETHASONE DIPROPIONATE'], true),
('CLOZAPINE', 'Clozapine', 'Tier 1', 'Preferred', false, '{}', true),
('CLOZARIL', 'Clozapine', 'Tier 1', 'Preferred', false, '{}', true),
('CODEINE SULFATE', 'Codeine', 'Tier 1', 'Preferred', false, '{}', true),
('COGENTIN', 'Benztropine', 'Tier 1', 'Preferred', false, '{}', true),
('COLACE', 'Docusate Sodium', 'Tier 1', 'Preferred', false, '{}', true),
('COLCHICINE', 'Colchicine', 'Tier 2', 'Preferred', false, '{}', true),
('COLCRYS', 'Colchicine', 'Tier 2', 'Preferred', false, '{}', true),
('COLESEVELAM HYDROCHLORIDE', 'Colesevelam', 'Tier 2', 'Preferred', false, '{}', true),
('COLESTID', 'Colestipol', 'Tier 1', 'Preferred', false, '{}', true),
('COLESTIPOL HYDROCHLORIDE', 'Colestipol', 'Tier 1', 'Preferred', false, '{}', true),
('COMBIGAN', 'Brimonidine/Timolol', 'Tier 2', 'Preferred', true, ARRAY['BRIMONIDINE', 'TIMOLOL'], true),
('COMBIVENT', 'Ipratropium/Albuterol', 'Tier 1', 'Preferred', true, ARRAY['IPRATROPIUM', 'ALBUTEROL'], true),
('COMBIVENT RESPIMAT', 'Ipratropium/Albuterol', 'Tier 2', 'Preferred', true, ARRAY['IPRATROPIUM', 'ALBUTEROL'], true),
('COMBIVIR', 'Lamivudine/Zidovudine', 'Tier 2', 'Preferred', true, ARRAY['LAMIVUDINE', 'ZIDOVUDINE'], true),
('COMPLERA', 'Emtricitabine/Rilpivirine/Tenofovir', 'Tier 2', 'Preferred', true, ARRAY['EMTRICITABINE', 'RILPIVIRINE', 'TENOFOVIR'], true),
('COMTAN', 'Entacapone', 'Tier 2', 'Preferred', false, '{}', true),
('CONCERTA', 'Methylphenidate ER', 'Tier 2', 'Preferred', false, '{}', true),
('CONJUGATED ESTROGENS', 'Conjugated Estrogens', 'Tier 1', 'Preferred', false, '{}', true),
('COPAXONE', 'Glatiramer Acetate', 'Tier 3', 'Preferred', false, '{}', true),
('CORDARONE', 'Amiodarone', 'Tier 1', 'Preferred', false, '{}', true),
('COREG', 'Carvedilol', 'Tier 1', 'Preferred', false, '{}', true),
('COREG CR', 'Carvedilol CR', 'Tier 2', 'Preferred', false, '{}', true),
('CORGARD', 'Nadolol', 'Tier 1', 'Preferred', false, '{}', true),
('CORTEF', 'Hydrocortisone', 'Tier 1', 'Preferred', false, '{}', true),
('CORTISONE ACETATE', 'Cortisone', 'Tier 1', 'Preferred', false, '{}', true),
('COSENTYX', 'Secukinumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('COSOPT', 'Dorzolamide/Timolol', 'Tier 2', 'Preferred', true, ARRAY['DORZOLAMIDE', 'TIMOLOL'], true),
('COUMADIN', 'Warfarin', 'Tier 1', 'Preferred', false, '{}', true),
('COZAAR', 'Losartan', 'Tier 1', 'Preferred', false, '{}', true),
('CREON', 'Pancrelipase', 'Tier 2', 'Preferred', false, '{}', true),
('CRESTOR', 'Rosuvastatin', 'Tier 1', 'Preferred', false, '{}', true),
('CRIXIVAN', 'Indinavir', 'Tier 2', 'Preferred', false, '{}', true),
('CROMOLYN SODIUM', 'Cromolyn', 'Tier 1', 'Preferred', false, '{}', true),
('CUBICIN', 'Daptomycin', 'Tier 3', 'Preferred', false, '{}', true),
('CUPRIMINE', 'Penicillamine', 'Tier 2', 'Preferred', false, '{}', true),
('CYANOCOBALAMIN', 'Vitamin B12', 'Tier 1', 'Preferred', false, '{}', true),
('CYCLOBENZAPRINE HYDROCHLORIDE', 'Cyclobenzaprine', 'Tier 1', 'Preferred', false, '{}', true),
('CYCLOPENTOLATE HYDROCHLORIDE', 'Cyclopentolate', 'Tier 1', 'Preferred', false, '{}', true),
('CYCLOPHOSPHAMIDE', 'Cyclophosphamide', 'Tier 2', 'Preferred', false, '{}', true),
('CYCLOSPORINE', 'Cyclosporine', 'Tier 2', 'Preferred', false, '{}', true),
('CYMBALTA', 'Duloxetine', 'Tier 1', 'Preferred', false, '{}', true),
('CYPROHEPTADINE HYDROCHLORIDE', 'Cyproheptadine', 'Tier 1', 'Preferred', false, '{}', true),
('CYRAMZA', 'Ramucirumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('CYTARABINE', 'Cytarabine', 'Tier 2', 'Preferred', false, '{}', true),
('CYTOMEL', 'Liothyronine', 'Tier 1', 'Preferred', false, '{}', true),
('CYTOTEC', 'Misoprostol', 'Tier 1', 'Preferred', false, '{}', true),
('CYTOXAN', 'Cyclophosphamide', 'Tier 2', 'Preferred', false, '{}', true),
('DABIGATRAN ETEXILATE MESYLATE', 'Dabigatran', 'Tier 2', 'Preferred', false, '{}', true),
('DACARBAZINE', 'Dacarbazine', 'Tier 2', 'Preferred', false, '{}', true),
('DACTINOMYCIN', 'Dactinomycin', 'Tier 3', 'Preferred', false, '{}', true),
('DALFAMPRIDINE', 'Dalfampridine', 'Tier 3', 'Preferred', false, '{}', true),
('DALMANE', 'Flurazepam', 'Tier 1', 'Preferred', false, '{}', true),
('DANTROLENE SODIUM', 'Dantrolene', 'Tier 2', 'Preferred', false, '{}', true),
('DAPAGLIFLOZIN', 'Dapagliflozin', 'Tier 2', 'Preferred', false, '{}', true),
('DAPAGLIFLOZIN AND METFORMIN HYDROCHLORIDE', 'Dapagliflozin/Metformin', 'Tier 2', 'Preferred', true, ARRAY['DAPAGLIFLOZIN', 'METFORMIN HYDROCHLORIDE'], true),
('DAPSONE', 'Dapsone', 'Tier 1', 'Preferred', false, '{}', true),
('DAPTOMYCIN', 'Daptomycin', 'Tier 3', 'Preferred', false, '{}', true),
('DARIFENACIN', 'Darifenacin', 'Tier 2', 'Preferred', false, '{}', true),
('DARUNAVIR', 'Darunavir', 'Tier 2', 'Preferred', false, '{}', true),
('DASATINIB', 'Dasatinib', 'Tier 4', 'Non-Preferred', false, '{}', true),
('DAUNORUBICIN HYDROCHLORIDE', 'Daunorubicin', 'Tier 3', 'Preferred', false, '{}', true),
('DAYPRO', 'Oxaprozin', 'Tier 1', 'Preferred', false, '{}', true),
('DAYTRANA', 'Methylphenidate Transdermal', 'Tier 2', 'Preferred', false, '{}', true),
('DDAVP', 'Desmopressin', 'Tier 2', 'Preferred', false, '{}', true),
('DECADRON', 'Dexamethasone', 'Tier 1', 'Preferred', false, '{}', true),
('DEFERASIROX', 'Deferasirox', 'Tier 3', 'Preferred', false, '{}', true),
('DEFEROXAMINE MESYLATE', 'Deferoxamine', 'Tier 2', 'Preferred', false, '{}', true),
('DELESTROGEN', 'Estradiol Valerate', 'Tier 2', 'Preferred', false, '{}', true),
('DELTASONE', 'Prednisone', 'Tier 1', 'Preferred', false, '{}', true),
('DEMADEX', 'Torsemide', 'Tier 1', 'Preferred', false, '{}', true),
('DEMEROL', 'Meperidine', 'Tier 1', 'Preferred', false, '{}', true),
('DEPAKENE', 'Valproic Acid', 'Tier 1', 'Preferred', false, '{}', true),
('DEPAKOTE', 'Divalproex Sodium', 'Tier 1', 'Preferred', false, '{}', true),
('DEPAKOTE ER', 'Divalproex Sodium ER', 'Tier 2', 'Preferred', false, '{}', true),
('DEPO-MEDROL', 'Methylprednisolone Acetate', 'Tier 1', 'Preferred', false, '{}', true),
('DEPO-PROVERA', 'Medroxyprogesterone', 'Tier 1', 'Preferred', false, '{}', true),
('DEPO-TESTOSTERONE', 'Testosterone Cypionate', 'Tier 2', 'Preferred', false, '{}', true),
('DESCOVY', 'Emtricitabine/Tenofovir AF', 'Tier 2', 'Preferred', true, ARRAY['EMTRICITABINE', 'TENOFOVIR ALAFENAMIDE'], true),
('DESIPRAMINE HYDROCHLORIDE', 'Desipramine', 'Tier 1', 'Preferred', false, '{}', true),
('DESLORATADINE', 'Desloratadine', 'Tier 1', 'Preferred', false, '{}', true),
('DESMOPRESSIN ACETATE', 'Desmopressin', 'Tier 2', 'Preferred', false, '{}', true),
('DESOGESTREL AND ETHINYL ESTRADIOL', 'Desogestrel/Ethinyl Estradiol', 'Tier 1', 'Preferred', true, ARRAY['DESOGESTREL', 'ETHINYL ESTRADIOL'], true),
('DESONIDE', 'Desonide', 'Tier 1', 'Preferred', false, '{}', true),
('DESOXIMETASONE', 'Desoximetasone', 'Tier 2', 'Preferred', false, '{}', true),
('DESVENLAFAXINE', 'Desvenlafaxine', 'Tier 2', 'Preferred', false, '{}', true),
('DESYREL', 'Trazodone', 'Tier 1', 'Preferred', false, '{}', true),
('DETROL', 'Tolterodine', 'Tier 2', 'Preferred', false, '{}', true),
('DETROL LA', 'Tolterodine LA', 'Tier 2', 'Preferred', false, '{}', true),
('DEXAMETHASONE', 'Dexamethasone', 'Tier 1', 'Preferred', false, '{}', true),
('DEXAMETHASONE SODIUM PHOSPHATE', 'Dexamethasone', 'Tier 1', 'Preferred', false, '{}', true),
('DEXEDRINE', 'Dextroamphetamine', 'Tier 2', 'Preferred', false, '{}', true),
('DEXILANT', 'Dexlansoprazole', 'Tier 2', 'Preferred', false, '{}', true),
('DEXLANSOPRAZOLE', 'Dexlansoprazole', 'Tier 2', 'Preferred', false, '{}', true),
('DEXMEDETOMIDINE HYDROCHLORIDE', 'Dexmedetomidine', 'Tier 2', 'Preferred', false, '{}', true),
('DEXMETHYLPHENIDATE HYDROCHLORIDE', 'Dexmethylphenidate', 'Tier 2', 'Preferred', false, '{}', true),
('DEXTROAMPHETAMINE SULFATE', 'Dextroamphetamine', 'Tier 2', 'Preferred', false, '{}', true),
('DIABETA', 'Glyburide', 'Tier 1', 'Preferred', false, '{}', true),
('DIASTAT', 'Diazepam Rectal', 'Tier 2', 'Preferred', false, '{}', true),
('DIAZEPAM', 'Diazepam', 'Tier 1', 'Preferred', false, '{}', true),
('DICLOFENAC', 'Diclofenac', 'Tier 1', 'Preferred', false, '{}', true),
('DICLOFENAC POTASSIUM', 'Diclofenac Potassium', 'Tier 1', 'Preferred', false, '{}', true),
('DICLOFENAC SODIUM', 'Diclofenac Sodium', 'Tier 1', 'Preferred', false, '{}', true),
('DICLOFENAC SODIUM AND MISOPROSTOL', 'Diclofenac/Misoprostol', 'Tier 2', 'Preferred', true, ARRAY['DICLOFENAC SODIUM', 'MISOPROSTOL'], true),
('DICYCLOMINE HYDROCHLORIDE', 'Dicyclomine', 'Tier 1', 'Preferred', false, '{}', true),
('DIDANOSINE', 'Didanosine', 'Tier 2', 'Preferred', false, '{}', true),
('DIFLUCAN', 'Fluconazole', 'Tier 1', 'Preferred', false, '{}', true),
('DIFLUNISAL', 'Diflunisal', 'Tier 1', 'Preferred', false, '{}', true),
('DIGOXIN', 'Digoxin', 'Tier 1', 'Preferred', false, '{}', true),
('DILANTIN', 'Phenytoin', 'Tier 1', 'Preferred', false, '{}', true),
('DILAUDID', 'Hydromorphone', 'Tier 1', 'Preferred', false, '{}', true),
('DILTIAZEM HYDROCHLORIDE', 'Diltiazem', 'Tier 1', 'Preferred', false, '{}', true),
('DIMENHYDRINATE', 'Dimenhydrinate', 'Tier 1', 'Preferred', false, '{}', true),
('DIOVAN', 'Valsartan', 'Tier 1', 'Preferred', false, '{}', true),
('DIOVAN HCT', 'Valsartan/HCTZ', 'Tier 2', 'Preferred', true, ARRAY['VALSARTAN', 'HYDROCHLOROTHIAZIDE'], true),
('DIPHENHYDRAMINE HYDROCHLORIDE', 'Diphenhydramine', 'Tier 1', 'Preferred', false, '{}', true),
('DIPHENOXYLATE HYDROCHLORIDE AND ATROPINE SULFATE', 'Diphenoxylate/Atropine', 'Tier 1', 'Preferred', true, ARRAY['DIPHENOXYLATE HYDROCHLORIDE', 'ATROPINE SULFATE'], true),
('DIPYRIDAMOLE', 'Dipyridamole', 'Tier 1', 'Preferred', false, '{}', true),
('DISULFIRAM', 'Disulfiram', 'Tier 1', 'Preferred', false, '{}', true),
('DITROPAN', 'Oxybutynin', 'Tier 1', 'Preferred', false, '{}', true),
('DITROPAN XL', 'Oxybutynin XL', 'Tier 2', 'Preferred', false, '{}', true),
('DIURIL', 'Chlorothiazide', 'Tier 1', 'Preferred', false, '{}', true),
('DIVALPROEX SODIUM', 'Divalproex', 'Tier 1', 'Preferred', false, '{}', true),
('DOCETAXEL', 'Docetaxel', 'Tier 2', 'Preferred', false, '{}', true),
('DOCUSATE SODIUM', 'Docusate', 'Tier 1', 'Preferred', false, '{}', true),
('DOFETILIDE', 'Dofetilide', 'Tier 2', 'Preferred', false, '{}', true),
('DOLASETRON MESYLATE', 'Dolasetron', 'Tier 2', 'Preferred', false, '{}', true),
('DOLUTEGRAVIR', 'Dolutegravir', 'Tier 2', 'Preferred', false, '{}', true),
('DOLUTEGRAVIR AND LAMIVUDINE', 'Dolutegravir/Lamivudine', 'Tier 2', 'Preferred', true, ARRAY['DOLUTEGRAVIR', 'LAMIVUDINE'], true),
('DONEPEZIL HYDROCHLORIDE', 'Donepezil', 'Tier 1', 'Preferred', false, '{}', true),
('DOPAMINE HYDROCHLORIDE', 'Dopamine', 'Tier 1', 'Preferred', false, '{}', true),
('DORZOLAMIDE HYDROCHLORIDE', 'Dorzolamide', 'Tier 1', 'Preferred', false, '{}', true),
('DORZOLAMIDE HYDROCHLORIDE AND TIMOLOL MALEATE', 'Dorzolamide/Timolol', 'Tier 2', 'Preferred', true, ARRAY['DORZOLAMIDE HYDROCHLORIDE', 'TIMOLOL MALEATE'], true),
('DOVATO', 'Dolutegravir/Lamivudine', 'Tier 2', 'Preferred', true, ARRAY['DOLUTEGRAVIR', 'LAMIVUDINE'], true),
('DOXAZOSIN MESYLATE', 'Doxazosin', 'Tier 1', 'Preferred', false, '{}', true),
('DOXEPIN HYDROCHLORIDE', 'Doxepin', 'Tier 1', 'Preferred', false, '{}', true),
('DOXIL', 'Doxorubicin Liposomal', 'Tier 4', 'Non-Preferred', false, '{}', true),
('DOXORUBICIN HYDROCHLORIDE', 'Doxorubicin', 'Tier 2', 'Preferred', false, '{}', true),
('DOXYCYCLINE', 'Doxycycline', 'Tier 1', 'Preferred', false, '{}', true),
('DOXYCYCLINE HYCLATE', 'Doxycycline', 'Tier 1', 'Preferred', false, '{}', true),
('DOXYLAMINE SUCCINATE', 'Doxylamine', 'Tier 1', 'Preferred', false, '{}', true),
('DRONEDARONE', 'Dronedarone', 'Tier 2', 'Preferred', false, '{}', true),
('DROSPIRENONE AND ETHINYL ESTRADIOL', 'Drospirenone/Ethinyl Estradiol', 'Tier 1', 'Preferred', true, ARRAY['DROSPIRENONE', 'ETHINYL ESTRADIOL'], true),
('DROXIA', 'Hydroxyurea', 'Tier 2', 'Preferred', false, '{}', true),
('DUAC', 'Clindamycin/Benzoyl Peroxide', 'Tier 2', 'Preferred', true, ARRAY['CLINDAMYCIN', 'BENZOYL PEROXIDE'], true),
('DULERA', 'Mometasone/Formoterol', 'Tier 2', 'Preferred', true, ARRAY['MOMETASONE', 'FORMOTEROL'], true),
('DULOXETINE HYDROCHLORIDE', 'Duloxetine', 'Tier 1', 'Preferred', false, '{}', true),
('DUONEB', 'Ipratropium/Albuterol', 'Tier 1', 'Preferred', true, ARRAY['IPRATROPIUM', 'ALBUTEROL'], true),
('DUPIXENT', 'Dupilumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('DURAGESIC', 'Fentanyl Transdermal', 'Tier 2', 'Preferred', false, '{}', true),
('DUTASTERIDE', 'Dutasteride', 'Tier 1', 'Preferred', false, '{}', true),
('DUTASTERIDE AND TAMSULOSIN HYDROCHLORIDE', 'Dutasteride/Tamsulosin', 'Tier 2', 'Preferred', true, ARRAY['DUTASTERIDE', 'TAMSULOSIN HYDROCHLORIDE'], true),
('DYAZIDE', 'Triamterene/HCTZ', 'Tier 1', 'Preferred', true, ARRAY['TRIAMTERENE', 'HYDROCHLOROTHIAZIDE'], true),
('DYNACIN', 'Minocycline', 'Tier 1', 'Preferred', false, '{}', true),
('DYRENIUM', 'Triamterene', 'Tier 1', 'Preferred', false, '{}', true)
ON CONFLICT (medication_name) DO NOTHING;
