/*
  # Seed Drug Formulary - Batch 6 (L-M Medications)
  
  1. Data Seeding
    - Medications starting with L and M (~200 entries)
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Labetalol', 'labetalol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['100mg', '200mg', '300mg', '5mg/ml'], false, true),
  ('Lacosamide', 'lacosamide', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['50mg', '100mg', '150mg', '200mg', '10mg/ml'], false, true),
  ('Lactulose', 'lactulose', 'Laxative', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal'], ARRAY['Solution'], ARRAY['10g/15ml'], false, true),
  ('Lamictal', 'lamotrigine', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Chewable Tablet', 'ODT'], ARRAY['25mg', '100mg', '150mg', '200mg', '2mg', '5mg'], false, true),
  ('Lamictal XR', 'lamotrigine extended-release', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg', '200mg', '250mg', '300mg'], false, true),
  ('Lamisil', 'terbinafine', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Cream', 'Gel', 'Solution'], ARRAY['250mg', '1%'], false, true),
  ('Lamivudine', 'lamivudine', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['100mg', '150mg', '300mg', '5mg/ml', '10mg/ml'], false, true),
  ('Lamotrigine', 'lamotrigine', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Chewable Tablet', 'ODT'], ARRAY['25mg', '100mg', '150mg', '200mg'], false, true),
  ('Lanoxin', 'digoxin', 'Cardiac Glycoside', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['0.0625mg', '0.125mg', '0.1875mg', '0.25mg', '0.05mg/ml', '0.1mg/ml', '0.25mg/ml'], false, true),
  ('Lansoprazole', 'lansoprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'ODT'], ARRAY['15mg', '30mg'], false, true),
  ('Lantus', 'insulin glargine', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Larin', 'norethindrone/ethinyl estradiol', 'Contraceptive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1/20mcg', '1.5/30mcg'], true, true),
  ('Lasix', 'furosemide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['20mg', '40mg', '80mg', '10mg/ml', '40mg/5ml'], false, true),
  ('Latanoprost', 'latanoprost', 'Prostaglandin Analog', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.005%'], false, true),
  ('Latuda', 'lurasidone', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '40mg', '60mg', '80mg', '120mg'], false, true),
  ('Lazanda', 'fentanyl nasal spray', 'Opioid Analgesic', 'Tier 3', 'Non-Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['100mcg', '300mcg', '400mcg'], false, true),
  ('Leflunomide', 'leflunomide', 'DMARD', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg'], false, true),
  ('Lenvima', 'lenvatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['4mg', '10mg'], false, true),
  ('Lescol', 'fluvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['20mg', '40mg'], false, true),
  ('Lescol XL', 'fluvastatin extended-release', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['80mg'], false, true),
  ('Letrozole', 'letrozole', 'Antineoplastic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg'], false, true),
  ('Leucovorin', 'leucovorin', 'Folate Analog', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['5mg', '10mg', '15mg', '25mg', '10mg/ml'], false, true),
  ('Leuprolide', 'leuprolide', 'GnRH Agonist', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg/0.2ml', '3.75mg', '7.5mg', '11.25mg', '22.5mg', '30mg', '45mg'], false, true),
  ('Levalbuterol', 'levalbuterol', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler', 'Nebulizer Solution'], ARRAY['45mcg', '0.31mg/3ml', '0.63mg/3ml', '1.25mg/3ml'], false, true),
  ('Levaquin', 'levofloxacin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Ophthalmic'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['250mg', '500mg', '750mg', '25mg/ml', '0.5%', '1.5%'], false, true),
  ('Levemir', 'insulin detemir', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Levetiracetam', 'levetiracetam', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['250mg', '500mg', '750mg', '1000mg', '100mg/ml'], false, true),
  ('Levitra', 'vardenafil', 'PDE5 Inhibitor', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['2.5mg', '5mg', '10mg', '20mg'], false, true),
  ('Levobunolol', 'levobunolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.25%', '0.5%'], false, true),
  ('Levocetirizine', 'levocetirizine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '2.5mg/5ml'], false, true),
  ('Levofloxacin', 'levofloxacin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Ophthalmic'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['250mg', '500mg', '750mg', '0.5%', '1.5%'], false, true),
  ('Levonorgestrel', 'levonorgestrel', 'Contraceptive', 'Tier 1', 'Preferred', ARRAY['Oral', 'Intrauterine'], ARRAY['Tablet', 'IUD'], ARRAY['0.75mg', '1.5mg', '13.5mg', '19.5mg', '52mg'], false, true),
  ('Levorphanol', 'levorphanol', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg'], false, true),
  ('Levothyroxine', 'levothyroxine', 'Thyroid Hormone', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Capsule', 'Injection'], ARRAY['25mcg', '50mcg', '75mcg', '88mcg', '100mcg', '112mcg', '125mcg', '137mcg', '150mcg', '175mcg', '200mcg', '300mcg'], false, true),
  ('Lexapro', 'escitalopram', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '10mg', '20mg', '1mg/ml'], false, true),
  ('Lexiva', 'fosamprenavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['700mg', '50mg/ml'], false, true),
  ('Lialda', 'mesalamine', 'Aminosalicylate', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.2g'], false, true),
  ('Librax', 'chlordiazepoxide/clidinium', 'Antispasmodic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['5/2.5mg'], true, true),
  ('Lidocaine', 'lidocaine', 'Local Anesthetic', 'Tier 1', 'Preferred', ARRAY['Topical', 'Injection'], ARRAY['Cream', 'Ointment', 'Gel', 'Patch', 'Injection', 'Solution'], ARRAY['2%', '4%', '5%', '1%', '2%', '0.5%', '1%', '2%'], false, true),
  ('Lidoderm', 'lidocaine patch', 'Local Anesthetic', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Patch'], ARRAY['5%'], false, true),
  ('Liletta', 'levonorgestrel IUD', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Intrauterine'], ARRAY['IUD'], ARRAY['52mg'], false, true),
  ('Linaglipitin', 'linagliptin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg'], false, true),
  ('Linezolid', 'linezolid', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['600mg', '100mg/5ml', '2mg/ml'], false, true),
  ('Lioresal', 'baclofen', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Intrathecal'], ARRAY['Tablet', 'Injection'], ARRAY['10mg', '20mg', '0.05mg/ml', '0.5mg/ml', '2mg/ml'], false, true),
  ('Liothyronine', 'liothyronine', 'Thyroid Hormone', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['5mcg', '25mcg', '50mcg', '10mcg/ml'], false, true),
  ('Lipitor', 'atorvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg', '80mg'], false, true),
  ('Liraglutide', 'liraglutide', 'Antidiabetic/Weight Loss', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.6mg', '1.2mg', '1.8mg', '3mg'], false, true),
  ('Lisdexamfetamine', 'lisdexamfetamine', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Chewable Tablet'], ARRAY['10mg', '20mg', '30mg', '40mg', '50mg', '60mg', '70mg'], false, true),
  ('Lisinopril', 'lisinopril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['2.5mg', '5mg', '10mg', '20mg', '30mg', '40mg', '1mg/ml'], false, true),
  ('Lisinopril/HCTZ', 'lisinopril/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10/12.5mg', '20/12.5mg', '20/25mg'], true, true),
  ('Lithium', 'lithium carbonate', 'Mood Stabilizer', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['150mg', '300mg', '450mg', '600mg'], false, true),
  ('Lithium Citrate', 'lithium citrate', 'Mood Stabilizer', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Solution'], ARRAY['8mEq/5ml'], false, true),
  ('Livalo', 'pitavastatin', 'Antilipemic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '4mg'], false, true),
  ('Lodine', 'etodolac', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['200mg', '300mg', '400mg', '500mg'], false, true),
  ('Lomotil', 'diphenoxylate/atropine', 'Antidiarrheal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Liquid'], ARRAY['2.5/0.025mg'], true, true),
  ('Lonsurf', 'trifluridine/tipiracil', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15/6.14mg', '20/8.19mg'], true, true),
  ('Loperamide', 'loperamide', 'Antidiarrheal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Liquid'], ARRAY['2mg', '1mg/5ml'], false, true),
  ('Lopid', 'gemfibrozil', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['600mg'], false, true),
  ('Lopinavir/Ritonavir', 'lopinavir/ritonavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['200/50mg', '100/25mg', '80/20mg/ml'], true, true),
  ('Lopressor', 'metoprolol tartrate', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['25mg', '50mg', '100mg', '1mg/ml'], false, true),
  ('Loratadine', 'loratadine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Syrup', 'ODT'], ARRAY['10mg', '5mg/5ml'], false, true),
  ('Lorazepam', 'lorazepam', 'Benzodiazepine', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['0.5mg', '1mg', '2mg', '2mg/ml', '4mg/ml'], false, true),
  ('Lortab', 'hydrocodone/acetaminophen', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Elixir'], ARRAY['5/325mg', '7.5/325mg', '10/325mg', '7.5/325mg/15ml'], true, true),
  ('Losartan', 'losartan', 'ARB', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Losartan/HCTZ', 'losartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/12.5mg', '100/12.5mg', '100/25mg'], true, true),
  ('Lotemax', 'loteprednol', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Suspension', 'Gel', 'Ointment'], ARRAY['0.2%', '0.5%'], false, true),
  ('Lotensin', 'benazepril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg', '40mg'], false, true),
  ('Lotrel', 'amlodipine/benazepril', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['2.5/10mg', '5/10mg', '5/20mg', '5/40mg', '10/20mg', '10/40mg'], true, true),
  ('Lotrisone', 'clotrimazole/betamethasone', 'Antifungal/Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Lotion'], ARRAY['1%/0.05%'], true, true),
  ('Lovastatin', 'lovastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Lovenox', 'enoxaparin', 'Anticoagulant', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['30mg', '40mg', '60mg', '80mg', '100mg', '120mg', '150mg'], false, true),
  ('Loxapine', 'loxapine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Inhalation'], ARRAY['Capsule', 'Inhaler'], ARRAY['5mg', '10mg', '25mg', '50mg', '10mg'], false, true),
  ('Lucentis', 'ranibizumab', 'VEGF Inhibitor', 'Tier 3', 'Preferred', ARRAY['Intravitreal'], ARRAY['Injection'], ARRAY['0.5mg/0.05ml'], false, true),
  ('Lumigan', 'bimatoprost', 'Prostaglandin Analog', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.01%', '0.03%'], false, true),
  ('Lunesta', 'eszopiclone', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '3mg'], false, true),
  ('Lupron', 'leuprolide', 'GnRH Agonist', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg/0.2ml', '3.75mg', '7.5mg', '11.25mg', '22.5mg', '30mg', '45mg'], false, true),
  ('Lurasidone', 'lurasidone', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '40mg', '60mg', '80mg', '120mg'], false, true),
  ('Lyrica', 'pregabalin', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['25mg', '50mg', '75mg', '100mg', '150mg', '200mg', '225mg', '300mg', '20mg/ml'], false, true),
  ('Lynparza', 'olaparib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['100mg', '150mg', '50mg'], false, true),
  ('Maalox', 'aluminum/magnesium hydroxide', 'Antacid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Suspension', 'Tablet'], ARRAY['200/200mg', '400/400mg'], true, true),
  ('Macrobid', 'nitrofurantoin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg'], false, true),
  ('Macrodantin', 'nitrofurantoin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Magnesium Oxide', 'magnesium oxide', 'Mineral Supplement', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['400mg', '500mg'], false, true),
  ('Magnesium Sulfate', 'magnesium sulfate', 'Electrolyte', 'Tier 1', 'Preferred', ARRAY['Injection', 'Oral'], ARRAY['Injection', 'Powder'], ARRAY['50%', '500mg/ml'], false, true),
  ('Makena', 'hydroxyprogesterone caproate', 'Progestin', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mg/ml'], false, true),
  ('Maraviroc', 'maraviroc', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg', '300mg'], false, true),
  ('Marinol', 'dronabinol', 'Antiemetic/Appetite Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Mavik', 'trandolapril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '4mg'], false, true),
  ('Maxalt', 'rizatriptan', 'Antimigraine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['5mg', '10mg'], false, true),
  ('Maxzide', 'triamterene/hydrochlorothiazide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['37.5/25mg', '75/50mg'], true, true),
  ('Medroxyprogesterone', 'medroxyprogesterone', 'Progestin', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['2.5mg', '5mg', '10mg', '150mg/ml', '400mg/ml'], false, true),
  ('Mefenamic Acid', 'mefenamic acid', 'NSAID', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['250mg'], false, true),
  ('Mefloquine', 'mefloquine', 'Antimalarial', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg'], false, true),
  ('Megace', 'megestrol', 'Progestin/Appetite Stimulant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['20mg', '40mg', '40mg/ml', '625mg/5ml'], false, true),
  ('Mekinist', 'trametinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.5mg', '2mg'], false, true),
  ('Meloxicam', 'meloxicam', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Suspension'], ARRAY['7.5mg', '15mg', '7.5mg/5ml'], false, true),
  ('Melphalan', 'melphalan', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['2mg', '50mg'], false, true),
  ('Memantine', 'memantine', 'NMDA Antagonist', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Solution'], ARRAY['5mg', '10mg', '7mg', '14mg', '21mg', '28mg', '2mg/ml'], false, true),
  ('Menopur', 'menotropins', 'Fertility Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['75 units'], false, true),
  ('Meperidine', 'meperidine', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Syrup', 'Injection'], ARRAY['50mg', '100mg', '50mg/5ml', '25mg/ml', '50mg/ml', '100mg/ml'], false, true),
  ('Mepron', 'atovaquone', 'Antiprotozoal', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Suspension'], ARRAY['750mg/5ml'], false, true),
  ('Mercaptopurine', 'mercaptopurine', 'Antineoplastic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['50mg', '20mg/ml'], false, true),
  ('Meropenem', 'meropenem', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['500mg', '1g'], false, true),
  ('Mesalamine', 'mesalamine', 'Aminosalicylate', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal'], ARRAY['Tablet', 'Capsule', 'Enema', 'Suppository'], ARRAY['250mg', '400mg', '500mg', '800mg', '1.2g', '4g/60ml', '1000mg'], false, true),
  ('Metadate CD', 'methylphenidate extended-release', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg', '30mg', '40mg', '50mg', '60mg'], false, true),
  ('Metformin', 'metformin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['500mg', '850mg', '1000mg', '500mg/5ml'], false, true),
  ('Metformin ER', 'metformin extended-release', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '750mg', '1000mg'], false, true),
  ('Methadone', 'methadone', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['5mg', '10mg', '40mg', '5mg/5ml', '10mg/5ml', '10mg/ml'], false, true),
  ('Methimazole', 'methimazole', 'Antithyroid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Methocarbamol', 'methocarbamol', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['500mg', '750mg', '100mg/ml'], false, true),
  ('Methotrexate', 'methotrexate', 'Antineoplastic/DMARD', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['2.5mg', '5mg', '7.5mg', '10mg', '15mg', '25mg/ml'], false, true),
  ('Methyldopa', 'methyldopa', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg', '500mg'], false, true),
  ('Methylphenidate', 'methylphenidate', 'CNS Stimulant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Solution', 'Patch'], ARRAY['5mg', '10mg', '20mg', '18mg', '27mg', '36mg', '54mg', '5mg/5ml'], false, true),
  ('Methylprednisolone', 'methylprednisolone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['4mg', '8mg', '16mg', '32mg', '40mg', '125mg', '500mg', '1g'], false, true),
  ('Metoclopramide', 'metoclopramide', 'Antiemetic/Prokinetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection', 'ODT'], ARRAY['5mg', '10mg', '5mg/5ml', '5mg/ml'], false, true),
  ('Metolazone', 'metolazone', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Metoprolol Succinate', 'metoprolol succinate', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg', '200mg'], false, true),
  ('Metoprolol Tartrate', 'metoprolol tartrate', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['25mg', '50mg', '100mg', '1mg/ml'], false, true),
  ('MetroGel', 'metronidazole gel', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Topical', 'Vaginal'], ARRAY['Gel'], ARRAY['0.75%', '1%'], false, true),
  ('Metronidazole', 'metronidazole', 'Antibiotic/Antiprotozoal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Topical', 'Vaginal'], ARRAY['Tablet', 'Capsule', 'Injection', 'Gel', 'Cream', 'Lotion'], ARRAY['250mg', '500mg', '375mg', '5mg/ml', '0.75%', '1%'], false, true),
  ('Mevacor', 'lovastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Mexiletine', 'mexiletine', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['150mg', '200mg', '250mg'], false, true),
  ('Micardis', 'telmisartan', 'ARB', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '40mg', '80mg'], false, true),
  ('Micardis HCT', 'telmisartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['40/12.5mg', '80/12.5mg', '80/25mg'], true, true),
  ('Miconazole', 'miconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Topical', 'Vaginal', 'Buccal'], ARRAY['Cream', 'Powder', 'Spray', 'Insert', 'Tablet'], ARRAY['2%', '100mg', '200mg', '1200mg', '50mg'], false, true),
  ('Micronase', 'glyburide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.25mg', '2.5mg', '5mg'], false, true),
  ('Midazolam', 'midazolam', 'Benzodiazepine', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Nasal'], ARRAY['Syrup', 'Injection', 'Spray'], ARRAY['2mg/ml', '1mg/ml', '5mg/ml', '5mg'], false, true),
  ('Midodrine', 'midodrine', 'Alpha Agonist', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Miglitol', 'miglitol', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Minocycline', 'minocycline', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['50mg', '75mg', '100mg'], false, true),
  ('Minoxidil', 'minoxidil', 'Antihypertensive/Hair Growth', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Solution', 'Foam'], ARRAY['2.5mg', '10mg', '2%', '5%'], false, true),
  ('Miralax', 'polyethylene glycol 3350', 'Laxative', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Powder'], ARRAY['17g'], false, true),
  ('Mirapex', 'pramipexole', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.125mg', '0.25mg', '0.5mg', '0.75mg', '1mg', '1.5mg'], false, true),
  ('Mirapex ER', 'pramipexole extended-release', 'Antiparkinson', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.375mg', '0.75mg', '1.5mg', '2.25mg', '3mg', '3.75mg', '4.5mg'], false, true),
  ('Mirena', 'levonorgestrel IUD', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Intrauterine'], ARRAY['IUD'], ARRAY['52mg'], false, true),
  ('Mirtazapine', 'mirtazapine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['7.5mg', '15mg', '30mg', '45mg'], false, true),
  ('Misoprostol', 'misoprostol', 'Prostaglandin', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mcg', '200mcg'], false, true),
  ('Mobic', 'meloxicam', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['7.5mg', '15mg', '7.5mg/5ml'], false, true),
  ('Modafinil', 'modafinil', 'Wakefulness Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Moexipril', 'moexipril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['7.5mg', '15mg'], false, true),
  ('Mometasone', 'mometasone furoate', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Nasal', 'Topical', 'Inhalation'], ARRAY['Spray', 'Cream', 'Ointment', 'Lotion', 'Inhaler'], ARRAY['50mcg', '0.1%', '110mcg', '220mcg'], false, true),
  ('Monopril', 'fosinopril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Montelukast', 'montelukast', 'Leukotriene Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Chewable Tablet', 'Granules'], ARRAY['4mg', '5mg', '10mg'], false, true),
  ('Morphine', 'morphine sulfate', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Rectal'], ARRAY['Tablet', 'Capsule', 'Solution', 'Injection', 'Suppository'], ARRAY['15mg', '30mg', '60mg', '100mg', '200mg', '10mg/5ml', '20mg/5ml', '20mg/ml', '1mg/ml', '2mg/ml', '4mg/ml', '5mg', '10mg', '20mg', '30mg'], false, true),
  ('Motrin', 'ibuprofen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Suspension'], ARRAY['200mg', '400mg', '600mg', '800mg', '100mg/5ml'], false, true),
  ('Movantik', 'naloxegol', 'Opioid Antagonist', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['12.5mg', '25mg'], false, true),
  ('Moxifloxacin', 'moxifloxacin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Ophthalmic'], ARRAY['Tablet', 'Injection', 'Solution'], ARRAY['400mg', '0.5%'], false, true),
  ('MS Contin', 'morphine sulfate extended-release', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg', '60mg', '100mg', '200mg'], false, true),
  ('Mucinex', 'guaifenesin', 'Expectorant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['600mg', '1200mg'], false, true),
  ('Multaq', 'dronedarone', 'Antiarrhythmic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400mg'], false, true),
  ('Mupirocin', 'mupirocin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Topical', 'Nasal'], ARRAY['Ointment', 'Cream'], ARRAY['2%'], false, true),
  ('Myambutol', 'ethambutol', 'Antitubercular', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '400mg'], false, true),
  ('Mycophenolate', 'mycophenolate mofetil', 'Immunosuppressant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Tablet', 'Suspension', 'Injection'], ARRAY['250mg', '500mg', '200mg/ml', '500mg'], false, true),
  ('Myrbetriq', 'mirabegron', 'Urinary Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg'], false, true)
ON CONFLICT (medication_name) DO NOTHING;
