/*
  # Seed Drug Formulary - Batch 7 (N-O-P Medications)
  
  1. Data Seeding
    - Medications starting with N, O, and P (~250 entries)
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Nabumetone', 'nabumetone', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '750mg'], false, true),
  ('Nadolol', 'nadolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '40mg', '80mg', '120mg', '160mg'], false, true),
  ('Nafcillin', 'nafcillin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g', '2g'], false, true),
  ('Naftifine', 'naftifine', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Gel'], ARRAY['1%', '2%'], false, true),
  ('Naloxone', 'naloxone', 'Opioid Antagonist', 'Tier 1', 'Preferred', ARRAY['Injection', 'Nasal'], ARRAY['Injection', 'Spray'], ARRAY['0.4mg/ml', '1mg/ml', '2mg', '4mg'], false, true),
  ('Naltrexone', 'naltrexone', 'Opioid Antagonist', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['50mg', '380mg'], false, true),
  ('Namenda', 'memantine', 'NMDA Antagonist', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '10mg', '2mg/ml'], false, true),
  ('Namenda XR', 'memantine extended-release', 'NMDA Antagonist', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['7mg', '14mg', '21mg', '28mg'], false, true),
  ('Namzaric', 'memantine/donepezil', 'Alzheimer Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['7/10mg', '14/10mg', '21/10mg', '28/10mg'], true, true),
  ('Naprosyn', 'naproxen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['250mg', '375mg', '500mg', '125mg/5ml'], false, true),
  ('Naproxen', 'naproxen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Suspension'], ARRAY['220mg', '250mg', '375mg', '500mg', '125mg/5ml'], false, true),
  ('Naproxen Sodium', 'naproxen sodium', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['220mg', '275mg', '550mg'], false, true),
  ('Naratriptan', 'naratriptan', 'Antimigraine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2.5mg'], false, true),
  ('Narcan', 'naloxone', 'Opioid Antagonist', 'Tier 1', 'Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['4mg'], false, true),
  ('Nasacort', 'triamcinolone acetonide nasal', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['55mcg'], false, true),
  ('Nasonex', 'mometasone furoate nasal', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Nasal'], ARRAY['Spray'], ARRAY['50mcg'], false, true),
  ('Natazia', 'estradiol valerate/dienogest', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['Quadriphasic'], true, true),
  ('Nateglinide', 'nateglinide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['60mg', '120mg'], false, true),
  ('Navane', 'thiothixene', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1mg', '2mg', '5mg', '10mg', '20mg'], false, true),
  ('Nebcin', 'tobramycin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg/ml', '40mg/ml'], false, true),
  ('Nebivolol', 'nebivolol', 'Beta Blocker', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg', '20mg'], false, true),
  ('Nefazodone', 'nefazodone', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg', '150mg', '200mg', '250mg'], false, true),
  ('Neoral', 'cyclosporine modified', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['25mg', '100mg', '100mg/ml'], false, true),
  ('Neosporin', 'neomycin/polymyxin/bacitracin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Topical', 'Ophthalmic'], ARRAY['Ointment'], ARRAY['Triple Antibiotic'], true, true),
  ('Neulasta', 'pegfilgrastim', 'Hematopoietic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['6mg/0.6ml'], false, true),
  ('Neupogen', 'filgrastim', 'Hematopoietic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['300mcg/ml', '480mcg/1.6ml'], false, true),
  ('Neurontin', 'gabapentin', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Solution'], ARRAY['100mg', '300mg', '400mg', '600mg', '800mg', '250mg/5ml'], false, true),
  ('Nexium', 'esomeprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Packet', 'Injection'], ARRAY['20mg', '40mg'], false, true),
  ('Niacin', 'niacin', 'Antilipemic/Vitamin', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['250mg', '500mg', '750mg', '1000mg'], false, true),
  ('Niaspan', 'niacin extended-release', 'Antilipemic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '750mg', '1000mg'], false, true),
  ('Nicardipine', 'nicardipine', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['20mg', '30mg', '2.5mg/ml'], false, true),
  ('Nicotine', 'nicotine', 'Smoking Cessation', 'Tier 1', 'Preferred', ARRAY['Transdermal', 'Oral', 'Nasal', 'Inhalation'], ARRAY['Patch', 'Gum', 'Lozenge', 'Spray', 'Inhaler'], ARRAY['7mg', '14mg', '21mg', '2mg', '4mg'], false, true),
  ('Nifedipine', 'nifedipine', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['10mg', '20mg', '30mg', '60mg', '90mg'], false, true),
  ('Nilandron', 'nilutamide', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg'], false, true),
  ('Nilotinib', 'nilotinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['150mg', '200mg'], false, true),
  ('Nimodipine', 'nimodipine', 'Calcium Channel Blocker', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['30mg', '6mg/ml'], false, true),
  ('Ninlaro', 'ixazomib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['2.3mg', '3mg', '4mg'], false, true),
  ('Niravam', 'alprazolam ODT', 'Benzodiazepine', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['ODT'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg'], false, true),
  ('Nitrofurantoin', 'nitrofurantoin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Suspension'], ARRAY['25mg', '50mg', '100mg', '25mg/5ml'], false, true),
  ('Nitroglycerin', 'nitroglycerin', 'Antianginal', 'Tier 1', 'Preferred', ARRAY['Sublingual', 'Transdermal', 'Topical', 'Injection'], ARRAY['Tablet', 'Spray', 'Patch', 'Ointment', 'Injection'], ARRAY['0.3mg', '0.4mg', '0.6mg', '0.4mg/spray', '0.1mg/hr', '0.2mg/hr', '0.4mg/hr', '0.6mg/hr', '2%', '5mg/ml'], false, true),
  ('Nitropress', 'nitroprusside', 'Vasodilator', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['25mg/ml'], false, true),
  ('Nizatidine', 'nizatidine', 'H2 Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['150mg', '300mg', '15mg/ml'], false, true),
  ('Nizoral', 'ketoconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Cream', 'Shampoo'], ARRAY['200mg', '2%'], false, true),
  ('Norco', 'hydrocodone/acetaminophen', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5/325mg', '7.5/325mg', '10/325mg'], true, true),
  ('Norditropin', 'somatropin', 'Growth Hormone', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg', '10mg', '15mg', '30mg'], false, true),
  ('Norepinephrine', 'norepinephrine', 'Vasopressor', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg/ml'], false, true),
  ('Norfloxacin', 'norfloxacin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Ophthalmic'], ARRAY['Tablet', 'Solution'], ARRAY['400mg', '0.3%'], false, true),
  ('Norpace', 'disopyramide', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg', '150mg'], false, true),
  ('Nortriptyline', 'nortriptyline', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['10mg', '25mg', '50mg', '75mg', '10mg/5ml'], false, true),
  ('Norvasc', 'amlodipine', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Norvir', 'ritonavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['100mg', '80mg/ml'], false, true),
  ('Novolin 70/30', 'NPH/regular insulin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], true, true),
  ('Novolin N', 'NPH insulin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Novolin R', 'regular insulin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('NovoLog', 'insulin aspart', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('NovoLog Mix 70/30', 'insulin aspart protamine/insulin aspart', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], true, true),
  ('Nucala', 'mepolizumab', 'Monoclonal Antibody', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg'], false, true),
  ('Nucynta', 'tapentadol', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '75mg', '100mg'], false, true),
  ('Nucynta ER', 'tapentadol extended-release', 'Opioid Analgesic', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg', '150mg', '200mg', '250mg'], false, true),
  ('NuvaRing', 'etonogestrel/ethinyl estradiol ring', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Vaginal'], ARRAY['Ring'], ARRAY['0.12mg/0.015mg per day'], true, true),
  ('Nystatin', 'nystatin', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Suspension', 'Cream', 'Ointment', 'Powder'], ARRAY['500000 units', '100000 units/ml', '100000 units/g'], false, true),
  ('Ocrevus', 'ocrelizumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['300mg/10ml'], false, true),
  ('Octreotide', 'octreotide', 'Somatostatin Analog', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.05mg/ml', '0.1mg/ml', '0.2mg/ml', '0.5mg/ml', '1mg/ml', '10mg', '20mg', '30mg'], false, true),
  ('Odefsey', 'emtricitabine/rilpivirine/tenofovir AF', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200/25/25mg'], true, true),
  ('Ofev', 'nintedanib', 'Antifibrotic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg', '150mg'], false, true),
  ('Ofloxacin', 'ofloxacin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Ophthalmic', 'Otic'], ARRAY['Tablet', 'Solution'], ARRAY['200mg', '300mg', '400mg', '0.3%'], false, true),
  ('Olanzapine', 'olanzapine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'ODT', 'Injection'], ARRAY['2.5mg', '5mg', '7.5mg', '10mg', '15mg', '20mg', '210mg', '300mg', '405mg'], false, true),
  ('Olanzapine/Fluoxetine', 'olanzapine/fluoxetine', 'Antidepressant/Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['3/25mg', '6/25mg', '6/50mg', '12/25mg', '12/50mg'], true, true),
  ('Olmesartan', 'olmesartan', 'ARB', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '20mg', '40mg'], false, true),
  ('Olmesartan/HCTZ', 'olmesartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20/12.5mg', '40/12.5mg', '40/25mg'], true, true),
  ('Olopatadine', 'olopatadine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Ophthalmic', 'Nasal'], ARRAY['Solution', 'Spray'], ARRAY['0.1%', '0.2%', '0.7%', '0.6%'], false, true),
  ('Omalizumab', 'omalizumab', 'Monoclonal Antibody', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['75mg/0.5ml', '150mg/ml'], false, true),
  ('Omega-3 Fatty Acids', 'omega-3 fatty acids', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1g'], false, true),
  ('Omeprazole', 'omeprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Packet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Omnicef', 'cefdinir', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Suspension'], ARRAY['300mg', '125mg/5ml', '250mg/5ml'], false, true),
  ('Omnipred', 'prednisolone acetate', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Suspension'], ARRAY['1%'], false, true),
  ('Ondansetron', 'ondansetron', 'Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'ODT', 'Solution', 'Injection'], ARRAY['4mg', '8mg', '4mg/5ml', '2mg/ml'], false, true),
  ('Onglyza', 'saxagliptin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg'], false, true),
  ('Onmel', 'itraconazole', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Opdivo', 'nivolumab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg/ml', '40mg/4ml', '100mg/10ml', '240mg/24ml'], false, true),
  ('Oracea', 'doxycycline', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['40mg'], false, true),
  ('Orap', 'pimozide', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg'], false, true),
  ('Orencia', 'abatacept', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['125mg/ml', '250mg'], false, true),
  ('Orfadin', 'nitisinone', 'Metabolic Agent', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Suspension'], ARRAY['2mg', '5mg', '10mg', '4mg/ml'], false, true),
  ('Orkambi', 'lumacaftor/ivacaftor', 'Cystic Fibrosis Agent', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Granules'], ARRAY['100/125mg', '200/125mg'], true, true),
  ('Orphenadrine', 'orphenadrine', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['100mg', '30mg/ml'], false, true),
  ('Ortho Tri-Cyclen', 'norgestimate/ethinyl estradiol', 'Contraceptive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['Triphasic'], true, true),
  ('Oseltamivir', 'oseltamivir', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Suspension'], ARRAY['30mg', '45mg', '75mg', '6mg/ml'], false, true),
  ('Oseni', 'alogliptin/pioglitazone', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['12.5/15mg', '12.5/30mg', '12.5/45mg', '25/15mg', '25/30mg', '25/45mg'], true, true),
  ('Otezla', 'apremilast', 'PDE4 Inhibitor', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '30mg'], false, true),
  ('Otovel', 'ciprofloxacin/fluocinolone', 'Antibiotic/Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Otic'], ARRAY['Solution'], ARRAY['0.3%/0.025%'], true, true),
  ('Oxacillin', 'oxacillin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g', '2g'], false, true),
  ('Oxaliplatin', 'oxaliplatin', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg/ml'], false, true),
  ('Oxandrolone', 'oxandrolone', 'Anabolic Steroid', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '10mg'], false, true),
  ('Oxazepam', 'oxazepam', 'Benzodiazepine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '15mg', '30mg'], false, true),
  ('Oxcarbazepine', 'oxcarbazepine', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['150mg', '300mg', '600mg', '300mg/5ml'], false, true),
  ('Oxybutynin', 'oxybutynin', 'Urinary Antispasmodic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical', 'Transdermal'], ARRAY['Tablet', 'Syrup', 'Gel', 'Patch'], ARRAY['5mg', '10mg', '15mg', '5mg/5ml', '10%', '3.9mg/day'], false, true),
  ('Oxycodone', 'oxycodone', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Solution'], ARRAY['5mg', '10mg', '15mg', '20mg', '30mg', '5mg/5ml', '20mg/ml'], false, true),
  ('Oxycodone/Acetaminophen', 'oxycodone/acetaminophen', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Solution'], ARRAY['2.5/325mg', '5/325mg', '7.5/325mg', '10/325mg', '5/325mg/5ml'], true, true),
  ('OxyContin', 'oxycodone extended-release', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '15mg', '20mg', '30mg', '40mg', '60mg', '80mg'], false, true),
  ('Oxymetazoline', 'oxymetazoline', 'Decongestant', 'Tier 1', 'Preferred', ARRAY['Nasal', 'Ophthalmic'], ARRAY['Spray', 'Solution'], ARRAY['0.05%', '0.025%'], false, true),
  ('Ozempic', 'semaglutide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg'], false, true),
  ('Paclitaxel', 'paclitaxel', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['6mg/ml'], false, true),
  ('Paliperidone', 'paliperidone', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['1.5mg', '3mg', '6mg', '9mg', '39mg', '78mg', '117mg', '156mg', '234mg'], false, true),
  ('Palonosetron', 'palonosetron', 'Antiemetic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['0.5mg', '0.25mg/5ml'], false, true),
  ('Pamelor', 'nortriptyline', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['10mg', '25mg', '50mg', '75mg', '10mg/5ml'], false, true),
  ('Pamidronate', 'pamidronate', 'Bisphosphonate', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['3mg/ml', '6mg/ml', '9mg/ml'], false, true),
  ('Pancrelipase', 'pancrelipase', 'Digestive Enzyme', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['3000 units', '6000 units', '12000 units', '24000 units', '36000 units'], false, true),
  ('Pantoprazole', 'pantoprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Packet', 'Injection'], ARRAY['20mg', '40mg'], false, true),
  ('Paricalcitol', 'paricalcitol', 'Vitamin D Analog', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['1mcg', '2mcg', '4mcg', '2mcg/ml', '5mcg/ml'], false, true),
  ('Parlodel', 'bromocriptine', 'Dopamine Agonist', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['2.5mg', '5mg'], false, true),
  ('Parnate', 'tranylcypromine', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg'], false, true),
  ('Paroxetine', 'paroxetine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['10mg', '20mg', '30mg', '40mg', '10mg/5ml'], false, true),
  ('Patanol', 'olopatadine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.1%'], false, true),
  ('Pataday', 'olopatadine', 'Antihistamine', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.2%', '0.7%'], false, true),
  ('Paxil', 'paroxetine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['10mg', '20mg', '30mg', '40mg', '10mg/5ml'], false, true),
  ('Paxil CR', 'paroxetine controlled-release', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['12.5mg', '25mg', '37.5mg'], false, true),
  ('Pazopanib', 'pazopanib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Pediarix', 'DTaP/HepB/IPV vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], true, true),
  ('Penicillin G', 'penicillin G', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1 million units', '5 million units', '20 million units'], false, true),
  ('Penicillin VK', 'penicillin V potassium', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['250mg', '500mg', '125mg/5ml', '250mg/5ml'], false, true),
  ('Pentasa', 'mesalamine', 'Aminosalicylate', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['250mg', '500mg'], false, true),
  ('Pentazocine', 'pentazocine', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['50mg', '30mg/ml'], false, true),
  ('Pentoxifylline', 'pentoxifylline', 'Hemorheologic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['400mg'], false, true),
  ('Pepcid', 'famotidine', 'H2 Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['10mg', '20mg', '40mg', '40mg/5ml', '10mg/ml'], false, true),
  ('Percocet', 'oxycodone/acetaminophen', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5/325mg', '5/325mg', '7.5/325mg', '10/325mg'], true, true),
  ('Perforomist', 'formoterol', 'LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Nebulizer Solution'], ARRAY['20mcg/2ml'], false, true),
  ('Perindopril', 'perindopril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg', '4mg', '8mg'], false, true),
  ('Permethrin', 'permethrin', 'Antiparasitic', 'Tier 1', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Lotion'], ARRAY['1%', '5%'], false, true),
  ('Perphenazine', 'perphenazine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg', '4mg', '8mg', '16mg'], false, true),
  ('Phenazopyridine', 'phenazopyridine', 'Urinary Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Phenobarbital', 'phenobarbital', 'Anticonvulsant/Sedative', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Elixir', 'Injection'], ARRAY['15mg', '16.2mg', '30mg', '32.4mg', '60mg', '64.8mg', '97.2mg', '100mg', '20mg/5ml', '65mg/ml', '130mg/ml'], false, true),
  ('Phenergan', 'promethazine', 'Antihistamine/Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal', 'Injection'], ARRAY['Tablet', 'Syrup', 'Suppository', 'Injection'], ARRAY['12.5mg', '25mg', '50mg', '6.25mg/5ml', '25mg/ml', '50mg/ml'], false, true),
  ('Phenobarbital', 'phenobarbital', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Elixir', 'Injection'], ARRAY['15mg', '30mg', '60mg', '100mg', '20mg/5ml'], false, true),
  ('Phentermine', 'phentermine', 'Weight Loss Agent', 'Tier 2', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['15mg', '30mg', '37.5mg'], false, true),
  ('Phenylephrine', 'phenylephrine', 'Decongestant/Vasopressor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Nasal', 'Ophthalmic', 'Injection'], ARRAY['Tablet', 'Liquid', 'Spray', 'Solution', 'Injection'], ARRAY['10mg', '0.25%', '0.5%', '1%', '2.5%', '10%', '10mg/ml'], false, true),
  ('Phenytoin', 'phenytoin', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Tablet', 'Suspension', 'Injection'], ARRAY['30mg', '100mg', '200mg', '300mg', '50mg', '125mg/5ml', '50mg/ml'], false, true),
  ('Pimecrolimus', 'pimecrolimus', 'Immunomodulator', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream'], ARRAY['1%'], false, true),
  ('Pimozide', 'pimozide', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg'], false, true),
  ('Pindolol', 'pindolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Pioglitazone', 'pioglitazone', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg', '45mg'], false, true),
  ('Piperacillin/Tazobactam', 'piperacillin/tazobactam', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2.25g', '3.375g', '4.5g'], true, true),
  ('Piroxicam', 'piroxicam', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg'], false, true),
  ('Plaquenil', 'hydroxychloroquine', 'Antimalarial/DMARD', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Plavix', 'clopidogrel', 'Antiplatelet', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['75mg', '300mg'], false, true),
  ('Plendil', 'felodipine', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Pletal', 'cilostazol', 'Antiplatelet', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg'], false, true),
  ('Pneumovax', 'pneumococcal vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], false, true),
  ('Podofilox', 'podofilox', 'Antiviral', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Solution', 'Gel'], ARRAY['0.5%'], false, true),
  ('Polyethylene Glycol', 'polyethylene glycol 3350', 'Laxative', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Powder'], ARRAY['17g', '255g', '527g'], false, true),
  ('Polymyxin B', 'polymyxin B', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection', 'Ophthalmic'], ARRAY['Injection', 'Solution'], ARRAY['500000 units'], false, true),
  ('Ponatinib', 'ponatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg', '45mg'], false, true),
  ('Posaconazole', 'posaconazole', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['100mg', '40mg/ml', '18mg/ml'], false, true),
  ('Potassium Chloride', 'potassium chloride', 'Electrolyte', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Liquid', 'Powder'], ARRAY['8mEq', '10mEq', '20mEq', '25mEq', '20mEq/15ml', '40mEq/15ml'], false, true),
  ('Pradaxa', 'dabigatran', 'Anticoagulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['75mg', '110mg', '150mg'], false, true),
  ('Pramipexole', 'pramipexole', 'Antiparkinson', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.125mg', '0.25mg', '0.5mg', '0.75mg', '1mg', '1.5mg'], false, true),
  ('Pramlintide', 'pramlintide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.6mg/ml', '1mg/ml'], false, true),
  ('Prasugrel', 'prasugrel', 'Antiplatelet', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Pravastatin', 'pravastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg', '80mg'], false, true),
  ('Prazosin', 'prazosin', 'Alpha Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1mg', '2mg', '5mg'], false, true),
  ('Pred Forte', 'prednisolone acetate', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Suspension'], ARRAY['1%'], false, true),
  ('Prednisolone', 'prednisolone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Oral', 'Ophthalmic'], ARRAY['Tablet', 'Solution', 'Syrup', 'Suspension'], ARRAY['5mg', '15mg', '5mg/5ml', '15mg/5ml', '0.12%', '1%'], false, true),
  ('Prednisone', 'prednisone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['1mg', '2.5mg', '5mg', '10mg', '20mg', '50mg', '1mg/ml', '5mg/5ml'], false, true),
  ('Pregabalin', 'pregabalin', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['25mg', '50mg', '75mg', '100mg', '150mg', '200mg', '225mg', '300mg', '20mg/ml'], false, true),
  ('Premarin', 'conjugated estrogens', 'Hormone', 'Tier 1', 'Preferred', ARRAY['Oral', 'Vaginal', 'Injection'], ARRAY['Tablet', 'Cream', 'Injection'], ARRAY['0.3mg', '0.45mg', '0.625mg', '0.9mg', '1.25mg', '0.625mg/g', '25mg'], false, true),
  ('Prempro', 'conjugated estrogens/medroxyprogesterone', 'Hormone', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.3/1.5mg', '0.45/1.5mg', '0.625/2.5mg', '0.625/5mg'], true, true),
  ('Prevacid', 'lansoprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'ODT'], ARRAY['15mg', '30mg'], false, true),
  ('Prevnar', 'pneumococcal vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], false, true),
  ('Prezista', 'darunavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['75mg', '150mg', '600mg', '800mg', '100mg/ml'], false, true),
  ('Prilosec', 'omeprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Primaquine', 'primaquine', 'Antimalarial', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['26.3mg'], false, true),
  ('Primidone', 'primidone', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['50mg', '250mg', '250mg/5ml'], false, true),
  ('Prinivil', 'lisinopril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg', '20mg', '40mg'], false, true),
  ('Pristiq', 'desvenlafaxine', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Proair', 'albuterol', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['90mcg'], false, true),
  ('Probenecid', 'probenecid', 'Uricosuric', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg'], false, true),
  ('Procainamide', 'procainamide', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Tablet', 'Injection'], ARRAY['250mg', '375mg', '500mg', '100mg/ml', '500mg/ml'], false, true),
  ('Prochlorperazine', 'prochlorperazine', 'Antiemetic/Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal', 'Injection'], ARRAY['Tablet', 'Suppository', 'Injection'], ARRAY['5mg', '10mg', '25mg', '5mg/ml'], false, true),
  ('Procrit', 'epoetin alfa', 'Hematopoietic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2000 units', '3000 units', '4000 units', '10000 units', '40000 units'], false, true),
  ('Progesterone', 'progesterone', 'Hormone', 'Tier 1', 'Preferred', ARRAY['Oral', 'Vaginal', 'Injection'], ARRAY['Capsule', 'Gel', 'Insert', 'Injection'], ARRAY['100mg', '200mg', '4%', '8%', '100mg', '50mg/ml'], false, true),
  ('Prograf', 'tacrolimus', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['0.5mg', '1mg', '5mg', '5mg/ml'], false, true),
  ('Prolia', 'denosumab', 'Bone Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['60mg/ml'], false, true),
  ('Promethazine', 'promethazine', 'Antihistamine/Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal', 'Injection'], ARRAY['Tablet', 'Syrup', 'Suppository', 'Injection'], ARRAY['12.5mg', '25mg', '50mg', '6.25mg/5ml', '25mg/ml', '50mg/ml'], false, true),
  ('Propafenone', 'propafenone', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['150mg', '225mg', '300mg', '225mg', '325mg', '425mg'], false, true),
  ('Propranolol', 'propranolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Capsule', 'Injection'], ARRAY['10mg', '20mg', '40mg', '60mg', '80mg', '4mg/ml', '8mg/ml', '60mg', '80mg', '120mg', '160mg', '1mg/ml'], false, true),
  ('Propylthiouracil', 'propylthiouracil', 'Antithyroid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg'], false, true),
  ('ProQuad', 'MMRV vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], true, true),
  ('Proscar', 'finasteride', 'Antiandrogen', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg'], false, true),
  ('Protonix', 'pantoprazole', 'Proton Pump Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Packet', 'Injection'], ARRAY['20mg', '40mg'], false, true),
  ('Protopic', 'tacrolimus topical', 'Immunomodulator', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Ointment'], ARRAY['0.03%', '0.1%'], false, true),
  ('Proventil', 'albuterol', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['90mcg'], false, true),
  ('Provera', 'medroxyprogesterone', 'Progestin', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Provigil', 'modafinil', 'Wakefulness Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Prozac', 'fluoxetine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Solution'], ARRAY['10mg', '20mg', '40mg', '60mg', '90mg', '20mg/5ml'], false, true),
  ('Pulmicort', 'budesonide inhalation', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler', 'Nebulizer Suspension'], ARRAY['90mcg', '180mcg', '0.25mg/2ml', '0.5mg/2ml', '1mg/2ml'], false, true),
  ('Pyrazinamide', 'pyrazinamide', 'Antitubercular', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg'], false, true),
  ('Pyridostigmine', 'pyridostigmine', 'Cholinesterase Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Syrup'], ARRAY['60mg', '180mg', '60mg/5ml'], false, true),
  ('Pyridoxine', 'pyridoxine', 'Vitamin B6', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['25mg', '50mg', '100mg', '100mg/ml'], false, true)
ON CONFLICT (medication_name) DO NOTHING;
