/*
  # Seed Drug Formulary - Batch 4 (G-H Medications)
  
  1. Data Seeding
    - Medications starting with G and H (~150 entries)
    - Includes combination medications with proper flagging
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Gabapentin', 'gabapentin', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Solution'], ARRAY['100mg', '300mg', '400mg', '600mg', '800mg', '250mg/5ml'], false, true),
  ('Gabitril', 'tiagabine', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg', '4mg', '12mg', '16mg'], false, true),
  ('Galantamine', 'galantamine', 'Cholinesterase Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Solution'], ARRAY['4mg', '8mg', '12mg', '8mg', '16mg', '24mg'], false, true),
  ('Ganciclovir', 'ganciclovir', 'Antiviral', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection', 'Ophthalmic'], ARRAY['Capsule', 'Injection', 'Gel'], ARRAY['250mg', '500mg', '0.15%'], false, true),
  ('Gardasil', 'human papillomavirus vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], false, true),
  ('Gastrocrom', 'cromolyn sodium', 'Mast Cell Stabilizer', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Solution'], ARRAY['100mg/5ml'], false, true),
  ('Gattex', 'teduglutide', 'GLP-2 Analog', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg'], false, true),
  ('Gavilyte', 'PEG electrolyte solution', 'Laxative', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Powder'], ARRAY['4L'], false, true),
  ('Gazyva', 'obinutuzumab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1000mg/40ml'], false, true),
  ('Gefitinib', 'gefitinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg'], false, true),
  ('Gemcitabine', 'gemcitabine', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['200mg', '1g', '2g'], false, true),
  ('Gemfibrozil', 'gemfibrozil', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['600mg'], false, true),
  ('Gemifloxacin', 'gemifloxacin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['320mg'], false, true),
  ('Gemzar', 'gemcitabine', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['200mg', '1g', '2g'], false, true),
  ('Gengraf', 'cyclosporine modified', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['25mg', '100mg', '100mg/ml'], false, true),
  ('Genotropin', 'somatropin', 'Growth Hormone', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg', '12mg'], false, true),
  ('Gentamicin', 'gentamicin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Injection', 'Topical', 'Ophthalmic'], ARRAY['Injection', 'Cream', 'Ointment', 'Solution'], ARRAY['40mg/ml', '80mg/2ml', '0.1%', '0.3%'], false, true),
  ('Geodon', 'ziprasidone', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['20mg', '40mg', '60mg', '80mg', '20mg/ml'], false, true),
  ('Gianvi', 'drospirenone/ethinyl estradiol', 'Contraceptive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['3/0.02mg'], true, true),
  ('Gilenya', 'fingolimod', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['0.5mg'], false, true),
  ('Gilotrif', 'afatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '30mg', '40mg'], false, true),
  ('Glatiramer', 'glatiramer acetate', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['20mg/ml', '40mg/ml'], false, true),
  ('Gleevec', 'imatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '400mg'], false, true),
  ('Glimepiride', 'glimepiride', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '4mg'], false, true),
  ('Glipizide', 'glipizide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Glipizide XL', 'glipizide extended-release', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Glucagen', 'glucagon', 'Antihypoglycemic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg'], false, true),
  ('Glucagon', 'glucagon', 'Antihypoglycemic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg'], false, true),
  ('Glucophage', 'metformin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '850mg', '1000mg'], false, true),
  ('Glucophage XR', 'metformin extended-release', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '750mg', '1000mg'], false, true),
  ('Glucotrol', 'glipizide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Glucotrol XL', 'glipizide extended-release', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg'], false, true),
  ('Glucovance', 'glyburide/metformin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.25/250mg', '2.5/500mg', '5/500mg'], true, true),
  ('Glumetza', 'metformin extended-release', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '1000mg'], false, true),
  ('Glyburide', 'glyburide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.25mg', '2.5mg', '5mg'], false, true),
  ('Glyburide/Metformin', 'glyburide/metformin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.25/250mg', '2.5/500mg', '5/500mg'], true, true),
  ('Glycopyrrolate', 'glycopyrrolate', 'Anticholinergic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection', 'Solution'], ARRAY['1mg', '2mg', '0.2mg/ml'], false, true),
  ('Glynase', 'glyburide micronized', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.5mg', '3mg', '6mg'], false, true),
  ('Glyset', 'miglitol', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('GoLYTELY', 'PEG electrolyte solution', 'Laxative', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Powder'], ARRAY['4L'], false, true),
  ('Gonal-f', 'follitropin alfa', 'Fertility Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['75 units', '450 units', '900 units'], false, true),
  ('Granisetron', 'granisetron', 'Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Transdermal'], ARRAY['Tablet', 'Solution', 'Injection', 'Patch'], ARRAY['1mg', '2mg/10ml', '1mg/ml', '3.1mg/24hr'], false, true),
  ('Grastek', 'timothy grass pollen extract', 'Allergen Immunotherapy', 'Tier 2', 'Preferred', ARRAY['Sublingual'], ARRAY['Tablet'], ARRAY['2800 BAU'], false, true),
  ('Gris-PEG', 'griseofulvin ultramicrosize', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['125mg', '250mg'], false, true),
  ('Griseofulvin', 'griseofulvin', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['500mg', '125mg/5ml'], false, true),
  ('Guaifenesin', 'guaifenesin', 'Expectorant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Liquid', 'Capsule'], ARRAY['200mg', '400mg', '600mg', '1200mg', '100mg/5ml'], false, true),
  ('Guanfacine', 'guanfacine', 'Antihypertensive/ADHD', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg'], false, true),
  ('Guanfacine ER', 'guanfacine extended-release', 'ADHD Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '3mg', '4mg'], false, true),
  ('Gynazole-1', 'butoconazole', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Vaginal'], ARRAY['Cream'], ARRAY['2%'], false, true),
  ('Gyne-Lotrimin', 'clotrimazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Vaginal'], ARRAY['Cream', 'Insert'], ARRAY['1%', '2%', '100mg', '200mg'], false, true),
  ('Haegarda', 'C1 esterase inhibitor', 'Hereditary Angioedema', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2000 units', '3000 units'], false, true),
  ('Halaven', 'eribulin', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg/2ml'], false, true),
  ('Halcion', 'triazolam', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.125mg', '0.25mg'], false, true),
  ('Haldol', 'haloperidol', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['0.5mg', '1mg', '2mg', '5mg', '10mg', '20mg', '2mg/ml', '5mg/ml', '50mg/ml', '100mg/ml'], false, true),
  ('Haloperidol', 'haloperidol', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['0.5mg', '1mg', '2mg', '5mg', '10mg', '20mg'], false, true),
  ('Haloperidol Decanoate', 'haloperidol decanoate', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['50mg/ml', '100mg/ml'], false, true),
  ('Harvoni', 'ledipasvir/sofosbuvir', 'Antiviral', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['90/400mg'], true, true),
  ('Havrix', 'hepatitis A vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['720 units/0.5ml', '1440 units/ml'], false, true),
  ('Hectorol', 'doxercalciferol', 'Vitamin D Analog', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['0.5mcg', '1mcg', '2.5mcg', '2mcg/ml'], false, true),
  ('Helidac', 'bismuth/metronidazole/tetracycline', 'H. pylori Therapy', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Kit'], ARRAY['262.4mg/250mg/500mg'], true, true),
  ('Hemlibra', 'emicizumab', 'Hemophilia Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['30mg/ml', '60mg/0.4ml', '105mg/0.7ml', '150mg/ml'], false, true),
  ('Heparin', 'heparin sodium', 'Anticoagulant', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1000 units/ml', '5000 units/ml', '10000 units/ml', '20000 units/ml'], false, true),
  ('Hepatitis A Vaccine', 'hepatitis A vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['720 units', '1440 units'], false, true),
  ('Hepatitis B Vaccine', 'hepatitis B vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mcg', '20mcg', '40mcg'], false, true),
  ('Herceptin', 'trastuzumab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['150mg', '440mg'], false, true),
  ('Hizentra', 'immune globulin subcutaneous', 'Immunoglobulin', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g', '2g', '4g', '10g'], false, true),
  ('Humalog', 'insulin lispro', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml', '200 units/ml'], false, true),
  ('Humalog Mix 50/50', 'insulin lispro protamine/insulin lispro', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], true, true),
  ('Humalog Mix 75/25', 'insulin lispro protamine/insulin lispro', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], true, true),
  ('Humira', 'adalimumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg/0.1ml', '20mg/0.2ml', '40mg/0.4ml', '40mg/0.8ml', '80mg/0.8ml'], false, true),
  ('Humulin 70/30', 'NPH/regular insulin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], true, true),
  ('Humulin N', 'NPH insulin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Humulin R', 'regular insulin', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml', '500 units/ml'], false, true),
  ('Hyalgan', 'hyaluronate sodium', 'Viscosupplement', 'Tier 2', 'Preferred', ARRAY['Intra-articular'], ARRAY['Injection'], ARRAY['20mg/2ml'], false, true),
  ('Hycamtin', 'topotecan', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['0.25mg', '1mg', '4mg'], false, true),
  ('Hycodan', 'hydrocodone/homatropine', 'Antitussive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Syrup'], ARRAY['5/1.5mg'], true, true),
  ('Hydralazine', 'hydralazine', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['10mg', '25mg', '50mg', '100mg', '20mg/ml'], false, true),
  ('Hydrochlorothiazide', 'hydrochlorothiazide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['12.5mg', '25mg', '50mg'], false, true),
  ('Hydrocodone/Acetaminophen', 'hydrocodone/acetaminophen', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5/325mg', '7.5/325mg', '10/325mg', '7.5/325mg/15ml'], true, true),
  ('Hydrocodone/Ibuprofen', 'hydrocodone/ibuprofen', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['7.5/200mg'], true, true),
  ('Hydrocortisone', 'hydrocortisone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical', 'Injection', 'Rectal'], ARRAY['Tablet', 'Cream', 'Ointment', 'Lotion', 'Injection', 'Enema', 'Suppository'], ARRAY['5mg', '10mg', '20mg', '0.5%', '1%', '2.5%', '100mg', '250mg', '500mg', '1000mg'], false, true),
  ('Hydromorphone', 'hydromorphone', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Rectal'], ARRAY['Tablet', 'Liquid', 'Injection', 'Suppository'], ARRAY['2mg', '4mg', '8mg', '1mg/ml', '2mg/ml', '4mg/ml', '10mg/ml', '3mg'], false, true),
  ('Hydroxychloroquine', 'hydroxychloroquine', 'Antimalarial/DMARD', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Hydroxyurea', 'hydroxyurea', 'Antineoplastic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['500mg'], false, true),
  ('Hydroxyzine', 'hydroxyzine', 'Antihistamine/Anxiolytic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Capsule', 'Syrup', 'Injection'], ARRAY['10mg', '25mg', '50mg', '10mg/5ml', '25mg/ml', '50mg/ml'], false, true),
  ('Hyoscyamine', 'hyoscyamine', 'Anticholinergic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Sublingual', 'Injection'], ARRAY['Tablet', 'Capsule', 'Drops', 'Injection'], ARRAY['0.125mg', '0.375mg', '0.125mg/ml', '0.5mg/ml'], false, true),
  ('Hytrin', 'terazosin', 'Alpha Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1mg', '2mg', '5mg', '10mg'], false, true),
  ('Hyzaar', 'losartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/12.5mg', '100/12.5mg', '100/25mg'], true, true)
ON CONFLICT (medication_name) DO NOTHING;
