/*
  # Seed Drug Formulary with Medications - Batch 1 (A-B)

  ## Overview
  This migration seeds the drug_formulary table with FDA-listed medications.
  Batch 1 covers medications starting with A and B.

  ## Data Processing
  - Combination medications are flagged with is_combination = true
  - Component drugs are extracted and stored in component_medications array
  - Default tier is set to 'Tier 2' and formulary_status to 'Preferred'
  
  ## Important Notes
  - Uses ON CONFLICT to skip duplicates
  - All medications are set as active by default
*/

-- Helper function to parse combination medications
CREATE OR REPLACE FUNCTION parse_combination_components(med_name text)
RETURNS text[]
LANGUAGE plpgsql
AS $$
DECLARE
  components text[];
  cleaned_name text;
BEGIN
  cleaned_name := regexp_replace(med_name, '^\s+|\s+$', '', 'g');
  
  IF med_name ~* '\|\|' THEN
    SELECT array_agg(trim(part))
    INTO components
    FROM unnest(regexp_split_to_array(med_name, '\s*\|\|\s*')) AS part
    WHERE trim(part) != '';
  ELSIF med_name ~* ';\s*' AND med_name !~* 'IN PLASTIC CONTAINER' THEN
    SELECT array_agg(trim(part))
    INTO components
    FROM unnest(regexp_split_to_array(med_name, '\s*;\s*')) AS part
    WHERE trim(part) != '';
  ELSIF med_name ~* '\sAND\s' AND med_name !~* 'SINUS|COLD|FLU|ALLERGY|CONGESTION|HEADACHE|RELIEF' THEN
    SELECT array_agg(trim(part))
    INTO components
    FROM unnest(regexp_split_to_array(med_name, '\s+AND\s+')) AS part
    WHERE trim(part) != '';
  ELSE
    components := '{}';
  END IF;
  
  RETURN COALESCE(components, '{}');
END;
$$;

-- Insert medications A-B
INSERT INTO drug_formulary (medication_name, generic_name, tier, formulary_status, is_combination, component_medications, is_active)
VALUES
('A-HYDROCORT', 'Hydrocortisone', 'Tier 2', 'Preferred', false, '{}', true),
('A-METHAPRED', 'Methylprednisolone', 'Tier 2', 'Preferred', false, '{}', true),
('A-POXIDE', 'Chlordiazepoxide', 'Tier 2', 'Preferred', false, '{}', true),
('A.P.L.', 'Chorionic Gonadotropin', 'Tier 3', 'Preferred', false, '{}', true),
('A/T/S', 'Erythromycin Topical', 'Tier 2', 'Preferred', false, '{}', true),
('ABACAVIR SULFATE', 'Abacavir', 'Tier 2', 'Preferred', false, '{}', true),
('ABACAVIR AND LAMIVUDINE', 'Abacavir/Lamivudine', 'Tier 2', 'Preferred', true, ARRAY['ABACAVIR', 'LAMIVUDINE'], true),
('ABACAVIR SULFATE AND LAMIVUDINE', 'Abacavir/Lamivudine', 'Tier 2', 'Preferred', true, ARRAY['ABACAVIR SULFATE', 'LAMIVUDINE'], true),
('ABACAVIR, DOLUTEGRAVIR AND LAMIVUDINE', 'Abacavir/Dolutegravir/Lamivudine', 'Tier 2', 'Preferred', true, ARRAY['ABACAVIR', 'DOLUTEGRAVIR', 'LAMIVUDINE'], true),
('ABELCET', 'Amphotericin B Lipid Complex', 'Tier 3', 'Preferred', false, '{}', true),
('ABEMACICLIB', 'Abemaciclib', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ABILIFY', 'Aripiprazole', 'Tier 2', 'Preferred', false, '{}', true),
('ABILIFY MAINTENA KIT', 'Aripiprazole Extended-Release', 'Tier 3', 'Preferred', false, '{}', true),
('ABIRATERONE ACETATE', 'Abiraterone', 'Tier 3', 'Preferred', false, '{}', true),
('ABRAXANE', 'Paclitaxel Protein-Bound', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ABSORICA', 'Isotretinoin', 'Tier 2', 'Preferred', false, '{}', true),
('ABSTRAL', 'Fentanyl Sublingual', 'Tier 3', 'Non-Preferred', false, '{}', true),
('ACAMPROSATE CALCIUM', 'Acamprosate', 'Tier 2', 'Preferred', false, '{}', true),
('ACARBOSE', 'Acarbose', 'Tier 1', 'Preferred', false, '{}', true),
('ACCOLATE', 'Zafirlukast', 'Tier 2', 'Preferred', false, '{}', true),
('ACCUPRIL', 'Quinapril', 'Tier 1', 'Preferred', false, '{}', true),
('ACCURETIC', 'Quinapril/Hydrochlorothiazide', 'Tier 2', 'Preferred', true, ARRAY['QUINAPRIL', 'HYDROCHLOROTHIAZIDE'], true),
('ACCUTANE', 'Isotretinoin', 'Tier 2', 'Preferred', false, '{}', true),
('ACEBUTOLOL HYDROCHLORIDE', 'Acebutolol', 'Tier 1', 'Preferred', false, '{}', true),
('ACEON', 'Perindopril', 'Tier 2', 'Preferred', false, '{}', true),
('ACETADOTE', 'Acetylcysteine IV', 'Tier 2', 'Preferred', false, '{}', true),
('ACETAMINOPHEN', 'Acetaminophen', 'Tier 1', 'Preferred', false, '{}', true),
('ACETAMINOPHEN AND CODEINE PHOSPHATE', 'Acetaminophen/Codeine', 'Tier 1', 'Preferred', true, ARRAY['ACETAMINOPHEN', 'CODEINE PHOSPHATE'], true),
('ACETAMINOPHEN AND HYDROCODONE BITARTRATE', 'Acetaminophen/Hydrocodone', 'Tier 1', 'Preferred', true, ARRAY['ACETAMINOPHEN', 'HYDROCODONE BITARTRATE'], true),
('ACETAMINOPHEN AND IBUPROFEN', 'Acetaminophen/Ibuprofen', 'Tier 1', 'Preferred', true, ARRAY['ACETAMINOPHEN', 'IBUPROFEN'], true),
('ACETAZOLAMIDE', 'Acetazolamide', 'Tier 1', 'Preferred', false, '{}', true),
('ACETIC ACID', 'Acetic Acid', 'Tier 1', 'Preferred', false, '{}', true),
('ACETYLCYSTEINE', 'Acetylcysteine', 'Tier 1', 'Preferred', false, '{}', true),
('ACIPHEX', 'Rabeprazole', 'Tier 2', 'Preferred', false, '{}', true),
('ACITRETIN', 'Acitretin', 'Tier 2', 'Preferred', false, '{}', true),
('ACLOVATE', 'Alclometasone', 'Tier 2', 'Preferred', false, '{}', true),
('ACTEMRA', 'Tocilizumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ACTIGALL', 'Ursodiol', 'Tier 2', 'Preferred', false, '{}', true),
('ACTIMMUNE', 'Interferon Gamma-1b', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ACTIQ', 'Fentanyl Citrate Lozenge', 'Tier 3', 'Non-Preferred', false, '{}', true),
('ACTIVASE', 'Alteplase', 'Tier 3', 'Preferred', false, '{}', true),
('ACTIVELLA', 'Estradiol/Norethindrone', 'Tier 2', 'Preferred', true, ARRAY['ESTRADIOL', 'NORETHINDRONE'], true),
('ACTONEL', 'Risedronate', 'Tier 2', 'Preferred', false, '{}', true),
('ACTOPLUS MET', 'Pioglitazone/Metformin', 'Tier 2', 'Preferred', true, ARRAY['PIOGLITAZONE', 'METFORMIN'], true),
('ACTOS', 'Pioglitazone', 'Tier 2', 'Preferred', false, '{}', true),
('ACULAR', 'Ketorolac Ophthalmic', 'Tier 2', 'Preferred', false, '{}', true),
('ACYCLOVIR', 'Acyclovir', 'Tier 1', 'Preferred', false, '{}', true),
('ACZONE', 'Dapsone Gel', 'Tier 2', 'Preferred', false, '{}', true),
('ADAKVEO', 'Crizanlizumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ADALAT', 'Nifedipine', 'Tier 2', 'Preferred', false, '{}', true),
('ADALAT CC', 'Nifedipine Extended-Release', 'Tier 2', 'Preferred', false, '{}', true),
('ADAPALENE', 'Adapalene', 'Tier 1', 'Preferred', false, '{}', true),
('ADAPALENE AND BENZOYL PEROXIDE', 'Adapalene/Benzoyl Peroxide', 'Tier 2', 'Preferred', true, ARRAY['ADAPALENE', 'BENZOYL PEROXIDE'], true),
('ADCIRCA', 'Tadalafil', 'Tier 3', 'Preferred', false, '{}', true),
('ADDERALL', 'Amphetamine/Dextroamphetamine', 'Tier 2', 'Preferred', false, '{}', true),
('ADDERALL XR', 'Amphetamine/Dextroamphetamine XR', 'Tier 2', 'Preferred', false, '{}', true),
('ADDYI', 'Flibanserin', 'Tier 3', 'Non-Preferred', false, '{}', true),
('ADEFOVIR DIPIVOXIL', 'Adefovir', 'Tier 2', 'Preferred', false, '{}', true),
('ADEMPAS', 'Riociguat', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ADENOSINE', 'Adenosine', 'Tier 2', 'Preferred', false, '{}', true),
('ADIPEX-P', 'Phentermine', 'Tier 2', 'Preferred', false, '{}', true),
('ADMELOG', 'Insulin Lispro', 'Tier 2', 'Preferred', false, '{}', true),
('ADRENALIN', 'Epinephrine', 'Tier 1', 'Preferred', false, '{}', true),
('ADVAIR DISKUS', 'Fluticasone/Salmeterol', 'Tier 2', 'Preferred', true, ARRAY['FLUTICASONE', 'SALMETEROL'], true),
('ADVAIR HFA', 'Fluticasone/Salmeterol HFA', 'Tier 2', 'Preferred', true, ARRAY['FLUTICASONE', 'SALMETEROL'], true),
('ADVIL', 'Ibuprofen', 'Tier 1', 'Preferred', false, '{}', true),
('AFINITOR', 'Everolimus', 'Tier 4', 'Non-Preferred', false, '{}', true),
('AFREZZA', 'Insulin Human Inhalation', 'Tier 3', 'Preferred', false, '{}', true),
('AGGRENOX', 'Aspirin/Dipyridamole', 'Tier 2', 'Preferred', true, ARRAY['ASPIRIN', 'DIPYRIDAMOLE'], true),
('AIMOVIG', 'Erenumab', 'Tier 3', 'Preferred', false, '{}', true),
('AJOVY', 'Fremanezumab', 'Tier 3', 'Preferred', false, '{}', true),
('ALBENDAZOLE', 'Albendazole', 'Tier 2', 'Preferred', false, '{}', true),
('ALBUTEROL', 'Albuterol', 'Tier 1', 'Preferred', false, '{}', true),
('ALBUTEROL SULFATE', 'Albuterol', 'Tier 1', 'Preferred', false, '{}', true),
('ALBUTEROL SULFATE AND IPRATROPIUM BROMIDE', 'Albuterol/Ipratropium', 'Tier 1', 'Preferred', true, ARRAY['ALBUTEROL SULFATE', 'IPRATROPIUM BROMIDE'], true),
('ALDACTAZIDE', 'Spironolactone/Hydrochlorothiazide', 'Tier 1', 'Preferred', true, ARRAY['SPIRONOLACTONE', 'HYDROCHLOROTHIAZIDE'], true),
('ALDACTONE', 'Spironolactone', 'Tier 1', 'Preferred', false, '{}', true),
('ALDARA', 'Imiquimod', 'Tier 2', 'Preferred', false, '{}', true),
('ALDURAZYME', 'Laronidase', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ALECENSA', 'Alectinib', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ALENDRONATE SODIUM', 'Alendronate', 'Tier 1', 'Preferred', false, '{}', true),
('ALEVE', 'Naproxen Sodium', 'Tier 1', 'Preferred', false, '{}', true),
('ALFUZOSIN HYDROCHLORIDE', 'Alfuzosin', 'Tier 1', 'Preferred', false, '{}', true),
('ALIMTA', 'Pemetrexed', 'Tier 4', 'Non-Preferred', false, '{}', true),
('ALINIA', 'Nitazoxanide', 'Tier 2', 'Preferred', false, '{}', true),
('ALISKIREN HEMIFUMARATE', 'Aliskiren', 'Tier 2', 'Preferred', false, '{}', true),
('ALLEGRA', 'Fexofenadine', 'Tier 1', 'Preferred', false, '{}', true),
('ALLI', 'Orlistat', 'Tier 2', 'Non-Preferred', false, '{}', true),
('ALLOPURINOL', 'Allopurinol', 'Tier 1', 'Preferred', false, '{}', true),
('ALMOTRIPTAN MALATE', 'Almotriptan', 'Tier 2', 'Preferred', false, '{}', true),
('ALOGLIPTIN', 'Alogliptin', 'Tier 2', 'Preferred', false, '{}', true),
('ALOGLIPTIN AND METFORMIN HYDROCHLORIDE', 'Alogliptin/Metformin', 'Tier 2', 'Preferred', true, ARRAY['ALOGLIPTIN', 'METFORMIN HYDROCHLORIDE'], true),
('ALOSETRON HYDROCHLORIDE', 'Alosetron', 'Tier 3', 'Non-Preferred', false, '{}', true),
('ALOXI', 'Palonosetron', 'Tier 2', 'Preferred', false, '{}', true),
('ALPHAGAN P', 'Brimonidine', 'Tier 2', 'Preferred', false, '{}', true),
('ALPRAZOLAM', 'Alprazolam', 'Tier 1', 'Preferred', false, '{}', true),
('ALPROSTADIL', 'Alprostadil', 'Tier 3', 'Preferred', false, '{}', true),
('ALTACE', 'Ramipril', 'Tier 1', 'Preferred', false, '{}', true),
('ALTOPREV', 'Lovastatin Extended-Release', 'Tier 2', 'Preferred', false, '{}', true),
('ALVESCO', 'Ciclesonide', 'Tier 2', 'Preferred', false, '{}', true),
('AMANTADINE', 'Amantadine', 'Tier 1', 'Preferred', false, '{}', true),
('AMANTADINE HYDROCHLORIDE', 'Amantadine', 'Tier 1', 'Preferred', false, '{}', true),
('AMARYL', 'Glimepiride', 'Tier 1', 'Preferred', false, '{}', true),
('AMBIEN', 'Zolpidem', 'Tier 1', 'Preferred', false, '{}', true),
('AMBIEN CR', 'Zolpidem Extended-Release', 'Tier 2', 'Preferred', false, '{}', true),
('AMBISOME', 'Amphotericin B Liposomal', 'Tier 3', 'Preferred', false, '{}', true),
('AMBRISENTAN', 'Ambrisentan', 'Tier 4', 'Non-Preferred', false, '{}', true),
('AMERGE', 'Naratriptan', 'Tier 2', 'Preferred', false, '{}', true),
('AMICAR', 'Aminocaproic Acid', 'Tier 2', 'Preferred', false, '{}', true),
('AMIKACIN SULFATE', 'Amikacin', 'Tier 2', 'Preferred', false, '{}', true),
('AMILORIDE HYDROCHLORIDE', 'Amiloride', 'Tier 1', 'Preferred', false, '{}', true),
('AMILORIDE HYDROCHLORIDE AND HYDROCHLOROTHIAZIDE', 'Amiloride/HCTZ', 'Tier 1', 'Preferred', true, ARRAY['AMILORIDE HYDROCHLORIDE', 'HYDROCHLOROTHIAZIDE'], true),
('AMINOPHYLLINE', 'Aminophylline', 'Tier 1', 'Preferred', false, '{}', true),
('AMIODARONE HYDROCHLORIDE', 'Amiodarone', 'Tier 1', 'Preferred', false, '{}', true),
('AMITIZA', 'Lubiprostone', 'Tier 3', 'Preferred', false, '{}', true),
('AMITRIPTYLINE HYDROCHLORIDE', 'Amitriptyline', 'Tier 1', 'Preferred', false, '{}', true),
('AMLODIPINE BESYLATE', 'Amlodipine', 'Tier 1', 'Preferred', false, '{}', true),
('AMLODIPINE BESYLATE AND ATORVASTATIN CALCIUM', 'Amlodipine/Atorvastatin', 'Tier 2', 'Preferred', true, ARRAY['AMLODIPINE BESYLATE', 'ATORVASTATIN CALCIUM'], true),
('AMLODIPINE BESYLATE AND BENAZEPRIL HYDROCHLORIDE', 'Amlodipine/Benazepril', 'Tier 1', 'Preferred', true, ARRAY['AMLODIPINE BESYLATE', 'BENAZEPRIL HYDROCHLORIDE'], true),
('AMLODIPINE BESYLATE AND VALSARTAN', 'Amlodipine/Valsartan', 'Tier 2', 'Preferred', true, ARRAY['AMLODIPINE BESYLATE', 'VALSARTAN'], true),
('AMMONIUM LACTATE', 'Ammonium Lactate', 'Tier 1', 'Preferred', false, '{}', true),
('AMOXAPINE', 'Amoxapine', 'Tier 1', 'Preferred', false, '{}', true),
('AMOXICILLIN', 'Amoxicillin', 'Tier 1', 'Preferred', false, '{}', true),
('AMOXICILLIN AND CLAVULANATE POTASSIUM', 'Amoxicillin/Clavulanate', 'Tier 1', 'Preferred', true, ARRAY['AMOXICILLIN', 'CLAVULANATE POTASSIUM'], true),
('AMOXIL', 'Amoxicillin', 'Tier 1', 'Preferred', false, '{}', true),
('AMPHETAMINE SULFATE', 'Amphetamine', 'Tier 2', 'Preferred', false, '{}', true),
('AMPHOTERICIN B', 'Amphotericin B', 'Tier 2', 'Preferred', false, '{}', true),
('AMPICILLIN SODIUM', 'Ampicillin', 'Tier 1', 'Preferred', false, '{}', true),
('AMPICILLIN AND SULBACTAM', 'Ampicillin/Sulbactam', 'Tier 2', 'Preferred', true, ARRAY['AMPICILLIN', 'SULBACTAM'], true),
('AMPYRA', 'Dalfampridine', 'Tier 3', 'Preferred', false, '{}', true),
('AMRIX', 'Cyclobenzaprine Extended-Release', 'Tier 2', 'Preferred', false, '{}', true),
('ANAFRANIL', 'Clomipramine', 'Tier 2', 'Preferred', false, '{}', true),
('ANAGRELIDE HYDROCHLORIDE', 'Anagrelide', 'Tier 2', 'Preferred', false, '{}', true),
('ANAPROX', 'Naproxen Sodium', 'Tier 1', 'Preferred', false, '{}', true),
('ANASTROZOLE', 'Anastrozole', 'Tier 1', 'Preferred', false, '{}', true),
('ANDROGEL', 'Testosterone Gel', 'Tier 2', 'Preferred', false, '{}', true),
('ANORO ELLIPTA', 'Umeclidinium/Vilanterol', 'Tier 2', 'Preferred', true, ARRAY['UMECLIDINIUM', 'VILANTEROL'], true),
('ANTABUSE', 'Disulfiram', 'Tier 2', 'Preferred', false, '{}', true),
('ANTIVERT', 'Meclizine', 'Tier 1', 'Preferred', false, '{}', true),
('ANZEMET', 'Dolasetron', 'Tier 2', 'Preferred', false, '{}', true),
('APALUTAMIDE', 'Apalutamide', 'Tier 4', 'Non-Preferred', false, '{}', true),
('APIDRA', 'Insulin Glulisine', 'Tier 2', 'Preferred', false, '{}', true),
('APIXABAN', 'Apixaban', 'Tier 2', 'Preferred', false, '{}', true),
('APLENZIN', 'Bupropion Hydrobromide', 'Tier 2', 'Preferred', false, '{}', true),
('APOKYN', 'Apomorphine', 'Tier 3', 'Preferred', false, '{}', true),
('APREMILAST', 'Apremilast', 'Tier 3', 'Preferred', false, '{}', true),
('APREPITANT', 'Aprepitant', 'Tier 2', 'Preferred', false, '{}', true),
('APRISO', 'Mesalamine', 'Tier 2', 'Preferred', false, '{}', true),
('APTIOM', 'Eslicarbazepine', 'Tier 2', 'Preferred', false, '{}', true),
('ARAVA', 'Leflunomide', 'Tier 2', 'Preferred', false, '{}', true),
('ARFORMOTEROL TARTRATE', 'Arformoterol', 'Tier 2', 'Preferred', false, '{}', true),
('ARICEPT', 'Donepezil', 'Tier 1', 'Preferred', false, '{}', true),
('ARIMIDEX', 'Anastrozole', 'Tier 1', 'Preferred', false, '{}', true),
('ARIPIPRAZOLE', 'Aripiprazole', 'Tier 1', 'Preferred', false, '{}', true),
('ARISTADA', 'Aripiprazole Lauroxil', 'Tier 3', 'Preferred', false, '{}', true),
('ARMOUR THYROID', 'Thyroid Desiccated', 'Tier 2', 'Preferred', false, '{}', true),
('ARMODAFINIL', 'Armodafinil', 'Tier 2', 'Preferred', false, '{}', true),
('ARNUITY ELLIPTA', 'Fluticasone Furoate', 'Tier 2', 'Preferred', false, '{}', true),
('AROMASIN', 'Exemestane', 'Tier 2', 'Preferred', false, '{}', true),
('ARTANE', 'Trihexyphenidyl', 'Tier 1', 'Preferred', false, '{}', true),
('ARTHROTEC', 'Diclofenac/Misoprostol', 'Tier 2', 'Preferred', true, ARRAY['DICLOFENAC', 'MISOPROSTOL'], true),
('ASACOL HD', 'Mesalamine', 'Tier 2', 'Preferred', false, '{}', true),
('ASMANEX', 'Mometasone Inhaler', 'Tier 2', 'Preferred', false, '{}', true),
('ASPIRIN AND DIPYRIDAMOLE', 'Aspirin/Dipyridamole', 'Tier 2', 'Preferred', true, ARRAY['ASPIRIN', 'DIPYRIDAMOLE'], true),
('ASTAGRAF XL', 'Tacrolimus Extended-Release', 'Tier 3', 'Preferred', false, '{}', true),
('ASTELIN', 'Azelastine Nasal', 'Tier 2', 'Preferred', false, '{}', true),
('ASTEPRO', 'Azelastine Nasal', 'Tier 2', 'Preferred', false, '{}', true),
('ATACAND', 'Candesartan', 'Tier 2', 'Preferred', false, '{}', true),
('ATACAND HCT', 'Candesartan/HCTZ', 'Tier 2', 'Preferred', true, ARRAY['CANDESARTAN', 'HYDROCHLOROTHIAZIDE'], true),
('ATARAX', 'Hydroxyzine', 'Tier 1', 'Preferred', false, '{}', true),
('ATAZANAVIR SULFATE', 'Atazanavir', 'Tier 2', 'Preferred', false, '{}', true),
('ATENOLOL', 'Atenolol', 'Tier 1', 'Preferred', false, '{}', true),
('ATENOLOL AND CHLORTHALIDONE', 'Atenolol/Chlorthalidone', 'Tier 1', 'Preferred', true, ARRAY['ATENOLOL', 'CHLORTHALIDONE'], true),
('ATIVAN', 'Lorazepam', 'Tier 1', 'Preferred', false, '{}', true),
('ATOMOXETINE HYDROCHLORIDE', 'Atomoxetine', 'Tier 2', 'Preferred', false, '{}', true),
('ATORVASTATIN CALCIUM', 'Atorvastatin', 'Tier 1', 'Preferred', false, '{}', true),
('ATOVAQUONE', 'Atovaquone', 'Tier 2', 'Preferred', false, '{}', true),
('ATOVAQUONE AND PROGUANIL HYDROCHLORIDE', 'Atovaquone/Proguanil', 'Tier 2', 'Preferred', true, ARRAY['ATOVAQUONE', 'PROGUANIL HYDROCHLORIDE'], true),
('ATRIPLA', 'Efavirenz/Emtricitabine/Tenofovir', 'Tier 2', 'Preferred', true, ARRAY['EFAVIRENZ', 'EMTRICITABINE', 'TENOFOVIR'], true),
('ATROPINE SULFATE', 'Atropine', 'Tier 1', 'Preferred', false, '{}', true),
('ATROVENT', 'Ipratropium Bromide', 'Tier 1', 'Preferred', false, '{}', true),
('ATROVENT HFA', 'Ipratropium HFA', 'Tier 1', 'Preferred', false, '{}', true),
('AUBAGIO', 'Teriflunomide', 'Tier 3', 'Preferred', false, '{}', true),
('AUGMENTIN', 'Amoxicillin/Clavulanate', 'Tier 1', 'Preferred', true, ARRAY['AMOXICILLIN', 'CLAVULANATE'], true),
('AUGMENTIN XR', 'Amoxicillin/Clavulanate XR', 'Tier 2', 'Preferred', true, ARRAY['AMOXICILLIN', 'CLAVULANATE'], true),
('AURYXIA', 'Ferric Citrate', 'Tier 3', 'Preferred', false, '{}', true),
('AVANDIA', 'Rosiglitazone', 'Tier 2', 'Non-Preferred', false, '{}', true),
('AVAPRO', 'Irbesartan', 'Tier 2', 'Preferred', false, '{}', true),
('AVASTIN', 'Bevacizumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('AVELOX', 'Moxifloxacin', 'Tier 2', 'Preferred', false, '{}', true),
('AVODART', 'Dutasteride', 'Tier 2', 'Preferred', false, '{}', true),
('AVONEX', 'Interferon Beta-1a', 'Tier 3', 'Preferred', false, '{}', true),
('AXERT', 'Almotriptan', 'Tier 2', 'Preferred', false, '{}', true),
('AXID', 'Nizatidine', 'Tier 1', 'Preferred', false, '{}', true),
('AXITINIB', 'Axitinib', 'Tier 4', 'Non-Preferred', false, '{}', true),
('AYGESTIN', 'Norethindrone Acetate', 'Tier 1', 'Preferred', false, '{}', true),
('AZACITIDINE', 'Azacitidine', 'Tier 4', 'Non-Preferred', false, '{}', true),
('AZASAN', 'Azathioprine', 'Tier 1', 'Preferred', false, '{}', true),
('AZASITE', 'Azithromycin Ophthalmic', 'Tier 2', 'Preferred', false, '{}', true),
('AZATHIOPRINE', 'Azathioprine', 'Tier 1', 'Preferred', false, '{}', true),
('AZELAIC ACID', 'Azelaic Acid', 'Tier 2', 'Preferred', false, '{}', true),
('AZELASTINE HYDROCHLORIDE', 'Azelastine', 'Tier 1', 'Preferred', false, '{}', true),
('AZILECT', 'Rasagiline', 'Tier 2', 'Preferred', false, '{}', true),
('AZITHROMYCIN', 'Azithromycin', 'Tier 1', 'Preferred', false, '{}', true),
('AZOPT', 'Brinzolamide', 'Tier 2', 'Preferred', false, '{}', true),
('AZOR', 'Amlodipine/Olmesartan', 'Tier 2', 'Preferred', true, ARRAY['AMLODIPINE', 'OLMESARTAN'], true),
('AZTREONAM', 'Aztreonam', 'Tier 2', 'Preferred', false, '{}', true),
('AZULFIDINE', 'Sulfasalazine', 'Tier 1', 'Preferred', false, '{}', true),
('BACITRACIN', 'Bacitracin', 'Tier 1', 'Preferred', false, '{}', true),
('BACLOFEN', 'Baclofen', 'Tier 1', 'Preferred', false, '{}', true),
('BACTRIM', 'Sulfamethoxazole/Trimethoprim', 'Tier 1', 'Preferred', true, ARRAY['SULFAMETHOXAZOLE', 'TRIMETHOPRIM'], true),
('BACTRIM DS', 'Sulfamethoxazole/Trimethoprim DS', 'Tier 1', 'Preferred', true, ARRAY['SULFAMETHOXAZOLE', 'TRIMETHOPRIM'], true),
('BACTROBAN', 'Mupirocin', 'Tier 1', 'Preferred', false, '{}', true),
('BALSALAZIDE DISODIUM', 'Balsalazide', 'Tier 2', 'Preferred', false, '{}', true),
('BANZEL', 'Rufinamide', 'Tier 3', 'Preferred', false, '{}', true),
('BARACLUDE', 'Entecavir', 'Tier 2', 'Preferred', false, '{}', true),
('BASAGLAR', 'Insulin Glargine', 'Tier 2', 'Preferred', false, '{}', true),
('BECLOMETHASONE DIPROPIONATE', 'Beclomethasone', 'Tier 1', 'Preferred', false, '{}', true),
('BELBUCA', 'Buprenorphine Buccal', 'Tier 3', 'Non-Preferred', false, '{}', true),
('BELSOMRA', 'Suvorexant', 'Tier 3', 'Preferred', false, '{}', true),
('BENADRYL', 'Diphenhydramine', 'Tier 1', 'Preferred', false, '{}', true),
('BENAZEPRIL HYDROCHLORIDE', 'Benazepril', 'Tier 1', 'Preferred', false, '{}', true),
('BENAZEPRIL HYDROCHLORIDE AND HYDROCHLOROTHIAZIDE', 'Benazepril/HCTZ', 'Tier 1', 'Preferred', true, ARRAY['BENAZEPRIL HYDROCHLORIDE', 'HYDROCHLOROTHIAZIDE'], true),
('BENDAMUSTINE HYDROCHLORIDE', 'Bendamustine', 'Tier 4', 'Non-Preferred', false, '{}', true),
('BENICAR', 'Olmesartan', 'Tier 2', 'Preferred', false, '{}', true),
('BENICAR HCT', 'Olmesartan/HCTZ', 'Tier 2', 'Preferred', true, ARRAY['OLMESARTAN', 'HYDROCHLOROTHIAZIDE'], true),
('BENLYSTA', 'Belimumab', 'Tier 4', 'Non-Preferred', false, '{}', true),
('BENZONATATE', 'Benzonatate', 'Tier 1', 'Preferred', false, '{}', true),
('BENZOYL PEROXIDE', 'Benzoyl Peroxide', 'Tier 1', 'Preferred', false, '{}', true),
('BENZTROPINE MESYLATE', 'Benztropine', 'Tier 1', 'Preferred', false, '{}', true),
('BETAMETHASONE DIPROPIONATE', 'Betamethasone', 'Tier 1', 'Preferred', false, '{}', true),
('BETAMETHASONE VALERATE', 'Betamethasone', 'Tier 1', 'Preferred', false, '{}', true),
('BETAPACE', 'Sotalol', 'Tier 1', 'Preferred', false, '{}', true),
('BETASERON', 'Interferon Beta-1b', 'Tier 3', 'Preferred', false, '{}', true),
('BETAXOLOL HYDROCHLORIDE', 'Betaxolol', 'Tier 1', 'Preferred', false, '{}', true),
('BETHANECHOL CHLORIDE', 'Bethanechol', 'Tier 1', 'Preferred', false, '{}', true),
('BEVYXXA', 'Betrixaban', 'Tier 3', 'Non-Preferred', false, '{}', true),
('BIAXIN', 'Clarithromycin', 'Tier 1', 'Preferred', false, '{}', true),
('BIAXIN XL', 'Clarithromycin XL', 'Tier 2', 'Preferred', false, '{}', true),
('BICALUTAMIDE', 'Bicalutamide', 'Tier 1', 'Preferred', false, '{}', true),
('BIDIL', 'Isosorbide Dinitrate/Hydralazine', 'Tier 2', 'Preferred', true, ARRAY['ISOSORBIDE DINITRATE', 'HYDRALAZINE'], true),
('BIKTARVY', 'Bictegravir/Emtricitabine/Tenofovir', 'Tier 2', 'Preferred', true, ARRAY['BICTEGRAVIR', 'EMTRICITABINE', 'TENOFOVIR ALAFENAMIDE'], true),
('BIMATOPROST', 'Bimatoprost', 'Tier 2', 'Preferred', false, '{}', true),
('BISOPROLOL FUMARATE', 'Bisoprolol', 'Tier 1', 'Preferred', false, '{}', true),
('BISOPROLOL FUMARATE AND HYDROCHLOROTHIAZIDE', 'Bisoprolol/HCTZ', 'Tier 1', 'Preferred', true, ARRAY['BISOPROLOL FUMARATE', 'HYDROCHLOROTHIAZIDE'], true),
('BONIVA', 'Ibandronate', 'Tier 2', 'Preferred', false, '{}', true),
('BOSENTAN', 'Bosentan', 'Tier 4', 'Non-Preferred', false, '{}', true),
('BOSULIF', 'Bosutinib', 'Tier 4', 'Non-Preferred', false, '{}', true),
('BOTOX', 'OnabotulinumtoxinA', 'Tier 3', 'Preferred', false, '{}', true),
('BRAFTOVI', 'Encorafenib', 'Tier 4', 'Non-Preferred', false, '{}', true),
('BRAVELLE', 'Urofollitropin', 'Tier 3', 'Non-Preferred', false, '{}', true),
('BREO ELLIPTA', 'Fluticasone/Vilanterol', 'Tier 2', 'Preferred', true, ARRAY['FLUTICASONE', 'VILANTEROL'], true),
('BRILINTA', 'Ticagrelor', 'Tier 2', 'Preferred', false, '{}', true),
('BRIMONIDINE TARTRATE', 'Brimonidine', 'Tier 1', 'Preferred', false, '{}', true),
('BRIMONIDINE TARTRATE AND TIMOLOL MALEATE', 'Brimonidine/Timolol', 'Tier 2', 'Preferred', true, ARRAY['BRIMONIDINE TARTRATE', 'TIMOLOL MALEATE'], true),
('BRINZOLAMIDE', 'Brinzolamide', 'Tier 2', 'Preferred', false, '{}', true),
('BRIVARACETAM', 'Brivaracetam', 'Tier 2', 'Preferred', false, '{}', true),
('BROMOCRIPTINE MESYLATE', 'Bromocriptine', 'Tier 2', 'Preferred', false, '{}', true),
('BROMPHENIRAMINE MALEATE', 'Brompheniramine', 'Tier 1', 'Preferred', false, '{}', true),
('BUDESONIDE', 'Budesonide', 'Tier 1', 'Preferred', false, '{}', true),
('BUMETANIDE', 'Bumetanide', 'Tier 1', 'Preferred', false, '{}', true),
('BUMEX', 'Bumetanide', 'Tier 1', 'Preferred', false, '{}', true),
('BUPRENORPHINE', 'Buprenorphine', 'Tier 2', 'Preferred', false, '{}', true),
('BUPRENORPHINE HYDROCHLORIDE', 'Buprenorphine', 'Tier 2', 'Preferred', false, '{}', true),
('BUPRENORPHINE HYDROCHLORIDE AND NALOXONE HYDROCHLORIDE', 'Buprenorphine/Naloxone', 'Tier 2', 'Preferred', true, ARRAY['BUPRENORPHINE HYDROCHLORIDE', 'NALOXONE HYDROCHLORIDE'], true),
('BUPROPION HYDROCHLORIDE', 'Bupropion', 'Tier 1', 'Preferred', false, '{}', true),
('BUSPAR', 'Buspirone', 'Tier 1', 'Preferred', false, '{}', true),
('BUSPIRONE HYDROCHLORIDE', 'Buspirone', 'Tier 1', 'Preferred', false, '{}', true),
('BUSULFAN', 'Busulfan', 'Tier 3', 'Preferred', false, '{}', true),
('BUTALBITAL AND ACETAMINOPHEN', 'Butalbital/Acetaminophen', 'Tier 1', 'Preferred', true, ARRAY['BUTALBITAL', 'ACETAMINOPHEN'], true),
('BUTORPHANOL TARTRATE', 'Butorphanol', 'Tier 2', 'Preferred', false, '{}', true),
('BUTRANS', 'Buprenorphine Transdermal', 'Tier 3', 'Preferred', false, '{}', true),
('BYETTA', 'Exenatide', 'Tier 2', 'Preferred', false, '{}', true),
('BYDUREON', 'Exenatide Extended-Release', 'Tier 2', 'Preferred', false, '{}', true),
('BYSTOLIC', 'Nebivolol', 'Tier 2', 'Preferred', false, '{}', true)
ON CONFLICT (medication_name) DO NOTHING;
