/*
  # Seed Drug Formulary - Batch 5 (I-J-K Medications)
  
  1. Data Seeding
    - Medications starting with I, J, and K (~150 entries)
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Ibandronate', 'ibandronate', 'Bisphosphonate', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['150mg', '3mg/3ml'], false, true),
  ('Ibrance', 'palbociclib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['75mg', '100mg', '125mg'], false, true),
  ('Ibuprofen', 'ibuprofen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Suspension'], ARRAY['200mg', '400mg', '600mg', '800mg', '100mg/5ml'], false, true),
  ('Iclusig', 'ponatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg', '45mg'], false, true),
  ('Idarubicin', 'idarubicin', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1mg/ml'], false, true),
  ('Ifex', 'ifosfamide', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g', '3g'], false, true),
  ('Ilaris', 'canakinumab', 'Interleukin-1 Inhibitor', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['150mg/ml'], false, true),
  ('Iloperidone', 'iloperidone', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '4mg', '6mg', '8mg', '10mg', '12mg'], false, true),
  ('Imatinib', 'imatinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '400mg'], false, true),
  ('Imbruvica', 'ibrutinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['70mg', '140mg', '280mg', '420mg', '560mg'], false, true),
  ('Imdur', 'isosorbide mononitrate', 'Antianginal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['30mg', '60mg', '120mg'], false, true),
  ('Imipenem/Cilastatin', 'imipenem/cilastatin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mg', '500mg'], true, true),
  ('Imipramine', 'imipramine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['10mg', '25mg', '50mg', '75mg', '100mg', '125mg', '150mg'], false, true),
  ('Imiquimod', 'imiquimod', 'Immunomodulator', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream'], ARRAY['3.75%', '5%'], false, true),
  ('Imitrex', 'sumatriptan', 'Antimigraine', 'Tier 1', 'Preferred', ARRAY['Oral', 'Nasal', 'Injection'], ARRAY['Tablet', 'Spray', 'Injection'], ARRAY['25mg', '50mg', '100mg', '5mg', '20mg', '4mg/0.5ml', '6mg/0.5ml'], false, true),
  ('Imodium', 'loperamide', 'Antidiarrheal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Liquid'], ARRAY['2mg', '1mg/5ml'], false, true),
  ('Imovax', 'rabies vaccine', 'Vaccine', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2.5 IU'], false, true),
  ('Imuran', 'azathioprine', 'Immunosuppressant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['50mg', '100mg/20ml'], false, true),
  ('Incivek', 'telaprevir', 'Antiviral', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['375mg'], false, true),
  ('Increlex', 'mecasermin', 'Growth Factor', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['40mg/4ml'], false, true),
  ('Indapamide', 'indapamide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.25mg', '2.5mg'], false, true),
  ('Inderal', 'propranolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['10mg', '20mg', '40mg', '60mg', '80mg', '4mg/ml', '8mg/ml'], false, true),
  ('Inderal LA', 'propranolol extended-release', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['60mg', '80mg', '120mg', '160mg'], false, true),
  ('Indomethacin', 'indomethacin', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal'], ARRAY['Capsule', 'Suppository', 'Suspension'], ARRAY['25mg', '50mg', '75mg', '50mg', '25mg/5ml'], false, true),
  ('Infanrix', 'DTaP vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], false, true),
  ('Infed', 'iron dextran', 'Iron Supplement', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['50mg/ml'], false, true),
  ('Inflectra', 'infliximab-dyyb', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg'], false, true),
  ('Infliximab', 'infliximab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg'], false, true),
  ('Influenza Vaccine', 'influenza vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection', 'Nasal'], ARRAY['Injection', 'Spray'], ARRAY['0.5ml', '0.2ml'], false, true),
  ('Ingrezza', 'valbenazine', 'VMAT2 Inhibitor', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['40mg', '60mg', '80mg'], false, true),
  ('Inlyta', 'axitinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '5mg'], false, true),
  ('Innopran XL', 'propranolol extended-release', 'Beta Blocker', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['80mg', '120mg'], false, true),
  ('Inspra', 'eplerenone', 'Aldosterone Antagonist', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg'], false, true),
  ('Insulin Aspart', 'insulin aspart', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Insulin Detemir', 'insulin detemir', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Insulin Glargine', 'insulin glargine', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml', '300 units/ml'], false, true),
  ('Insulin Glulisine', 'insulin glulisine', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml'], false, true),
  ('Insulin Lispro', 'insulin lispro', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml', '200 units/ml'], false, true),
  ('Intelence', 'etravirine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Intermezzo', 'zolpidem sublingual', 'Sedative/Hypnotic', 'Tier 2', 'Preferred', ARRAY['Sublingual'], ARRAY['Tablet'], ARRAY['1.75mg', '3.5mg'], false, true),
  ('Intron A', 'interferon alfa-2b', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10 million units', '18 million units', '50 million units'], false, true),
  ('Intuniv', 'guanfacine extended-release', 'ADHD Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '3mg', '4mg'], false, true),
  ('Invanz', 'ertapenem', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g'], false, true),
  ('Invega', 'paliperidone', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1.5mg', '3mg', '6mg', '9mg'], false, true),
  ('Invega Sustenna', 'paliperidone palmitate', 'Antipsychotic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['39mg', '78mg', '117mg', '156mg', '234mg'], false, true),
  ('Invirase', 'saquinavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['500mg', '200mg'], false, true),
  ('Invokana', 'canagliflozin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '300mg'], false, true),
  ('Invokamet', 'canagliflozin/metformin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/500mg', '50/1000mg', '150/500mg', '150/1000mg'], true, true),
  ('Ipratropium', 'ipratropium bromide', 'Anticholinergic', 'Tier 1', 'Preferred', ARRAY['Inhalation', 'Nasal'], ARRAY['Inhaler', 'Nebulizer Solution', 'Spray'], ARRAY['17mcg', '0.02%', '0.03%', '0.06%'], false, true),
  ('Ipratropium/Albuterol', 'ipratropium/albuterol', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler', 'Nebulizer Solution'], ARRAY['18/90mcg', '0.5/2.5mg/3ml'], true, true),
  ('Irbesartan', 'irbesartan', 'ARB', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['75mg', '150mg', '300mg'], false, true),
  ('Irbesartan/HCTZ', 'irbesartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150/12.5mg', '300/12.5mg', '300/25mg'], true, true),
  ('Iressa', 'gefitinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg'], false, true),
  ('Irinotecan', 'irinotecan', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['20mg/ml'], false, true),
  ('Isentress', 'raltegravir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Chewable Tablet', 'Packet'], ARRAY['400mg', '600mg', '25mg', '100mg'], false, true),
  ('Isoniazid', 'isoniazid', 'Antitubercular', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Syrup', 'Injection'], ARRAY['100mg', '300mg', '50mg/5ml', '100mg/ml'], false, true),
  ('Isoptin SR', 'verapamil sustained-release', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['120mg', '180mg', '240mg'], false, true),
  ('Isosorbide Dinitrate', 'isosorbide dinitrate', 'Antianginal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Sublingual'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg', '30mg', '40mg', '2.5mg', '5mg'], false, true),
  ('Isosorbide Mononitrate', 'isosorbide mononitrate', 'Antianginal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '30mg', '60mg', '120mg'], false, true),
  ('Isotretinoin', 'isotretinoin', 'Retinoid', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg', '30mg', '40mg'], false, true),
  ('Isradipine', 'isradipine', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['2.5mg', '5mg'], false, true),
  ('Itraconazole', 'itraconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Solution'], ARRAY['100mg', '10mg/ml'], false, true),
  ('Ivermectin', 'ivermectin', 'Antiparasitic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Cream', 'Lotion'], ARRAY['3mg', '0.5%', '1%'], false, true),
  ('Ixempra', 'ixabepilone', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['15mg', '45mg'], false, true),
  ('Jadenu', 'deferasirox', 'Chelating Agent', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['90mg', '180mg', '360mg'], false, true),
  ('Jakafi', 'ruxolitinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '15mg', '20mg', '25mg'], false, true),
  ('Jantoven', 'warfarin', 'Anticoagulant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '2.5mg', '3mg', '4mg', '5mg', '6mg', '7.5mg', '10mg'], false, true),
  ('Janumet', 'sitagliptin/metformin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/500mg', '50/1000mg'], true, true),
  ('Janumet XR', 'sitagliptin/metformin XR', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/500mg', '50/1000mg', '100/1000mg'], true, true),
  ('Januvia', 'sitagliptin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Jardiance', 'empagliflozin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '25mg'], false, true),
  ('Jalyn', 'dutasteride/tamsulosin', 'BPH Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['0.5/0.4mg'], true, true),
  ('Jevtana', 'cabazitaxel', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['60mg/1.5ml'], false, true),
  ('Jublia', 'efinaconazole', 'Antifungal', 'Tier 3', 'Non-Preferred', ARRAY['Topical'], ARRAY['Solution'], ARRAY['10%'], false, true),
  ('Juluca', 'dolutegravir/rilpivirine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/25mg'], true, true),
  ('Juxtapid', 'lomitapide', 'Antilipemic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['5mg', '10mg', '20mg', '30mg', '40mg', '60mg'], false, true),
  ('Kadian', 'morphine sulfate extended-release', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['10mg', '20mg', '30mg', '40mg', '50mg', '60mg', '80mg', '100mg', '200mg'], false, true),
  ('Kaletra', 'lopinavir/ritonavir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['200/50mg', '100/25mg', '80/20mg/ml'], true, true),
  ('Kapvay', 'clonidine extended-release', 'ADHD Agent', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.1mg'], false, true),
  ('Kayexalate', 'sodium polystyrene sulfonate', 'Potassium Binder', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal'], ARRAY['Powder', 'Suspension'], ARRAY['15g/60ml'], false, true),
  ('Keflex', 'cephalexin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Suspension'], ARRAY['250mg', '500mg', '750mg', '125mg/5ml', '250mg/5ml'], false, true),
  ('Kenalog', 'triamcinolone acetonide', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Topical', 'Injection'], ARRAY['Cream', 'Ointment', 'Lotion', 'Spray', 'Injection'], ARRAY['0.025%', '0.1%', '0.5%', '10mg/ml', '40mg/ml'], false, true),
  ('Keppra', 'levetiracetam', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['250mg', '500mg', '750mg', '1000mg', '100mg/ml', '500mg/5ml'], false, true),
  ('Keppra XR', 'levetiracetam extended-release', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '750mg'], false, true),
  ('Kerydin', 'tavaborole', 'Antifungal', 'Tier 3', 'Non-Preferred', ARRAY['Topical'], ARRAY['Solution'], ARRAY['5%'], false, true),
  ('Ketamine', 'ketamine', 'Anesthetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg/ml', '50mg/ml', '100mg/ml'], false, true),
  ('Ketoconazole', 'ketoconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Cream', 'Shampoo', 'Foam', 'Gel'], ARRAY['200mg', '2%'], false, true),
  ('Ketoprofen', 'ketoprofen', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['50mg', '75mg', '100mg', '150mg', '200mg'], false, true),
  ('Ketorolac', 'ketorolac', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Ophthalmic', 'Nasal'], ARRAY['Tablet', 'Injection', 'Solution', 'Spray'], ARRAY['10mg', '15mg/ml', '30mg/ml', '0.4%', '0.45%', '0.5%', '15.75mg'], false, true),
  ('Ketotifen', 'ketotifen', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.025%'], false, true),
  ('Keytruda', 'pembrolizumab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['25mg/ml', '100mg/4ml'], false, true),
  ('Kineret', 'anakinra', 'Interleukin-1 Inhibitor', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg/0.67ml'], false, true),
  ('Klonopin', 'clonazepam', 'Anticonvulsant/Anxiolytic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['0.5mg', '1mg', '2mg', '0.125mg', '0.25mg'], false, true),
  ('Klor-Con', 'potassium chloride', 'Electrolyte', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Powder', 'Liquid'], ARRAY['8mEq', '10mEq', '20mEq', '25mEq'], false, true),
  ('Korlym', 'mifepristone', 'Glucocorticoid Antagonist', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['300mg'], false, true),
  ('Krystexxa', 'pegloticase', 'Uric Acid Reducer', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['8mg/ml'], false, true),
  ('K-Tab', 'potassium chloride', 'Electrolyte', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mEq', '20mEq'], false, true),
  ('Kuvan', 'sapropterin', 'PKU Agent', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['100mg'], false, true),
  ('Kyleena', 'levonorgestrel IUD', 'Contraceptive', 'Tier 2', 'Preferred', ARRAY['Intrauterine'], ARRAY['IUD'], ARRAY['19.5mg'], false, true),
  ('Kyprolis', 'carfilzomib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg', '30mg', '60mg'], false, true),
  ('Kytril', 'granisetron', 'Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['1mg', '2mg/10ml', '0.1mg/ml', '1mg/ml'], false, true)
ON CONFLICT (medication_name) DO NOTHING;
