/*
  # Seed Drug Formulary - Batch 9 (T-Z Medications)
  
  1. Data Seeding
    - Medications starting with T through Z (~250 entries)
*/

INSERT INTO drug_formulary (medication_name, generic_name, therapeutic_class, tier, formulary_status, route_of_administration, default_dosage_forms, default_strengths, is_combination, is_active)
VALUES
  ('Tacrolimus', 'tacrolimus', 'Immunosuppressant', 'Tier 2', 'Preferred', ARRAY['Oral', 'Topical', 'Injection'], ARRAY['Capsule', 'Ointment', 'Injection'], ARRAY['0.5mg', '1mg', '5mg', '0.03%', '0.1%', '5mg/ml'], false, true),
  ('Tadalafil', 'tadalafil', 'PDE5 Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg', '20mg'], false, true),
  ('Tafinlar', 'dabrafenib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['50mg', '75mg'], false, true),
  ('Tagrisso', 'osimertinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['40mg', '80mg'], false, true),
  ('Taltz', 'ixekizumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['80mg/ml'], false, true),
  ('Tambocor', 'flecainide', 'Antiarrhythmic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg', '150mg'], false, true),
  ('Tamiflu', 'oseltamivir', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Suspension'], ARRAY['30mg', '45mg', '75mg', '6mg/ml'], false, true),
  ('Tamoxifen', 'tamoxifen', 'Antineoplastic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg'], false, true),
  ('Tamsulosin', 'tamsulosin', 'Alpha Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['0.4mg'], false, true),
  ('Tapazole', 'methimazole', 'Antithyroid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Tapentadol', 'tapentadol', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '75mg', '100mg'], false, true),
  ('Tarceva', 'erlotinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '100mg', '150mg'], false, true),
  ('Targretin', 'bexarotene', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Capsule', 'Gel'], ARRAY['75mg', '1%'], false, true),
  ('Tasigna', 'nilotinib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['150mg', '200mg'], false, true),
  ('Tasmar', 'tolcapone', 'Antiparkinson', 'Tier 3', 'Non-Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Tavist', 'clemastine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Syrup'], ARRAY['1.34mg', '2.68mg', '0.67mg/5ml'], false, true),
  ('Taxol', 'paclitaxel', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['6mg/ml'], false, true),
  ('Taxotere', 'docetaxel', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['10mg/ml', '20mg/ml'], false, true),
  ('Tazicef', 'ceftazidime', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1g', '2g', '6g'], false, true),
  ('Tazorac', 'tazarotene', 'Retinoid', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Gel'], ARRAY['0.05%', '0.1%'], false, true),
  ('Tecfidera', 'dimethyl fumarate', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['120mg', '240mg'], false, true),
  ('Tegretol', 'carbamazepine', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension', 'Chewable Tablet'], ARRAY['200mg', '100mg/5ml', '100mg'], false, true),
  ('Tegretol XR', 'carbamazepine extended-release', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg', '400mg'], false, true),
  ('Tekturna', 'aliskiren', 'Renin Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg', '300mg'], false, true),
  ('Telmisartan', 'telmisartan', 'ARB', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['20mg', '40mg', '80mg'], false, true),
  ('Temazepam', 'temazepam', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['7.5mg', '15mg', '22.5mg', '30mg'], false, true),
  ('Temodar', 'temozolomide', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['5mg', '20mg', '100mg', '140mg', '180mg', '250mg', '100mg'], false, true),
  ('Tenofovir', 'tenofovir disoproxil fumarate', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['150mg', '200mg', '250mg', '300mg', '40mg/scoop'], false, true),
  ('Tenoretic', 'atenolol/chlorthalidone', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/25mg', '100/25mg'], true, true),
  ('Tenormin', 'atenolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Terazosin', 'terazosin', 'Alpha Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1mg', '2mg', '5mg', '10mg'], false, true),
  ('Terbinafine', 'terbinafine', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical'], ARRAY['Tablet', 'Cream', 'Gel', 'Solution'], ARRAY['250mg', '1%'], false, true),
  ('Terbutaline', 'terbutaline', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['2.5mg', '5mg', '1mg/ml'], false, true),
  ('Teriparatide', 'teriparatide', 'Bone Agent', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['250mcg/ml'], false, true),
  ('Tessalon', 'benzonatate', 'Antitussive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg', '200mg'], false, true),
  ('Testosterone', 'testosterone', 'Hormone', 'Tier 2', 'Preferred', ARRAY['Injection', 'Topical', 'Transdermal', 'Buccal', 'Nasal'], ARRAY['Injection', 'Gel', 'Solution', 'Patch', 'Tablet', 'Spray'], ARRAY['100mg/ml', '200mg/ml', '1%', '1.62%', '2mg', '4mg', '30mg'], false, true),
  ('Tetracycline', 'tetracycline', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['250mg', '500mg'], false, true),
  ('Tetrahydrozoline', 'tetrahydrozoline', 'Decongestant', 'Tier 1', 'Preferred', ARRAY['Ophthalmic', 'Nasal'], ARRAY['Solution', 'Spray'], ARRAY['0.05%', '0.1%'], false, true),
  ('Theo-24', 'theophylline', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['100mg', '200mg', '300mg', '400mg'], false, true),
  ('Theophylline', 'theophylline', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Elixir'], ARRAY['100mg', '200mg', '300mg', '400mg', '450mg', '600mg', '80mg/15ml'], false, true),
  ('Thiamine', 'thiamine', 'Vitamin B1', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['50mg', '100mg', '250mg', '500mg', '100mg/ml'], false, true),
  ('Thioridazine', 'thioridazine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '25mg', '50mg', '100mg'], false, true),
  ('Thiothixene', 'thiothixene', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1mg', '2mg', '5mg', '10mg', '20mg'], false, true),
  ('Thyroid', 'thyroid desiccated', 'Thyroid Hormone', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['15mg', '30mg', '60mg', '90mg', '120mg', '180mg', '240mg', '300mg'], false, true),
  ('Tiagabine', 'tiagabine', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2mg', '4mg', '12mg', '16mg'], false, true),
  ('Tiazac', 'diltiazem extended-release', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['120mg', '180mg', '240mg', '300mg', '360mg', '420mg'], false, true),
  ('Ticagrelor', 'ticagrelor', 'Antiplatelet', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['60mg', '90mg'], false, true),
  ('Ticlid', 'ticlopidine', 'Antiplatelet', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg'], false, true),
  ('Tikosyn', 'dofetilide', 'Antiarrhythmic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['125mcg', '250mcg', '500mcg'], false, true),
  ('Timolol', 'timolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Ophthalmic'], ARRAY['Tablet', 'Solution', 'Gel'], ARRAY['5mg', '10mg', '20mg', '0.25%', '0.5%'], false, true),
  ('Timoptic', 'timolol ophthalmic', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution', 'Gel'], ARRAY['0.25%', '0.5%'], false, true),
  ('Tinidazole', 'tinidazole', 'Antiprotozoal', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg', '500mg'], false, true),
  ('Tioconazole', 'tioconazole', 'Antifungal', 'Tier 1', 'Preferred', ARRAY['Vaginal'], ARRAY['Ointment'], ARRAY['6.5%'], false, true),
  ('Tiotropium', 'tiotropium', 'Anticholinergic', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Capsule', 'Inhaler'], ARRAY['18mcg', '1.25mcg', '2.5mcg'], false, true),
  ('Tivicay', 'dolutegravir', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '25mg', '50mg'], false, true),
  ('Tizanidine', 'tizanidine', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['2mg', '4mg', '6mg'], false, true),
  ('Tobramycin', 'tobramycin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Injection', 'Ophthalmic', 'Inhalation'], ARRAY['Injection', 'Solution', 'Ointment', 'Nebulizer Solution'], ARRAY['10mg/ml', '40mg/ml', '0.3%', '300mg/5ml'], false, true),
  ('Tobrex', 'tobramycin ophthalmic', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution', 'Ointment'], ARRAY['0.3%'], false, true),
  ('Tofacitinib', 'tofacitinib', 'JAK Inhibitor', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '10mg', '11mg', '1mg/ml'], false, true),
  ('Tofranil', 'imipramine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['10mg', '25mg', '50mg', '75mg', '100mg', '125mg', '150mg'], false, true),
  ('Tolazamide', 'tolazamide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '250mg', '500mg'], false, true),
  ('Tolbutamide', 'tolbutamide', 'Antidiabetic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg'], false, true),
  ('Tolmetin', 'tolmetin', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['200mg', '400mg', '600mg'], false, true),
  ('Tolterodine', 'tolterodine', 'Urinary Antispasmodic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['1mg', '2mg', '4mg'], false, true),
  ('Topamax', 'topiramate', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['25mg', '50mg', '100mg', '200mg', '15mg', '25mg'], false, true),
  ('Topicort', 'desoximetasone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Topical'], ARRAY['Cream', 'Ointment', 'Gel', 'Spray'], ARRAY['0.05%', '0.25%'], false, true),
  ('Topiramate', 'topiramate', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['25mg', '50mg', '100mg', '200mg', '15mg', '25mg'], false, true),
  ('Topotecan', 'topotecan', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['0.25mg', '1mg', '4mg/ml'], false, true),
  ('Toprol XL', 'metoprolol succinate', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg', '200mg'], false, true),
  ('Toradol', 'ketorolac', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['10mg', '15mg/ml', '30mg/ml'], false, true),
  ('Torisel', 'temsirolimus', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['25mg/ml'], false, true),
  ('Torsemide', 'torsemide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['5mg', '10mg', '20mg', '100mg', '10mg/ml'], false, true),
  ('Toujeo', 'insulin glargine', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['300 units/ml'], false, true),
  ('Toviaz', 'fesoterodine', 'Urinary Antispasmodic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['4mg', '8mg'], false, true),
  ('Tradjenta', 'linagliptin', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg'], false, true),
  ('Tramadol', 'tramadol', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['50mg', '100mg', '200mg', '300mg'], false, true),
  ('Trandolapril', 'trandolapril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '4mg'], false, true),
  ('Tranexamic Acid', 'tranexamic acid', 'Antifibrinolytic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['650mg', '100mg/ml'], false, true),
  ('Transderm-Scop', 'scopolamine', 'Antiemetic', 'Tier 1', 'Preferred', ARRAY['Transdermal'], ARRAY['Patch'], ARRAY['1.5mg'], false, true),
  ('Tranylcypromine', 'tranylcypromine', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg'], false, true),
  ('Trastuzumab', 'trastuzumab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['150mg', '440mg'], false, true),
  ('Travatan', 'travoprost', 'Prostaglandin Analog', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.004%'], false, true),
  ('Trazodone', 'trazodone', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg', '150mg', '300mg'], false, true),
  ('Trelegy', 'fluticasone/umeclidinium/vilanterol', 'Corticosteroid/Anticholinergic/LABA', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['100/62.5/25mcg', '200/62.5/25mcg'], true, true),
  ('Trelstar', 'triptorelin', 'GnRH Agonist', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['3.75mg', '11.25mg', '22.5mg'], false, true),
  ('Tremfya', 'guselkumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100mg/ml'], false, true),
  ('Tresiba', 'insulin degludec', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100 units/ml', '200 units/ml'], false, true),
  ('Tretinoin', 'tretinoin', 'Retinoid', 'Tier 1', 'Preferred', ARRAY['Topical', 'Oral'], ARRAY['Cream', 'Gel', 'Capsule'], ARRAY['0.025%', '0.05%', '0.1%', '10mg'], false, true),
  ('Triamcinolone', 'triamcinolone', 'Corticosteroid', 'Tier 1', 'Preferred', ARRAY['Topical', 'Injection', 'Nasal', 'Dental'], ARRAY['Cream', 'Ointment', 'Lotion', 'Spray', 'Injection', 'Paste'], ARRAY['0.025%', '0.1%', '0.5%', '55mcg', '10mg/ml', '40mg/ml', '0.1%'], false, true),
  ('Triamterene', 'triamterene', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['50mg', '100mg'], false, true),
  ('Triamterene/HCTZ', 'triamterene/hydrochlorothiazide', 'Diuretic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['37.5/25mg', '75/50mg'], true, true),
  ('Triazolam', 'triazolam', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.125mg', '0.25mg'], false, true),
  ('Tricor', 'fenofibrate', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['48mg', '145mg'], false, true),
  ('Trileptal', 'oxcarbazepine', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['150mg', '300mg', '600mg', '300mg/5ml'], false, true),
  ('Trilipix', 'fenofibric acid', 'Antilipemic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['45mg', '135mg'], false, true),
  ('Trimethobenzamide', 'trimethobenzamide', 'Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['300mg', '100mg/ml'], false, true),
  ('Trimethoprim', 'trimethoprim', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg'], false, true),
  ('Trintellix', 'vortioxetine', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg'], false, true),
  ('Triumeq', 'abacavir/dolutegravir/lamivudine', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['600/50/300mg'], true, true),
  ('Trokendi XR', 'topiramate extended-release', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['25mg', '50mg', '100mg', '200mg'], false, true),
  ('Tropicamide', 'tropicamide', 'Mydriatic', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.5%', '1%'], false, true),
  ('Trospium', 'trospium', 'Urinary Antispasmodic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['20mg', '60mg'], false, true),
  ('Trulicity', 'dulaglutide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.75mg/0.5ml', '1.5mg/0.5ml', '3mg/0.5ml', '4.5mg/0.5ml'], false, true),
  ('Trumenba', 'meningococcal B vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], false, true),
  ('Truvada', 'emtricitabine/tenofovir DF', 'Antiretroviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100/150mg', '133/200mg', '167/250mg', '200/300mg'], true, true),
  ('Tudorza', 'aclidinium', 'Anticholinergic', 'Tier 2', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler'], ARRAY['400mcg'], false, true),
  ('Tussionex', 'hydrocodone/chlorpheniramine', 'Antitussive', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Suspension'], ARRAY['10/8mg per 5ml'], true, true),
  ('Twinrix', 'hepatitis A/B vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['720/20mcg'], true, true),
  ('Tylenol', 'acetaminophen', 'Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Rectal'], ARRAY['Tablet', 'Capsule', 'Liquid', 'Suppository'], ARRAY['325mg', '500mg', '650mg', '160mg/5ml', '120mg', '325mg', '650mg'], false, true),
  ('Tysabri', 'natalizumab', 'Immunomodulator', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['300mg/15ml'], false, true),
  ('Tyvaso', 'treprostinil', 'Pulmonary Vasodilator', 'Tier 3', 'Preferred', ARRAY['Inhalation'], ARRAY['Nebulizer Solution'], ARRAY['0.6mg/ml'], false, true),
  ('Ubrelvy', 'ubrogepant', 'CGRP Antagonist', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg', '100mg'], false, true),
  ('Uloric', 'febuxostat', 'Antigout', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['40mg', '80mg'], false, true),
  ('Ultracet', 'tramadol/acetaminophen', 'Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['37.5/325mg'], true, true),
  ('Ultram', 'tramadol', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50mg'], false, true),
  ('Ultram ER', 'tramadol extended-release', 'Opioid Analgesic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '200mg', '300mg'], false, true),
  ('Unasyn', 'ampicillin/sulbactam', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['1.5g', '3g'], true, true),
  ('Unisom', 'doxylamine', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg'], false, true),
  ('Urelle', 'methenamine/sodium phosphate/phenyl salicylate/methylene blue/hyoscyamine', 'Urinary Antiseptic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['81.6/40.8/36.2/10.8/0.12mg'], true, true),
  ('Uroxatral', 'alfuzosin', 'Alpha Blocker', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg'], false, true),
  ('Ursodiol', 'ursodiol', 'Bile Acid', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['250mg', '300mg', '500mg'], false, true),
  ('Valacyclovir', 'valacyclovir', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '1g'], false, true),
  ('Valcyte', 'valganciclovir', 'Antiviral', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['450mg', '50mg/ml'], false, true),
  ('Valium', 'diazepam', 'Benzodiazepine', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Rectal'], ARRAY['Tablet', 'Solution', 'Injection', 'Gel'], ARRAY['2mg', '5mg', '10mg', '5mg/ml', '5mg/5ml', '2.5mg', '10mg', '20mg'], false, true),
  ('Valproic Acid', 'valproic acid', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Syrup', 'Injection'], ARRAY['250mg', '500mg', '250mg/5ml', '100mg/ml'], false, true),
  ('Valsartan', 'valsartan', 'ARB', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['40mg', '80mg', '160mg', '320mg'], false, true),
  ('Valsartan/HCTZ', 'valsartan/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['80/12.5mg', '160/12.5mg', '160/25mg', '320/12.5mg', '320/25mg'], true, true),
  ('Valtrex', 'valacyclovir', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['500mg', '1g'], false, true),
  ('Vancocin', 'vancomycin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Solution', 'Injection'], ARRAY['125mg', '250mg', '500mg', '1g'], false, true),
  ('Vancomycin', 'vancomycin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Solution', 'Injection'], ARRAY['125mg', '250mg', '500mg', '750mg', '1g', '5mg/ml', '10mg/ml'], false, true),
  ('Vanos', 'fluocinonide', 'Corticosteroid', 'Tier 2', 'Preferred', ARRAY['Topical'], ARRAY['Cream'], ARRAY['0.1%'], false, true),
  ('Vaqta', 'hepatitis A vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['25 units', '50 units'], false, true),
  ('Vardenafil', 'vardenafil', 'PDE5 Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT'], ARRAY['2.5mg', '5mg', '10mg', '20mg'], false, true),
  ('Varivax', 'varicella vaccine', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.5ml'], false, true),
  ('Vasotec', 'enalapril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Injection'], ARRAY['2.5mg', '5mg', '10mg', '20mg', '1.25mg/ml'], false, true),
  ('Velcade', 'bortezomib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['3.5mg'], false, true),
  ('Venlafaxine', 'venlafaxine', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['25mg', '37.5mg', '50mg', '75mg', '100mg', '37.5mg', '75mg', '150mg', '225mg'], false, true),
  ('Ventolin', 'albuterol', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler', 'Nebulizer Solution'], ARRAY['90mcg', '0.083%', '0.5%'], false, true),
  ('Verapamil', 'verapamil', 'Calcium Channel Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Capsule', 'Injection'], ARRAY['40mg', '80mg', '120mg', '120mg', '180mg', '240mg', '360mg', '2.5mg/ml'], false, true),
  ('Versed', 'midazolam', 'Benzodiazepine', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Nasal'], ARRAY['Syrup', 'Injection', 'Spray'], ARRAY['2mg/ml', '1mg/ml', '5mg/ml', '5mg'], false, true),
  ('Vesicare', 'solifenacin', 'Urinary Antispasmodic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Vfend', 'voriconazole', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['50mg', '200mg', '40mg/ml', '200mg'], false, true),
  ('Viagra', 'sildenafil', 'PDE5 Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Vibramycin', 'doxycycline', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet', 'Syrup', 'Suspension'], ARRAY['50mg', '100mg', '50mg/5ml', '25mg/5ml'], false, true),
  ('Vicodin', 'hydrocodone/acetaminophen', 'Opioid Analgesic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5/300mg', '7.5/300mg', '10/300mg'], true, true),
  ('Victoza', 'liraglutide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['6mg/ml'], false, true),
  ('Vigabatrin', 'vigabatrin', 'Anticonvulsant', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['500mg'], false, true),
  ('Viibryd', 'vilazodone', 'Antidepressant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg', '20mg', '40mg'], false, true),
  ('Vimovo', 'naproxen/esomeprazole', 'NSAID/PPI', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['375/20mg', '500/20mg'], true, true),
  ('Vimpat', 'lacosamide', 'Anticonvulsant', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Solution', 'Injection'], ARRAY['50mg', '100mg', '150mg', '200mg', '10mg/ml'], false, true),
  ('Viokace', 'pancrelipase', 'Digestive Enzyme', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10440 units', '20880 units'], false, true),
  ('Viramune', 'nevirapine', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Suspension'], ARRAY['200mg', '400mg', '50mg/5ml'], false, true),
  ('Viread', 'tenofovir disoproxil fumarate', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['150mg', '200mg', '250mg', '300mg', '40mg/scoop'], false, true),
  ('Vistaril', 'hydroxyzine pamoate', 'Antihistamine/Anxiolytic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Suspension'], ARRAY['25mg', '50mg', '100mg', '25mg/5ml'], false, true),
  ('Vitamin B12', 'cyanocobalamin', 'Vitamin', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection', 'Nasal'], ARRAY['Tablet', 'Injection', 'Spray'], ARRAY['100mcg', '250mcg', '500mcg', '1000mcg', '1000mcg/ml'], false, true),
  ('Vitamin D', 'cholecalciferol', 'Vitamin', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Liquid'], ARRAY['400 IU', '1000 IU', '2000 IU', '5000 IU', '50000 IU'], false, true),
  ('Voltaren', 'diclofenac', 'NSAID', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical', 'Ophthalmic'], ARRAY['Tablet', 'Gel', 'Solution'], ARRAY['25mg', '50mg', '75mg', '1%', '0.1%'], false, true),
  ('Voriconazole', 'voriconazole', 'Antifungal', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['50mg', '200mg', '40mg/ml', '200mg'], false, true),
  ('Votrient', 'pazopanib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg'], false, true),
  ('Vraylar', 'cariprazine', 'Antipsychotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['1.5mg', '3mg', '4.5mg', '6mg'], false, true),
  ('Vyvanse', 'lisdexamfetamine', 'CNS Stimulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Chewable Tablet'], ARRAY['10mg', '20mg', '30mg', '40mg', '50mg', '60mg', '70mg'], false, true),
  ('Warfarin', 'warfarin', 'Anticoagulant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['1mg', '2mg', '2.5mg', '3mg', '4mg', '5mg', '6mg', '7.5mg', '10mg'], false, true),
  ('Welchol', 'colesevelam', 'Antilipemic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Powder'], ARRAY['625mg', '3.75g'], false, true),
  ('Wellbutrin', 'bupropion', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['75mg', '100mg'], false, true),
  ('Wellbutrin SR', 'bupropion sustained-release', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '150mg', '200mg'], false, true),
  ('Wellbutrin XL', 'bupropion extended-release', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg', '300mg', '450mg'], false, true),
  ('Xalatan', 'latanoprost', 'Prostaglandin Analog', 'Tier 1', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['0.005%'], false, true),
  ('Xanax', 'alprazolam', 'Benzodiazepine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'ODT', 'Solution'], ARRAY['0.25mg', '0.5mg', '1mg', '2mg', '1mg/ml'], false, true),
  ('Xanax XR', 'alprazolam extended-release', 'Benzodiazepine', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['0.5mg', '1mg', '2mg', '3mg'], false, true),
  ('Xarelto', 'rivaroxaban', 'Anticoagulant', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '10mg', '15mg', '20mg'], false, true),
  ('Xeloda', 'capecitabine', 'Antineoplastic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg', '500mg'], false, true),
  ('Xeljanz', 'tofacitinib', 'JAK Inhibitor', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['5mg', '10mg', '11mg', '1mg/ml'], false, true),
  ('Xenical', 'orlistat', 'Weight Loss Agent', 'Tier 2', 'Non-Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['120mg'], false, true),
  ('Xifaxan', 'rifaximin', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['200mg', '550mg'], false, true),
  ('Xigduo XR', 'dapagliflozin/metformin XR', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5/1000mg', '5/500mg', '5/1000mg', '10/500mg', '10/1000mg'], true, true),
  ('Xiidra', 'lifitegrast', 'Dry Eye Agent', 'Tier 2', 'Preferred', ARRAY['Ophthalmic'], ARRAY['Solution'], ARRAY['5%'], false, true),
  ('Xolair', 'omalizumab', 'Monoclonal Antibody', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['75mg/0.5ml', '150mg/ml'], false, true),
  ('Xopenex', 'levalbuterol', 'Bronchodilator', 'Tier 1', 'Preferred', ARRAY['Inhalation'], ARRAY['Inhaler', 'Nebulizer Solution'], ARRAY['45mcg', '0.31mg/3ml', '0.63mg/3ml', '1.25mg/3ml'], false, true),
  ('Xtandi', 'enzalutamide', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Tablet'], ARRAY['40mg', '80mg'], false, true),
  ('Xultophy', 'insulin degludec/liraglutide', 'Antidiabetic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['100/3.6 units/mg'], true, true),
  ('Xyrem', 'sodium oxybate', 'CNS Depressant', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Solution'], ARRAY['500mg/ml'], false, true),
  ('Yasmin', 'drospirenone/ethinyl estradiol', 'Contraceptive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['3/0.03mg'], true, true),
  ('Yaz', 'drospirenone/ethinyl estradiol', 'Contraceptive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['3/0.02mg'], true, true),
  ('Yervoy', 'ipilimumab', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['5mg/ml'], false, true),
  ('Zanaflex', 'tizanidine', 'Muscle Relaxant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule'], ARRAY['2mg', '4mg', '6mg'], false, true),
  ('Zantac', 'ranitidine', 'H2 Blocker', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Syrup', 'Injection'], ARRAY['75mg', '150mg', '300mg', '15mg/ml', '25mg/ml'], false, true),
  ('Zarxio', 'filgrastim-sndz', 'Hematopoietic', 'Tier 3', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['300mcg/0.5ml', '480mcg/0.8ml'], false, true),
  ('Zebeta', 'bisoprolol', 'Beta Blocker', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg'], false, true),
  ('Zegerid', 'omeprazole/sodium bicarbonate', 'Proton Pump Inhibitor', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule', 'Powder'], ARRAY['20/1100mg', '40/1100mg'], true, true),
  ('Zelboraf', 'vemurafenib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['240mg'], false, true),
  ('Zenpep', 'pancrelipase', 'Digestive Enzyme', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['3000 units', '5000 units', '10000 units', '15000 units', '20000 units', '25000 units', '40000 units'], false, true),
  ('Zepatier', 'elbasvir/grazoprevir', 'Antiviral', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['50/100mg'], true, true),
  ('Zestoretic', 'lisinopril/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10/12.5mg', '20/12.5mg', '20/25mg'], true, true),
  ('Zestril', 'lisinopril', 'ACE Inhibitor', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5mg', '5mg', '10mg', '20mg', '30mg', '40mg'], false, true),
  ('Zetia', 'ezetimibe', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['10mg'], false, true),
  ('Ziac', 'bisoprolol/hydrochlorothiazide', 'Antihypertensive', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['2.5/6.25mg', '5/6.25mg', '10/6.25mg'], true, true),
  ('Ziagen', 'abacavir', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['300mg', '20mg/ml'], false, true),
  ('Zidovudine', 'zidovudine', 'Antiretroviral', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Syrup', 'Injection'], ARRAY['100mg', '300mg', '10mg/ml'], false, true),
  ('Zinbryta', 'daclizumab', 'Immunomodulator', 'Tier 3', 'Non-Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['150mg/ml'], false, true),
  ('Zinc', 'zinc sulfate', 'Mineral Supplement', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Capsule', 'Liquid'], ARRAY['220mg', '50mg', '15mg/5ml'], false, true),
  ('Ziprasidone', 'ziprasidone', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Capsule', 'Injection'], ARRAY['20mg', '40mg', '60mg', '80mg', '20mg/ml'], false, true),
  ('Zithromax', 'azithromycin', 'Antibiotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Packet', 'Injection'], ARRAY['250mg', '500mg', '100mg/5ml', '200mg/5ml', '1g', '500mg'], false, true),
  ('Zocor', 'simvastatin', 'Antilipemic', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['5mg', '10mg', '20mg', '40mg', '80mg'], false, true),
  ('Zofran', 'ondansetron', 'Antiemetic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'ODT', 'Solution', 'Injection'], ARRAY['4mg', '8mg', '4mg/5ml', '2mg/ml'], false, true),
  ('Zoladex', 'goserelin', 'GnRH Agonist', 'Tier 3', 'Preferred', ARRAY['Implant'], ARRAY['Implant'], ARRAY['3.6mg', '10.8mg'], false, true),
  ('Zoledronic Acid', 'zoledronic acid', 'Bisphosphonate', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['4mg/5ml', '5mg/100ml'], false, true),
  ('Zoloft', 'sertraline', 'Antidepressant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Solution'], ARRAY['25mg', '50mg', '100mg', '20mg/ml'], false, true),
  ('Zolpidem', 'zolpidem', 'Sedative/Hypnotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Sublingual'], ARRAY['Tablet', 'Spray'], ARRAY['5mg', '10mg', '6.25mg', '12.5mg', '1.75mg', '3.5mg', '5mg'], false, true),
  ('Zometa', 'zoledronic acid', 'Bisphosphonate', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['4mg/5ml'], false, true),
  ('Zomig', 'zolmitriptan', 'Antimigraine', 'Tier 2', 'Preferred', ARRAY['Oral', 'Nasal'], ARRAY['Tablet', 'ODT', 'Spray'], ARRAY['2.5mg', '5mg'], false, true),
  ('Zonisamide', 'zonisamide', 'Anticonvulsant', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['25mg', '50mg', '100mg'], false, true),
  ('Zorvolex', 'diclofenac', 'NSAID', 'Tier 2', 'Preferred', ARRAY['Oral'], ARRAY['Capsule'], ARRAY['18mg', '35mg'], false, true),
  ('Zostavax', 'zoster vaccine live', 'Vaccine', 'Tier 1', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['0.65ml'], false, true),
  ('Zosyn', 'piperacillin/tazobactam', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Injection'], ARRAY['Injection'], ARRAY['2.25g', '3.375g', '4.5g'], true, true),
  ('Zovirax', 'acyclovir', 'Antiviral', 'Tier 1', 'Preferred', ARRAY['Oral', 'Topical', 'Injection'], ARRAY['Capsule', 'Tablet', 'Suspension', 'Cream', 'Ointment', 'Injection'], ARRAY['200mg', '400mg', '800mg', '200mg/5ml', '5%', '50mg/ml'], false, true),
  ('Zyban', 'bupropion sustained-release', 'Smoking Cessation', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['150mg'], false, true),
  ('Zydelig', 'idelalisib', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '150mg'], false, true),
  ('Zyloprim', 'allopurinol', 'Antigout', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['100mg', '300mg'], false, true),
  ('Zyprexa', 'olanzapine', 'Antipsychotic', 'Tier 1', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'ODT', 'Injection'], ARRAY['2.5mg', '5mg', '7.5mg', '10mg', '15mg', '20mg', '210mg', '300mg', '405mg'], false, true),
  ('Zyrtec', 'cetirizine', 'Antihistamine', 'Tier 1', 'Preferred', ARRAY['Oral'], ARRAY['Tablet', 'Syrup', 'Chewable Tablet'], ARRAY['5mg', '10mg', '5mg/5ml'], false, true),
  ('Zytiga', 'abiraterone', 'Antineoplastic', 'Tier 3', 'Preferred', ARRAY['Oral'], ARRAY['Tablet'], ARRAY['250mg', '500mg'], false, true),
  ('Zyvox', 'linezolid', 'Antibiotic', 'Tier 2', 'Preferred', ARRAY['Oral', 'Injection'], ARRAY['Tablet', 'Suspension', 'Injection'], ARRAY['600mg', '100mg/5ml', '2mg/ml'], false, true)
ON CONFLICT (medication_name) DO NOTHING;
